#!/usr/bin/env bash
#Author: linux-gaming.ru
#setup.exe
#Setup.exe
#SETUP.exe
#.msi
#Rating=5
################################################
export PW_WINE_USE="WINE-8.8-STAGING-TKG-AMD64"
[[ "${update_loc}" == "RUS" ]] && export PW_COMMENT_DB="Для установки репаков от xatab требуется использовать ${PW_WINE_USE}.\nОн загружен и выбран автоматически.\n"
export PW_DISABLED_CREATE_DB=1
export PW_ICON_FOR_YAD="${PORT_WINE_PATH}/data/img/setup.png" 
export PW_VULKAN_USE=1
export PW_MANGOHUD=0
export PW_NO_FSYNC=0        # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PW_NO_ESYNC=1        # Do not use eventfd-based in-process synchronization primitives
export PW_WINEDBG_DISABLE=1
export PW_USE_GAMEMODE=1             # Force disabele gamemod
export PW_FORCE_LARGE_ADDRESS_AWARE=1          # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
export PW_DLL_INSTALL=""
export WINEDLLOVERRIDES="mscoree,mshtml="
gui_proton_downloader silent "WINE-8.8-STAGING-TKG-AMD64"

add_in_stop_portwine () {
    pw_find_exe news
}
