#!/usr/bin/env bash
#Author: xuser
#alanwake.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="d3dx9 d3dcompiler_43"        # Install DLL in port prefix (used winetricks)
