#!/usr/bin/env bash
#Author: vano
#AliceMadnessReturns.exe
#Rating=5
#####################examples###########################
export PW_WINDOWS_VER="10"
export PW_NO_FSYNC="1"
export PW_NO_ESYNC="1"
export PW_USE_GSTREAMER="1"
export PW_WINE_USE="PROTON_LG_8-25-2"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"

gui_proton_downloader silent "$PW_WINE_USE"
