#!/usr/bin/env bash
#Author: akai
#Arthur.exe
#Rating=1-5
########################################################
export PW_VULKAN_USE=2
#####################examples###########################
export PULSE_LATENCY_MSEC=90                    # Fix crackling audio in games

