#!/usr/bin/env bash
#Author: 
#avengers.exe 
#Rating=?
################################################
export PW_VULKAN_USE=dxvk
export LAUNCH_PARAMETERS=""
#export WINEDLLOVERRIDES="atiadlxx=n"
export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
#export PW_NO_FSYNC=0                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
#export PW_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
export PW_DLL_INSTALL="d3dcompiler_47 vcrun2019"