#!/bin/bash
#Author: 
#bg3_dx11.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=dxvk
export LAUNCH_PARAMETERS=""
export PW_DLL_INSTALL="d3dcompiler_43 d3dcompiler_47 vcrun2019"
#export DXVK_HUD=1
