#!/usr/bin/env bash
#Author: kosta
#Biomutant.exe
#Rating=1-5
#####################examples###########################
export PW_VULKAN_USE=1
export PW_DLL_INSTALL="vcrun2019"               # Install DLL in port prefix (used winetricks)
