#!/usr/bin/env bash
#Author: fidel
#BsgLauncher.exe
#EscapeFromTarkov.exe
#EscapeFromTarkov_BE.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="10"
export PW_NO_FSYNC="1"
export PW_NO_ESYNC="1"
export PW_PREFIX_NAME="DOTNET"

# add_in_start_portwine () {
#     if [[ ! -f "${PATH_TO_GAME}/dxvk.conf" ]] ; then
#         echo "d3d9.shaderModel = 1" > "${PATH_TO_GAME}/dxvk.conf"
#     fi
# }
