#!/usr/bin/env bash
#Author: fidel
#caliber_launcher_pp.exe
#Rating=1-5
#####################examples###########################
export PW_VULKAN_USE="2"
export PW_WINE_USE="WINE_LG_9-0"
export PW_PREFIX_NAME="CALIBER"
export DISABLE_CP_DEFPFX=1
