#!/usr/bin/env bash
#Author: 
#CoJBiBGame_x86.exe 
#Rating=5
################################################
export PW_VULKAN_USE=dxvk
export LAUNCH_PARAMETERS=""
export PW_DLL_INSTALL="d3dx9"                 # Install DDL in port prefix (used winetricks) 
export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
