#!/usr/bin/env bash
#Author: 
#CoJBiBGame_x86.exe 
#Rating=5
################################################
export LAUNCH_PARAMETERS=""
export PW_DLL_INSTALL="d3dx9"                 # Install DLL in port prefix (used winetricks)
