#!/usr/bin/env bash
#Author: hty
#CoDSP.exe
#Rating=1-5
if [[ "$LANGUAGE" == "ru" ]] ; then
    export PW_COMMENT_DB="Нужно переименовать этот файл (файл игры) в mohaa.exe, тогда игра заработает"
else
    export PW_COMMENT_DB="Need rename this file (game file) to mohaa.exe, after this trick game will work"
fi
export PW_VULKAN_USE="0"
