#!/usr/bin/env bash
#Author: xuser
#Cyberpunk2077.exe 
#Rating=1-5
#####################examples###########################
export WINEDLLOVERRIDES="Crash*,REDEngineErrorReporter.exe="
export PW_REDUCE_PULSE_LATENCY=1
export LAUNCH_PARAMETERS=("--launcher-skip")                # Additional launch options
export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
