#!/usr/bin/env bash
#Author: xuser
#Cyberpunk2077.exe 
#Rating=1-5
#####################examples###########################
export WINEDLLOVERRIDES="Crash*,REDEngineErrorReporter.exe="
export PULSE_LATENCY_MSEC=40                    # Fix crackling audio in games
export LAUNCH_PARAMETERS=("--launcher-skip")                # Additional launch options
export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP

