#!/usr/bin/env bash
#Author: xuser
#Cyberpunk2077.exe 
#Rating=1-5
#####################examples###########################
export PW_VULKAN_USE=1
##export PW_COMMENT_DB="blablabla"
export WINEDLLOVERRIDES="Crash*,REDEngineErrorReporter.exe="
##export PW_DLL_INSTALL="d3dcompiler_47"        # Install DDL in port prefix (used winetricks) 
##export PW_LOG=0                                 # Enable debug mode fo terminal 
##export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PW_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
##export PW_VULKAN_NO_ASYNC=1                       # Disabled ASYNC for VULKAN
##export PW_USE_TERMINAL=0                        # Force run in terminal
##export PW_OLD_GL_STRING=0
##export PW_USE_NVAPI_AND_DLSS=0
##export PW_VKD3D_FEATURE_LEVEL=1
##export PW_NO_WRITE_WATCH=0                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PW_HIDE_NVIDIA_GPU=0
##export PW_FORCE_USE_VSYNC=0                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PW_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PW_USE_GAMEMODE=1              # Force disabele gamemod
##export PW_FORCE_LARGE_ADDRESS_AWARE=1           # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
export PULSE_LATENCY_MSEC=40                    # Fix crackling audio in games
export LAUNCH_PARAMETERS=("--launcher-skip")                # Additional launch options
##export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PW_VIRTUAL_DESKTOP=1
##export DXVK_HUD=fps,devinfo
export PW_HEAP_DELAY_FREE=0
##export PW_DXGI_FROM_DXVK=0
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
#add_in_start_portwine () { "${pw_runtime}" "$WINESERVER" -w }
