#!/usr/bin/env bash
#Author: xuser
#DaysGone.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="vcrun2019"               # Install DLL in port prefix (used winetricks)
export PW_NO_FSYNC=0                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PW_NO_ESYNC=0                            # Do not use eventfd-based in-process synchronization primitives
