#!/usr/bin/env bash
#Author: 
#Dead Space.exe 
#Rating=1-5
################################################
export PP_VULKAN_USE=0
export LAUNCH_PARAMETERS=""
export PP_GUI_DISABLED_CS=1                     # 1 = disabled GUI 

