#!/bin/bash
#Author: 
#ds.exe 
#Rating=5
################################################
export PW_VULKAN_USE=vkd3d
export LAUNCH_PARAMETERS=""
export WINEDLLOVERRIDES="d3dcompiler_47,dxcompiler=n,b"
