#!/usr/bin/env bash
#Author: 
#ds.exe 
#Rating=5
################################################
export PW_VULKAN_USE=1
export LAUNCH_PARAMETERS=""
export WINEDLLOVERRIDES="d3dcompiler_47,dxcompiler=n,b"
