#!/usr/bin/env bash
#Author: Eljeyna
#Deathloop.exe
#Rating=4
#####################examples###########################
if [[ "$LANGUAGE" == "ru" ]] ; then
    export PW_COMMENT_DB="При использовании DualSense следует оставить параметры нетронутыми\nЕсли проявляются проблемы с определением геймпада, выключите DINPUT PROTOCOL"
else
    export PW_COMMENT_DB="If you use DualSense do not recommended change settings\nBut if you have problems with gamepad controls, turn off DINPUT PROTOCOL parameter"
fi
export PW_VULKAN_USE="1"
export WINEDLLOVERRIDES="xaudio2_8,xaudio2_9=n"
export PW_DINPUT_PROTOCOL="1"
export PW_WINDOWS_VER="10"
export ENABLE_VKBASALT="0"
export PW_NO_ESYNC="1"
export PW_NO_FSYNC="1"
