#!/usr/bin/env bash
#Author: MrModer#6697
#DetroitBecomeHuman.exe
#Rating=1-5
################################################
export PW_VULKAN_USE=vkd3d
export PW_FORCE_USE_VSYNC=0
export PW_WINDOWS_VER="10"
#export PW_VIRTUAL_DESKTOP=1
