#!/usr/bin/env bash
#Author: nix
#DOOMx64.exe
#DOOMx64vk.exe
#Rating=1-5
########################################################
export PP_VULKAN_USE=1
#####################examples###########################
export PP_COMMENT_DB="DOOM 2016"
export PP_DLL_INSTALL="xact xact_x64 vcrun2019"
export WINEDLLOVERRIDES="xaudio2_8=n"
