#!/usr/bin/env bash
#Author: PortWINE
#EALauncher.exe
#EADesktop.exe
#Rating=5
#####################examples###########################
# export PW_DLL_INSTALL="vcrun2019"               # Install DDL in port prefix (used winetricks) 
export PW_VULKAN_USE=1                       # dxvk, vkd3d or 0 for OpenGL
export PW_USE_TERMINAL="1"
export PW_PREFIX_NAME="EA_APP"
# export PW_WINE_USE="WINE-8.8-STAGING-TKG-AMD64"
# gui_proton_downloader silent "WINE-8.8-STAGING-TKG-AMD64"
