#!/usr/bin/env bash
#Author: PortWINE
#EALauncher.exe
#EADesktop.exe
#Rating=5
#####################examples###########################
# export PW_DLL_INSTALL="vcrun2022"               # Install DDL in port prefix (used winetricks) 
export PW_VULKAN_USE=1                       # dxvk, vkd3d or 0 for OpenGL
# export PW_USE_TERMINAL="1"
export DISABLE_CP_DEFPFX=1
export PW_USE_D3D_EXTRAS=0
export PW_MUST_HAVE_DLL="d3dx9 d3dcompiler_43 d3dcompiler_47"
export PW_PREFIX_NAME="EA_APP"
export WINEDLLOVERRIDES="winemenubuilder=d"
# export PW_WINE_USE="WINE-8.8-STAGING-AMD64"
# gui_proton_downloader silent "WINE-8.8-STAGING-AMD64"
