#!/bin/bash
#Author: PortWINE
#EpicGamesLauncher.exe
#Rating=5
##############################################
export PW_COMMENT_DB="For GTA5 it is recommended to use DXVK."
export PW_WINE_USE=PROTON_GE
export PW_VULKAN_USE=1
export LAUNCH_PARAMETERS="-opengl -SkipBuildPatchPrereq"
export PW_DLL_INSTALL="vcrun2010 vcrun2012 vcrun2013 vcrun2019 d3dcompiler_43 d3dcompiler_47 d3dx9"
