#!/bin/bash
#Author: PortWINE
#EpicGamesLauncher.exe
#Rating=5
##############################################
#export PW_COMMENT_DB="PortWINE database file for Epic Games Launcher"
export PW_WINE_USE=PROTON_GE
export PW_VULKAN_USE=1
export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export LAUNCH_PARAMETERS="-opengl -SkipBuildPatchPrereq"
export PW_DLL_INSTALL="vcrun2010 vcrun2012 vcrun2013 vcrun2019 d3dcompiler_43 d3dcompiler_47 d3dx9"
