#!/bin/bash
#Author: PortWINE
#EpicGamesLauncher.exe 
#Rating=5
################################################
export WINEDLLOVERRIDES="libglesv2="
export LAUNCH_PARAMETERS="-opengl -SkipBuildPatchPrereq"
export PW_DLL_INSTALL="vcrun2010 vcrun2012 vcrun2013 vcrun2017 d3dcompiler_43 d3dcompiler_47 arial cjkfonts d3dx9"
export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
