#!/usr/bin/env bash
#Author: linux-gaming.ru
#eve.exe
#evelauncher.exe
#eve-online.exe
#Rating=5
#####################examples###########################
export PW_WINDOWS_VER="10"
export PW_WINE_USE="WINE_LG"
export PW_USE_WINE_DXGI="1"
export PW_VULKAN_USE="1"
export PW_USE_GSTREAMER="0"
export PW_PREFIX_NAME="EVE_ONLINE"
export PW_WINE_FULLSCREEN_FSR="0"
export PW_USE_D3D_EXTRAS="1"
export PW_FORCE_LARGE_ADDRESS_AWARE="0"
export PW_USE_SHADER_CACHE="0"
export PW_USE_EAC_AND_BE="1"
export PW_DLL_INSTALL="vcrun2022 d3dcompiler_47 tahoma arial" # msdelta
export WINEDLLOVERRIDES="msvcp140,msvcp140_1=n"
