#!/usr/bin/env bash
#Author: linux-gaming.ru
#eve.exe
#evelauncher.exe
#Rating=5
#####################examples###########################
export PW_VULKAN_USE=1
export WINEDLLOVERRIDES="concrt140,msvcp140,msvcp140_1,msvcp140_2,d3dcompiler_47=n"
