#!/usr/bin/env bash
#Author: nixon
#FarCry4.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="d3dcompiler_43 d3dcompiler_47"               # Install DLL in port prefix (used winetricks)
