#!/usr/bin/env bash
#Author: berg
#pemv.exe
#Rating=5
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
export PP_WINDOWS_VER="10"
export PP_DLL_INSTALL=""
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS=""
export PP_WINE_USE="PROTON_GE"
export PP_VULKAN_USE="1"
export PP_USE_DXR10="0"
##export PP_DLSS_ON=1
##export PP_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
export PP_USE_NVAPI_AND_DLSS="0"
export PP_OLD_GL_STRING="0"
export PP_HIDE_NVIDIA_GPU="0"
export PP_FORCE_USE_VSYNC="0"
export PP_VIRTUAL_DESKTOP="0"
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT="0"
##export PP_VKBASALT_EFFECTS="FakeHDR:cas"        # Use Reshade in others games (dx9-12 to vulkan only)
##export PP_VKBASALT_FFX_CAS="0.75"               # FidelityFX Contrast Adaptive Sharpening (min 0 - max 1)
export PP_NO_FSYNC="0"
export PP_NO_ESYNC="1"
export PP_USE_GSTREAMER="1"
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PP_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
export PP_HEAP_DELAY_FREE="0"
export PP_WINE_ALLOW_XIM="0"
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
export PP_WINEDBG_DISABLE="1"
export PP_USE_TERMINAL="0"
export PP_GUI_DISABLED_CS="0"
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PP_PREFIX_NAME="DEFAULT"
export PP_USE_DXR11="0"
export PP_WINE_FULLSCREEN_FSR="0"
export PP_USE_GAMEMODE="1"
export PP_DX12_DISABLE="0"
export PP_PRIME_RENDER_OFFLOAD="0"
export PP_USE_D3D_EXTRAS="1"
export PP_FIX_VIDEO_IN_GAME="0"
export PP_USE_AMDVLK_DRIVER="0"
export PP_FORCE_LARGE_ADDRESS_AWARE="1"
export PP_USE_SHADER_CACHE="1"
