#!/bin/bash
#Author: garrett
#ForzaHorizon4.exe 
#Rating=5
################################################
export PW_DLL_INSTALL="dotnet472 vcrun2019" 
export PW_VULKAN_USE=vkd3d
export WINEPREFIX="${PORT_WINE_PATH}/data/pfx_dotnet"
