#!/usr/bin/env bash
#Author: 
#Frozen Throne.exe 
#Rating=4 - no video
################################################
export PW_VULKAN_USE=0
export LAUNCH_PARAMETERS=""
export PW_GUI_DISABLED_CS=1
if [ -d "${PATH_TO_GAME}"/Movies ] ; then
    mv "${PATH_TO_GAME}"/Movies "${PATH_TO_GAME}"/Movies_bak
fi
