#!/usr/bin/env bash
#Author: xuser
#GameLauncher.exe
#Rating=1-5
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
##export PP_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PP_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
export PP_WINE_USE=PROTON_GE_6.19-5
export PP_VULKAN_USE=1
##export PP_USE_DXR10=1
##export PP_DLSS_ON=1
##export PP_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
##export PP_USE_NVAPI_AND_DLSS=0
##export PP_OLD_GL_STRING=1
##export PP_HIDE_NVIDIA_GPU=1
##export PP_FORCE_USE_VSYNC=0                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PP_VIRTUAL_DESKTOP=1
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT=1
export PP_VKBASALT_EFFECTS=cas:FilmGrain2:Curves
export PP_VKBASALT_FFX_CAS=1
##export PP_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PP_NO_ESYNC=0                            # Do not use eventfd-based in-process synchronization primitives
##export PP_USE_GSTREAMER=1                       # 0 - disabled use winegstreamer 
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PP_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PP_HEAP_DELAY_FREE=1
##export PP_WINE_ALLOW_XIM=1                      # Disable XIM support until libx11 >= 1.7 is widespread
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
##export PP_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PP_USE_TERMINAL=1                        # Force run in terminal
##export PP_GUI_DISABLED_CS=1                     # 1 = disabled GUI
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
