#!/usr/bin/env bash
#Author: fidel
#Genshin Impact.exe
#Rating=1-5
#####################examples###########################
export PW_WINDOWS_VER="10"
export PW_VULKAN_USE="2"
export PW_PREFIX_NAME="GENSHIN_IMPACT"
export PW_FORCE_LARGE_ADDRESS_AWARE="0"
export PW_USE_EAC_AND_BE="0"
