#!/usr/bin/env bash
#Author: xuser
#gfclient.exe
#Rating=1-5
#####################examples###########################
export PP_COMMENT_DB="GameForge\nClient"
export PP_VULKAN_USE=dxvk
export PP_WINE_USE=PROTON_GE
export PP_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
export PP_DLL_INSTALL="vcrun2019 d3dcompiler_43 d3dcompiler_47"               # Install DDL in port prefix (used winetricks) 
export WINEDLLOVERRIDES="gfclient0_msvc140=n;ucrtbase=b"
########################################################
#add_in_start_portwine () {
#
#while true; do
#    if  [ -z "`pgrep GameforgeClient`" ]; then 
#        sleep 1
#    else
#        while [ ! -z "`pgrep GameforgeClient`" ] ; do
#                killall -s KILL gfservice.exe
#        done
#            sleep 1
#            killall -s KILL gfclient.exe
#            break & exit 0
#    fi
#done &
#}
