#!/usr/bin/env bash
    #Author: Ridbowt
    #Sources: lutris.net/games/gothic-ii-gold-edition/
    #GothicStarter.exe
    #Gothic2.exe
    #Rating=1-5
    ################################################
    export PW_VULKAN_USE=0
#####################examples###########################
export WINEDLLOVERRIDES="dsound=b"
export PW_DLL_INSTALL="directmusic"        # Install DDL in port prefix (used winetricks) 
export PW_WINDOWS_VER=7                      # Set windows version 10, 7 or XP
