#!/usr/bin/env bash
#Author: norz3n
#gta3.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER=XP                        # Set windows version 10, 7 or XP
##export PW_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks) 
export WINEDLLOVERRIDES="d3d8,drvmgt,mss32=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
export PW_WINE_USE=PROTON_GE_7.1-2
export PW_VULKAN_USE=0
export PW_USE_DXR10=0
##export PW_DLSS_ON=1
export PW_VULKAN_NO_ASYNC=0
export PW_USE_NVAPI_AND_DLSS=0
export PW_OLD_GL_STRING=0
export PW_HIDE_NVIDIA_GPU=0
export PW_FORCE_USE_VSYNC=0
export PW_VIRTUAL_DESKTOP=1
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT=0
##export PW_VKBASALT_EFFECTS="FakeHDR:cas"        # Use Reshade in others games (dx9-12 to vulkan only)
##export PW_VKBASALT_FFX_CAS="0.75"               # FidelityFX Contrast Adaptive Sharpening (min 0 - max 1)
export PW_NO_FSYNC=0
export PW_NO_ESYNC=1
export PW_USE_GSTREAMER=1
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
export PW_NO_WRITE_WATCH=0
export PW_HEAP_DELAY_FREE=0
export PW_WINE_ALLOW_XIM=0
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
export PW_WINEDBG_DISABLE=1
export PW_USE_TERMINAL=0
export PW_GUI_DISABLED_CS=0
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PW_MANGOHUD_USER_CONF=0
export PW_USE_DXR11=0
export PW_USE_GAMEMODE=1
export PW_DX12_DISABLE=0
export PW_PRIME_RENDER_OFFLOAD=0
export PW_D3D_EXTRAS_DISABLE=0
