#!/bin/bash
#Author: lemonchic with help from Dezert1r
#GTAIV.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=dxvk
export PW_NO_ESYNC=1   
export PW_NO_FSYNC=1
export LAUNCH_PARAMETERS="-nomemrestrict -norestrictions -percentvidmem 100 -availablevidmem 2048 -novblank" # Change -availablevidmem 2048 if you have less than 2 Gb video memory

##export RADV_DEBUG=nodcc # Enable if you have Big Navi videocard (Radeon RX 60xx)
