#!/usr/bin/env bash
#Author: lemonchic with help from Dezert1r
#GTAIV.exe 
#Rating=1-5
################################################
export PP_VULKAN_USE=dxvk
export PP_NO_ESYNC=1   
export PP_NO_FSYNC=1
##export RADV_DEBUG=nodcc # Enable if you have Big Navi videocard (Radeon RX 60xx)
export LAUNCH_PARAMETERS="('"-nomemrestrict"' '"-norestrictions"' '"-percentvidmem 100"' '"-availablevidmem 2048"' '"-noprecache"' '"-novblank"' '"-heapsize 2097152"')"                # Additional launch options
