#!/usr/bin/env bash
#Author: lemonchic with help from Dezert1r
#GTAIV.exe 
#Rating=1-5
################################################
export LAUNCH_PARAMETERS="-nomemrestrict -norestrictions -percentvidmem 100 -availablevidmem 2048 -noprecache -novblank -heapsize 2097152"                # Additional launch options
