#!/usr/bin/env bash
#Author: nixon
#HITMAN3.exe 
#Rating=1-5
################################################
export PP_VULKAN_USE=vkd3d
export LAUNCH_PARAMETERS=""
export PP_DXGI_FROM_DXVK=1
#export MANGOHUD=1
#export PP_USE_NVAPI_AND_DLSS=0            # for nvidia gpu
