#!/usr/bin/env bash
#Author: nixon
#HITMAN3.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=vkd3d
export LAUNCH_PARAMETERS=""
export PW_DXGI_FROM_DXVK=1
#export MANGOHUD=1
#export PW_USE_NVAPI_AND_DLSS=0            # for nvidia gpu
