#!/usr/bin/env bash
#Author: fidel
#HogwartsLegacy.exe
#Rating=1-5
#####################examples###########################
if [ "${update_loc}" = "RUS" ] ; then
    export PW_COMMENT_DB="Если у вас игра не запускается, то необходимо добавить
clearcpuid=514 в раздел GRUB_CMDLINE_LINUX_DEFAULT 
в файле /etc/default/grub. Для упрощения можно использовать
утилиту Grub Customizer"
fi
export PW_VULKAN_USE="2"

add_in_start_portwine () {
    if [ "${update_loc}" = "RUS" ] ; then
        sed -i "s/Language=english/Language=russian/g" "${PATH_TO_GAME}/Engine/Binaries/ThirdParty/Steamworks/Steamv154/Win64/steam_api64.ini"
    fi
}
