#!/usr/bin/env bash
#Author: fidel
#HogwartsLegacy.exe
#Rating=1-5
#####################examples###########################
if [[ "$LANGUAGE" == "ru" ]] ; then
    export PW_COMMENT_DB="Если у вас игра не запускается, то необходимо добавить
clearcpuid=514 в раздел GRUB_CMDLINE_LINUX_DEFAULT
в файле /etc/default/grub. Для упрощения можно использовать
утилиту Grub Customizer"
fi
if [ "${update_loc}" = "ENG" ] ; then
    export PW_COMMENT_DB="If your game does not start, you need to add
clearcpuid=514 to the GRUB_CMDLINE_LINUX_DEFAULT section
in the /etc/default/grub file. To simplify things, you can use
Grub Customizer utility"
fi
export PW_VULKAN_USE="2"

