#!/usr/bin/env bash
#Author: Nixon
#HorizonZeroDawn.exe
#Rating=?
################################################
export PW_DLL_INSTALL="vcrun2019"
export LAUNCH_PARAMETERS="-EpicPortal"
export PW_USE_SHADER_CACHE="0"
