#!/usr/bin/env bash
#Author: Nixon
#HorizonZeroDawn.exe
#Rating=?
################################################
export PP_VULKAN_USE=vkd3d #dxvk or vkd3d
export WINEDLLOVERRIDES=""
export PP_DLL_INSTALL="vcrun2019"
export LAUNCH_PARAMETERS="-EpicPortal"
