#!/usr/bin/env bash
#Author: fidel
#HorizonForbiddenWest.exe
#Rating=1-5
#####################examples###########################
export PW_WINDOWS_VER="10"
export PW_DLL_INSTALL=""
export WINEDLLOVERRIDES=""
export PW_VULKAN_USE="2"
export PW_USE_GSTREAMER="1"
export PW_USE_D3D_EXTRAS="1"
export PW_FIX_VIDEO_IN_GAME="1"
export PW_USE_SHADER_CACHE="0"
export PW_USE_EAC_AND_BE="0"
export LAUNCH_PARAMETERS="-EpicPortal"
