#!/usr/bin/env bash
#Author: Nixon
#HorizonZeroDawn.exe
#Rating=?
################################################
export PW_VULKAN_USE=vkd3d #dxvk or vkd3d
export WINEDLLOVERRIDES=""
export PW_DLL_INSTALL="vcrun2019"
export LAUNCH_PARAMETERS="-EpicPortal"
