#!/bin/bash
#Author: Сергей 33(46)
#hulk.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=0
export PW_WINDOWS_VER="XP"
export LAUNCH_PARAMETERS="-d3d9"
export PW_WINE_USE=proton_steam
