#!/usr/bin/env bash
#Author: fidel
#Icarus.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="10"
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS="-dx12"
export PW_USE_EAC_AND_BE="0"
