#!/usr/bin/env bash
#Author: fidel
#IGClient.exe
#Rating=1-5
#####################examples###########################
export PW_COMMENT_DB="\nПосле первого подтверждения логина в вашем браузере\nнеобходимо перезапустить игру.\n"
export PW_WINE_USE="PROTON_LG"
export PW_VULKAN_USE="1"
export PW_PREFIX_NAME="IGCLIENT"
export PW_DLL_INSTALL="vcrun2019"
