#!/usr/bin/env bash
#Author: fidel
#IGClient.exe
#Rating=1-5
#####################examples###########################
if [ "${update_loc}" = "RUS" ] ; then
    export PW_COMMENT_DB="\nПосле первого подтверждения логина в вашем браузере\nнеобходимо перезапустить игру.\n"
fi
if [ "${update_loc}" = "ENG" ] ; then
    export PW_COMMENT_DB="After the first login confirmation in your browser, you need to restart the game."
fi

export PW_WINE_USE="PROTON_LG"
export PW_VULKAN_USE="1"
export PW_PREFIX_NAME="IGCLIENT"
export PW_DLL_INSTALL="vcrun2019"
