#!/usr/bin/env bash
#Author: xihnik
#iw4sp.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="vcrun2019 d3dx9"
export PW_NO_FSYNC=1
export PW_VIRTUAL_DESKTOP=1
