#!/usr/bin/env bash
    #Author: xihnik
    #iw4sp.exe 
    #Rating=1-5
    ################################################
    export PP_VULKAN_USE=dxvk
    export PP_DLL_INSTALL="vcrun2019 d3dx9"
    export PP_NO_FSYNC=1
    #export PP_FORCE_USE_VSYNC=0
    #export PP_WINDOWS_VER=7
    export PP_VIRTUAL_DESKTOP=1
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
##export PP_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PP_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
##export PP_VULKAN_USE=dxvk                       # dxvk, vkd3d or 0 for OpenGL
##export PP_DXVK_VER=1.8.1 
##export PP_VKD3D_VER=2.2
##export PP_USE_DXR10=1
##export PP_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
##export PP_USE_NVAPI_AND_DLSS=0
##export PP_OLD_GL_STRING=0
##export PP_HIDE_NVIDIA_GPU=0
##export PP_FORCE_USE_VSYNC=2                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PP_VKD3D_FEATURE_LEVEL=0
##export PP_DXGI_FROM_DXVK=0
##export PP_VIRTUAL_DESKTOP=1
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
##export PP_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PP_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PP_USE_GAMEMODE=0              # Force disabele gamemod
##export PP_FORCE_LARGE_ADDRESS_AWARE=1           # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
##export PP_NO_WRITE_WATCH=0                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PP_HEAP_DELAY_FREE=0
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
##export PP_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PP_USE_TERMINAL=0                        # Force run in terminal
##export PP_LOG=0                                 # Enable debug mode fo terminal 
##export PP_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
##add_in_start_portwine () { commands ; }
