#!/usr/bin/env bash
#Author: CyberHippy
#Konung3.exe
#Rating=1-5
#####################examples###########################
export PW_VULKAN_USE="0"
export PW_OLD_GL_STRING="0"
export PW_VIRTUAL_DESKTOP="1"
export PW_NO_FSYNC="0"
export PW_NO_ESYNC="1"

