#!/usr/bin/env bash
#Author: Veil
#LifeIsStrange.exe 
#Rating=1-5
################################################
export PP_VULKAN_USE=dxvk
export WINEDLLOVERRIDES="xapofx1_5,xaudio2_7=n,b"
export PP_DLL_INSTALL=faudio
