#!/bin/bash
#Author: UserDiscord
#NewRP.exe
#Rating=5
#####################examples###########################
export ENABLE_VKBASALT=1
export PW_VKBASALT_EFFECTS=cas:Curves:SMAA:LumaSharpen
export PW_VKBASALT_FFX_CAS=1
export PW_NO_FSYNC=0
export PW_NO_ESYNC=0
export PW_USE_GSTREAMER=0
