#!/bin/bash
#Author: UserDiscord
#NewRP.exe
#Rating=5
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
##export PP_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PP_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
export PP_WINE_USE=PROTON_GE
export PP_VULKAN_USE=1
export PP_USE_DXR10=0
##export PP_DLSS_ON=1
export PP_VULKAN_NO_ASYNC=0
export PP_USE_NVAPI_AND_DLSS=0
export PP_OLD_GL_STRING=0
export PP_HIDE_NVIDIA_GPU=0
export PP_FORCE_USE_VSYNC=0
export PP_VIRTUAL_DESKTOP=0
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT=1
export PP_VKBASALT_EFFECTS=cas:Curves:SMAA:LumaSharpen
export PP_VKBASALT_FFX_CAS=1
export PP_NO_FSYNC=0
export PP_NO_ESYNC=0
export PP_USE_GSTREAMER=0
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
export PP_NO_WRITE_WATCH=0
export PP_HEAP_DELAY_FREE=0
export PP_WINE_ALLOW_XIM=0
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
export PP_WINEDBG_DISABLE=1
export PP_USE_TERMINAL=0
export PP_GUI_DISABLED_CS=0
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PP_USE_DXR11=0
export PP_USE_GAMEMODE=1
export PP_DX12_DISABLE=1
export PP_USE_WINE_DXGI=0
export PP_PRIME_RENDER_OFFLOAD=0
