#!/usr/bin/env bash
#Author: Aliway
#Little Nightmares II.exe
#Rating=5
################################################

export PW_VULKAN_USE=dxvk 
export LAUNCH_PARAMETERS=""
export PW_WINDOWS_VER=10 
