#!/usr/bin/env bash
#Author: Aliway
#Little Nightmares II.exe
#Rating=5
################################################

export PP_VULKAN_USE=dxvk 
export LAUNCH_PARAMETERS=""
export PP_WINDOWS_VER=10 
