#!/usr/bin/env bash
#Author: mrm0der
#LOF2.exe 
#Rating=1-5
#####################examples###########################
export PW_REDUCE_PULSE_LATENCY=1                    # Fix crackling audio in games
