#!/usr/bin/env bash
    #Author: xuser
    #LostEmber-Win64-Shipping.exe 
    #Rating=1-5
    ################################################
    export PW_VULKAN_USE=vkd3d
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
##export PW_VULKAN_USE=dxvk                       # dxvk, vkd3d or 0 for OpenGL
##export WINEDLLOVERRIDES="blabla=n,b"
##export PW_DLL_INSTALL="vcrun2019 "        # Install DDL in port prefix (used winetricks) 
##export PW_LOG=0                                 # Enable debug mode fo terminal 
##export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PW_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
##export PW_VULKAN_NO_ASYNC=1                       # Disabled ASYNC for VULKAN
##export PW_USE_TERMINAL=0                        # Force run in terminal
##export PW_OLD_GL_STRING=0
export PW_USE_NVAPI_AND_DLSS=0
##export PW_VKD3D_FEATURE_LEVEL=0
##export PW_NO_WRITE_WATCH=0                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PW_HIDE_NVIDIA_GPU=0
##export PW_FORCE_USE_VSYNC=2                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PW_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PW_USE_GAMEMODE=0              # Force disabele gamemod
##export PW_FORCE_LARGE_ADDRESS_AWARE=1           # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
##export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue,dxr
##export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PW_VIRTUAL_DESKTOP=1
##export DXVK_HUD=fps,devinfo
export PW_HEAP_DELAY_FREE=1
##export PW_DXGI_FROM_DXVK=1
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
##add_in_start_portwine () { commands ; }
