#!/usr/bin/env bash
#Author: xuser
#MassEffect.exe
#MassEffectConfig.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="physx d3dx9"                  # Install DDL in port prefix (used winetricks) 
