#!/usr/bin/env bash
#Author: xuser
#MassEffectLauncher.exe
#Rating=1-5
#####################examples###########################
export ENABLE_VKBASALT=1
export PW_VKBASALT_EFFECTS=cas:FilmGrain2:Clarity
export PW_VKBASALT_FFX_CAS=0.75
