#!/usr/bin/env bash
#Author: xuser
#MassEffectLauncher.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
##export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PW_DLL_INSTALL="vcrun2017"               # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
export PW_WINE_USE=PROTON_GE
export PW_VULKAN_USE=1
export PW_DXR_ON=0
##export PW_DLSS_ON=1
export PW_VULKAN_NO_ASYNC=0
export PW_USE_NVAPI_AND_DLSS=0
export PW_OLD_GL_STRING=0
export PW_HIDE_NVIDIA_GPU=0
export PW_FORCE_USE_VSYNC=0
export PW_VIRTUAL_DESKTOP=0
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT=1
export PW_VKBASALT_EFFECTS=cas:FilmGrain2:Clarity
export PW_VKBASALT_FFX_CAS=0.75
export PW_NO_FSYNC=0
export PW_NO_ESYNC=1
export PW_USE_GSTREAMER=1
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
export PW_NO_WRITE_WATCH=0
export PW_HEAP_DELAY_FREE=0
export PW_WINE_ALLOW_XIM=0
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
export PW_WINEDBG_DISABLE=1
export PW_USE_TERMINAL=0
export PW_GUI_DISABLED_CS=0
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PW_MANGOHUD=1
export PW_USE_RUNTIME=1
export PW_USE_GAMEMODE=1
export MANGOHUD_CONFIG=font_size=24,position=top-left,toggle_hud=Shift_R+F12,no_display,resolution,wine,gpu_name,vulkan_driver,gpu_stats,vkbasalt,fps_limit=0 
