#!/usr/bin/env bash
#Author: 
#MetroExodus.exe 
#Rating=?
################################################
export PW_VULKAN_USE=vkd3d
export LAUNCH_PARAMETERS=""
export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
