#!/usr/bin/env bash
#Author: ValoKarDin
#modern_warships_pp.exe
#Rating=5
export PW_COMMENT_DB="Modern Warships"
################################################
export PW_VULKAN_USE=2                       #dxvk, vkd3d or 0 for OpenGL
export PW_DLL_INSTALL="lucida"     # Install DLL in port prefix (used winetricks)
export PW_USE_D3D_EXTRAS="1"
export PW_USE_EAC_AND_BE="0"
export PW_PREFIX_NAME="MODERN_WARSHIPS"
export PW_USE_SHADER_CACHE="1"
