#!/usr/bin/env bash
#Author: fidel
#MWOLauncher.exe
#MWO.exe
#Rating=1-5
#####################examples###########################
export PW_COMMENT_DB="\nНа данный момент игра работает, но долго запускаеться из Лаунчера.\nПосле установки игры, при повторном запуске, игра будет запускаться быстро.\n"
export PW_WINDOWS_VER="10"
export PW_DLL_INSTALL=""
export WINEDLLOVERRIDES="steam_api,steam_api64,steamclient,steamclient64=n;dotnetfx35.exe,dotnetfx35setup.exe,winemenubuilder="
export LAUNCH_PARAMETERS=""
export PW_WINE_USE="PROTON_LG"
export PW_VULKAN_USE="1"
export PW_HIDE_NVIDIA_GPU="0"
export PW_VIRTUAL_DESKTOP="0"
export ENABLE_VKBASALT="0"
export PW_NO_FSYNC="0"
export PW_NO_ESYNC="1"
export PW_USE_GSTREAMER="1"
export PW_USE_TERMINAL="0"
export PW_GUI_DISABLED_CS="0"
export PW_PREFIX_NAME="METAL_WAR_ONLINE"
export PW_MANGOHUD="1"
export PW_MANGOHUD_x32="1"
export PW_MANGOHUD_USER_CONF="0"
export PW_WINE_FULLSCREEN_FSR="1"
export PW_USE_GAMEMODE="1"
export PW_DX12_DISABLE="0"
export ="0"
export PW_USE_D3D_EXTRAS="1"
export PW_FIX_VIDEO_IN_GAME="1"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_USE_SHADER_CACHE="1"
export PW_USE_WINE_DXGI="0"
export PW_USE_EAC_AND_BE="1"
add_in_start_portwine ()
{
    if [[ -f "${PATH_TO_GAME}/MWO.exe" ]] ; then
        echo "Override $portwine_exe to ${PATH_TO_GAME}/MWO.exe"
        export portwine_exe="${PATH_TO_GAME}/MWO.exe"
    fi
}
