#!/usr/bin/env bash
#Author: fidel
#MWOLauncher.exe
#MWO.exe
#Rating=1-5
#####################examples###########################
export PW_COMMENT_DB="\nНа данный момент игра работает, но долго запускаеться из Лаунчера.\nПосле установки игры, при повторном запуске, игра будет запускаться быстро.\n"

add_in_start_portwine ()
{
    if [[ -f "${PATH_TO_GAME}/MWO.exe" ]] ; then
        echo "Override $portwine_exe to ${PATH_TO_GAME}/MWO.exe"
        export portwine_exe="${PATH_TO_GAME}/MWO.exe"
    fi
}
