#!/usr/bin/env bash
#Author: PortWINE
#Origin.exe 
#Rating=5
#####################examples###########################
export PW_DLL_INSTALL="vcrun2012 vcrun2019"               # Install DDL in port prefix (used winetricks) 
export PW_VULKAN_USE=1                       # dxvk, vkd3d or 0 for OpenGL
export PW_USE_TERMINAL="1"
