#!/bin/bash
#Author: PortWINE
#Origin.exe 
#Rating=
################################################
export PW_VULKAN_USE=vkd3d
export LAUNCH_PARAMETERS=""
sed -i 's%key="EnableIgo" value="true"%key="EnableIgo" value="false"%g' "${WINEPREFIX}/drive_c/users/steamuser/Application Data/Origin/local_"*".xml"
