#!/usr/bin/env bash
#Author: castro-fidel
#PnzSteamLauncher.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="7"
export ENABLE_VKBASALT="1"
export PW_VKBASALT_EFFECTS="Curves:cas"
export PW_VKBASALT_FFX_CAS="0.75"

