#!/usr/bin/env bash
#Author: castro-fidel
#PathOfExile.exe
#PathOfExile_x64.exe
#Rating=1-5
#####################examples###########################
# export WINEDLLOVERRIDES="mscoree,mshtml="
export LAUNCH_PARAMETERS="--nologo --noasync --nopreload -gc 2"
export PW_VULKAN_USE=1
export PW_MUST_HAVE_DLL=""
# export PW_DLL_INSTALL="riched20 usp10"
export PW_PREFIX_NAME="PATH_OF_EXILE"
export PW_NO_FSYNC=0
export PW_NO_ESYNC=1
# export PW_DISABLED_CREATE_DB=1
export PW_USE_D3D_EXTRAS=1
#export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI
export PW_WINDOWS_VER=7

add_in_start_portwine () {
    echo ""
}
