#!/usr/bin/env bash
#Author: nixon
#Photoshop.exe
#Rating=1-5
########################################################
export PP_WINDOWS_VER=10   
export PP_VIRTUAL_DESKTOP=1
export PP_DLL_INSTALL="atmlib corefonts gdiplus msxml3 msxml6 vcrun2012 vcrun2013 vcrun2019" 
#####################examples###########################
##export PP_COMMENT_DB="blablabla"
##export PP_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
#export LAUNCH_PARAMETERS="" 
##export PP_DLL_INSTALL="gdiplus msxml3 msxml6 atmlib corefonts  vcrun2010 vcrun2012 vcrun2013 vcrun2019"               # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export PP_VULKAN_USE=dxvk                       # dxvk, vkd3d or 0 for OpenGL
##export PP_DXR_ON=1
##export PP_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
##export PP_NVAPI_DISABLE=1
##export PP_OLD_GL_STRING=1
##export PP_HIDE_NVIDIA_GPU=1
##export PP_FORCE_USE_VSYNC=0                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PP_VIRTUAL_DESKTOP=1
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
##export ENABLE_VKBASALT=1
##export PP_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PP_NO_ESYNC=1                            # Do not use eventfd-based in-process synchronization primitives
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PP_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PP_HEAP_DELAY_FREE=1
##export PP_WINE_ALLOW_XIM=1                      # Disable XIM support until libx11 >= 1.7 is widespread
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
##export PP_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PP_USE_TERMINAL=1                        # Force run in terminal
##export PP_GUI_DISABLED_CS=1                     # 1 = disabled GUI 
#ADD_IN_START_PORTWINE () { commands ; }
