#!/usr/bin/env bash
#Author: castro-fidel
#PlariumPlay.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="10"
export PW_VULKAN_USE="1"
export PW_PREFIX_NAME="DOTNET"

