#!/usr/bin/env bash
#Author: fidel
#PulseOnlineLauncher.exe
#Rating=5
#####################examples###########################
export PW_VULKAN_USE="2"
export PW_WINE_USE="PROTON_LG"
export PW_PREFIX_NAME="DOTNET"
