#!/usr/bin/env bash
#Author:
#RDR2.exe
#PlayRDR2.exe
#Rating=?
################################################
export PW_VULKAN_USE=1
export WINEDLLOVERRIDES="vulkan-1=n,b"
export PW_DXGI_FROM_DXVK=1
export LAUNCH_PARAMETERS=("-fullscreen" "-vulkan" "-adapter=1" "-USEALLAVAILABLECORES" "-cpuLoadRebalancing" "-ignorepipelinecach")
export PULSE_LATENCY_MSEC=60
#export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json"
