#!/bin/bash
#Author: 
#RDR2.exe
#PlayRDR2.exe 
#Rating=?
################################################
export PW_VULKAN_USE=vkd3d
export WINEDLLOVERRIDES="amd_ags_x64=b,n"
export PW_DXGI_FROM_DXVK=1
export LAUNCH_PARAMETERS="-adapter=1 -vulkan -width=1920 -height=1080 -USEALLAVAILABLECORES -cpuLoadRebalancing -ignorepipelinecach"
export PULSE_LATENCY_MSEC=60
#export VK_ICD_FILENAMES="/usr/share/vulkan/icd.d/radeon_icd.i686.json:/usr/share/vulkan/icd.d/radeon_icd.x86_64.json"
#?PID=$(pgrep RDR2.exe); kill -s SIGSTOP $PID; kill -s SIGCONT $PID
