#!/usr/bin/env bash
#Author: PortWINE
#Revival.exe 
#Rating=5
################################################
export LAUNCH_PARAMETERS=""
export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
