#!/usr/bin/env bash
#Author: fidel
#RobloxPlayerBeta.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINE_USE="WINE-8.8-STAGING-TKG-AMD64"
export PW_VULKAN_USE="1"
export PW_PREFIX_NAME="ROBLOX"
# export DISABLE_CP_DEFPFX=1
