#!/bin/bash
#Author: Garrett
#RockstarService.exe
#Launcher.exe
#LauncherPatcher.exe
#Rating=?
################################################
export PW_VULKAN_USE=dxvk
export PW_DLL_INSTALL="arial vcrun2019"
export PW_WINDOWS_VER=10