#!/usr/bin/env bash
#Author: linux-gaming.ru
#setup.exe
#Setup.exe
#SETUP.exe
#.msi
#Rating=5
#export PP_COMMENT_DB="blablabla"
################################################
export PP_DISABLED_CREATE_DB=1
export PP_ICON_FOR_YAD="${PORT_WINE_PATH}/data/img/setup.png" 
export PP_VULKAN_USE=0 #dxvk or vkd3d
export PP_MANGOHUD=0
#export PP_WINE_USE=PROTON_LG
#export WINEDLLOVERRIDES="blabla=n,b"
#export PP_LOG=0             # Enable debug mode fo terminal
export PP_NO_FSYNC=1        # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PP_NO_ESYNC=1        # Do not use eventfd-based in-process synchronization primitives
#export PP_VULKAN_NO_ASYNC=1
#export PP_USE_TERMINAL=0
#export PP_OLD_GL_STRING=0
#export PP_USE_NVAPI_AND_DLSS=0
#export PP_VKD3D_FEATURE_LEVEL=0
export PP_NO_WRITE_WATCH=0          # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
#export PP_HIDE_NVIDIA_GPU=0
#export PP_FORCE_USE_VSYNC=2         # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
export PP_WINEDBG_DISABLE=1
export PP_USE_GAMEMODE=0             # Force disabele gamemod
#export PP_FORCE_LARGE_ADDRESS_AWARE=0          # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
#export PULSE_LATENCY_MSEC=60
export PP_DLL_INSTALL="mfc42 vcrun6sp6 vcrun2012 mfc120 mfc140 vcrun2013"
#export LAUNCH_PARAMETERS="-d3d9"
#export PP_WINDOWS_VER=XP                      # Set windows version 10, 7 or XP
