#!/usr/bin/env bash
#Author: Cefeiko
#SimCity.exe
#Rating=1-5
########################################################
export PW_COMMENT_DB="SimCity 5"
export PW_DLL_INSTALL="vcrun2012 vcrun2019 d3dcompiler_43 d3dcompiler_47 d3dx9"               # Install DDL in port prefix (used winetricks) 
export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PW_NO_ESYNC=1
##export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
