#!/usr/bin/env bash
#Author: kbp95
#SkyrimSE.exe
#Rating=1-5
########################################################
export PW_REDUCE_PULSE_LATENCY=1                    # Fix crackling audio in games
export WINEDLLOVERRIDES="xaudio2_7=n,b"
