#!/usr/bin/env bash
#Author: kbp95
#SkyrimSE.exe
#Rating=1-5
########################################################
export PW_VULKAN_USE=dxvk
export PULSE_LATENCY_MSEC=90
export WINEDLLOVERRIDES="xaudio2_7=n,b"
