#!/usr/bin/env bash
#Author: 
#SpideyPC.exe 
#Rating=5
################################################
export PP_VULKAN_USE=0
export PP_WINDOWS_VER="XP"
export PP_USE_GAMEMODE=1
export LAUNCH_PARAMETERS="-d3d9"
