#!/usr/bin/env bash
#Author: spider
#sprally2.exe
#Rating=1-5
#####################examples###########################
export PW_WINE_USE=proton_steam
export PW_VULKAN_USE=0
export PW_OLD_GL_STRING=1
