#!/usr/bin/env bash
#Author: xuser
#SR2_pc.exe
#Rating=1-5
#####################examples###########################
export PW_DLL_INSTALL="faudio"               # Install DDL in port prefix (used winetricks) 

