#!/usr/bin/env bash
#Author: linux-gaming.ru
#steam.exe
#Rating=5
################################################
export PW_COMMENT_DB="Steam"
export PW_WINDOWS_VER="10"
export PW_DLL_INSTALL="vcrun2022 d3dcompiler_46"
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS="-gamepadui -fullscreen -no-dwrite"
export PW_VULKAN_USE="1"

add_in_start_portwine () {
    echo "Disabled silent autostart steam."
    if [[ -f "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg" ]] ; then
        sed -i '/steam.exe\\" -silent"/d' "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg"
    fi
}
