#!/bin/bash
#Author: Cefeiko
#steam.exe
#Rating=5
################################################
export PW_COMMENT_DB="Steam"
export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
export PW_DLL_INSTALL="vcrun2019 d3dcompiler_46"
export WINEDLLOVERRIDES="libglesv2,lsteamclient="
export LAUNCH_PARAMETERS="-no-cef-sandbox"
export PW_VULKAN_USE=1
export PW_WINE_USE=PROTON_GE
