#!/usr/bin/env bash
#Author: fidel
#Ученик.exe
#Rating=1-5
export PW_VULKAN_USE="0"
export PW_WINE_USE="PROTON_LG"
export PW_PREFIX_NAME="STUDENT"
export PW_DISABLED_CREATE_DB="1"
export WINEDLLOVERRIDES="mscoree,mshtml="
export PW_GUI_DISABLED_CS="1"
export PW_MANGOHUD="0"
export PW_NO_FSYNC="1"
export PW_NO_ESYNC="1"
export PW_USE_GAMEMODE="0"
export DISABLE_CP_DEFPFX="1"
