#!/usr/bin/env bash
#Author: licrit
#SystemShock.exe
#SystemReShock-Win64-Shipping.exe
#Rating=1-5
#####################examples###########################
export PW_WINE_USE="WINE_8.5_LG"
export PW_PREFIX_NAME="SystemShock"
gui_proton_downloader silent "WINE_8.5_LG"
