#!/usr/bin/env bash
#Author: xuser
#Torchlight.exe
#Rating=1-5
########################################################
export PW_WINE_USE=PROTON_GE
export PW_VULKAN_USE=1
export ENABLE_VKBASALT=1
export PW_VKBASALT_EFFECTS="FakeHDR:cas:FilmGrain2"       
export PW_VKBASALT_FFX_CAS="1"
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
##export PW_WINDOWS_VER=10                        # Set windows version 10, 7 or XP
##export PW_DLL_INSTALL=""                        # Install DDL in port prefix (used winetricks) 
##export WINEDLLOVERRIDES="blabla=n,b"
##export LAUNCH_PARAMETERS="('"+com_skipIntroVideo 1"' '"+com_skipSignInManager 1"')"                # Additional launch options
##export PW_WINE_USE=PROTON_GE                    # PROTON_LG or PROTON_GE
##export PW_VULKAN_USE=vkd3d                      # dxvk, vkd3d or 0 for OpenGL
##export PW_USE_DXR10=1
##export PW_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
##export PW_USE_NVAPI_AND_DLSS=0
##export PW_OLD_GL_STRING=1
##export PW_HIDE_NVIDIA_GPU=1
##export PW_FORCE_USE_VSYNC=0                     # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
##export PW_VIRTUAL_DESKTOP=1
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
##export ENABLE_VKBASALT=1
##export PW_NO_FSYNC=1                            # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
##export PW_NO_ESYNC=0                            # Do not use eventfd-based in-process synchronization primitives
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PW_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
##export PW_HEAP_DELAY_FREE=1
##export PW_WINE_ALLOW_XIM=1                      # Disable XIM support until libx11 >= 1.7 is widespread
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
##export PW_WINEDBG_DISABLE=1                     # Disabled WINEDBG
##export PW_USE_TERMINAL=1                        # Force run in terminal
##export PW_GUI_DISABLED_CS=1                     # 1 = disabled GUI
##add_in_start_portwine () { commands ; }
