#!/bin/bash
#Author: user
#VampireLife.2.exe
#Rating=1-5
#########################################################
export PP_COMMENT_DB="VampireLife 2"
#export PP_DLL_INSTALL="vcrun2019 physx"
#####################examples###########################
export PP_VULKAN_USE="1"
export PP_WINE_USE="PROTON_GE_7-9"
export PP_PREFIX_NAME="DEFAULT"
export PP_DISABLED_CREATE_DB=1
