#!/bin/bash
#Author: user
#VampireLife.2.exe
#Rating=1-5
#########################################################
export PW_COMMENT_DB="VampireLife 2"
#export PW_DLL_INSTALL="vcrun2019 physx"
#####################examples###########################
export PW_VULKAN_USE="1"
export PW_WINE_USE="PROTON_GE_7-9"
export PW_PREFIX_NAME="DEFAULT"
export PW_DISABLED_CREATE_DB=1
