#!/usr/bin/env bash
#Author: castro-fidel
#VKPlayLoader.exe
#Rating=5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="10"
export WINEDLLOVERRIDES="mscoree,mshtml="
export PW_MUST_HAVE_DLL=""
export PW_PREFIX_NAME="VK_PLAY"

add_in_start_portwine () {
    if [[ -f "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg" ]] ; then
        sed -i '/Software\\\\Wine\\\\Explorer/d' "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg"
    fi
}
