#!/usr/bin/env bash
#Author: castro-fidel
#VKPlayLoader.exe
#Rating=5
#####################examples###########################
if [[ "${update_loc}" == "RUS" ]] ; then
    export PW_COMMENT_DB="Если вы используете Wayland, для перехвата управления в Atomic Heart\nнеобходимо свернуть в трей сам VK Play Игровой центр"
else
    export PW_COMMENT_DB="If you use Wayland, to intercept control in Atomic Heart\n,you need to collapse the VK Play Game Center itself into the tray"
fi
export PW_WINDOWS_VER="10"
export WINEDLLOVERRIDES=""
export PW_MUST_HAVE_DLL=""
export PW_PREFIX_NAME="VK_PLAY"
export PW_USE_GSTREAMER="0"

add_in_start_portwine () {
    if [[ -f "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg" ]] ; then
        sed -i '/Software\\\\Wine\\\\Explorer/d' "${PORT_WINE_PATH}/data/prefixes/${PW_PREFIX_NAME}/user.reg"
    fi
}
