#!/usr/bin/env bash
# Author: chal55rus and Boria138
#W3D Hub Launcher.exe
#Rating=1-5
export PW_VULKAN_USE="0"
export PW_PREFIX_NAME="DOTNET"
export PW_WINE_USE="WINE_LG"

gui_proton_downloader silent "$PW_WINE_USE"
