#!/usr/bin/env bash
#Author: fidel
#warframe_launcher_pp.exe
#Rating=1-5
#####################examples###########################
export PW_WINDOWS_VER="10"
export PW_VULKAN_USE="2"
export PW_PREFIX_NAME="DEFAULT"
export PW_USE_RAY_TRACING="0"
export PW_USE_NVAPI_AND_DLSS="0"
export PW_USE_D3D_EXTRAS="1"
export PW_FORCE_LARGE_ADDRESS_AWARE="0"
export PW_USE_EAC_AND_BE="0"
