#!/bin/bash
#Author: PortWINE
#wgc.exe 
#Rating=5
################################################
export PW_VULKAN_USE=dxvk                       #dxvk, vkd3d or 0 for OpenGL
#export PW_DLL_INSTALL=""     # Install DDL in port prefix (used winetricks) 
export LAUNCH_PARAMETERS="--disable-gpu"            # Additional launch options
