#!/bin/bash
#Author: PortWINE
#wgc.exe 
#Rating=5
################################################
export PW_VULKAN_USE=dxvk                       #dxvk, vkd3d or 0 for OpenGL
export LAUNCH_PARAMETERS="--disable-gpu"            # Additional launch options
export PW_USE_TERMINAL=1
export PW_WINDOWS_VER=7                        # Set windows version 10, 7 or XP
export PW_NVAPI_DISABLE=1
export WINEDLLOVERRIDES="ucrtbase=b,n"
##export PW_GUI_DISABLED_CS=1

ADD_IN_START_PORTWINE () { 
    sed -i 's/true/false/g' "$WINEPREFIX/drive_c/ProgramData/Wargaming.net/GameCenter/preferences.xml"
}
  