#!/bin/bash
#Author: PortWINE
#wgc.exe 
#Rating=5
################################################
export PW_VULKAN_USE=dxvk                       #dxvk, vkd3d or 0 for OpenGL
#export PW_DLL_INSTALL=""     # Install DDL in port prefix (used winetricks) 
export LAUNCH_PARAMETERS="--disable-gpu"            # Additional launch options
export PW_USE_TERMINAL=1
ADD_IN_START_PORTWINE () { 
    sed -i 's/true/false/g' "${PORT_WINE_PATH}/data/pfx/drive_c/Games/WGC/preferences.xml"
}