#!/usr/bin/env bash
#Author: xuser
#witcher3.exe
#Rating=1-5
#####################examples###########################
export PW_VULKAN_USE="2"
export PW_USE_D3D_EXTRAS="1"
export PW_USE_WINE_DXGI="1"
