#!/usr/bin/env bash
#Author: spider
#WolfNewOrder_x64.exe
#Rating=1-5
#####################examples###########################
##export PW_COMMENT_DB="blablabla"
export PW_WINDOWS_VER="10"
export PW_DLL_INSTALL=""
export WINEDLLOVERRIDES=""
export LAUNCH_PARAMETERS=""
export PW_WINE_USE="PROTON_GE"
export PW_VULKAN_USE="1"
export PW_USE_DXR10="0"
##export PW_DLSS_ON=1
##export PW_VULKAN_NO_ASYNC=1                     # Disabled ASYNC for VULKAN
export PW_USE_NVAPI_AND_DLSS="0"
export PW_OLD_GL_STRING="0"
export PW_HIDE_NVIDIA_GPU="0"
export PW_FORCE_USE_VSYNC="0"
export PW_VIRTUAL_DESKTOP="0"
##export VKD3D_CONFIG=force_bindless_texel_buffer,multi_queue
export ENABLE_VKBASALT="0"
export PW_VKBASALT_EFFECTS="Curves:SMAA:cas"
export PW_VKBASALT_FFX_CAS="0.75"
export PW_NO_FSYNC="0"
export PW_NO_ESYNC="1"
export PW_USE_GSTREAMER="1"
##export PULSE_LATENCY_MSEC=60                    # Fix crackling audio in games
##export PW_NO_WRITE_WATCH=1                      # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
export PW_HEAP_DELAY_FREE="0"
export PW_WINE_ALLOW_XIM="0"
##export WINEARCH=win32                           # defaut = win64
##export WINEPREFIX=
export PW_WINEDBG_DISABLE="1"
export PW_USE_TERMINAL="0"
export PW_GUI_DISABLED_CS="0"
##export PATH_TO_GAME=
##add_in_start_portwine () { commands ; }
export PW_PREFIX_NAME="DEFAULT"
export PW_MANGOHUD="1"
export PW_MANGOHUD_USER_CONF="0"
export PW_USE_DXR11="0"
export PW_WINE_FULLSCREEN_FSR="0"
export PW_USE_GAMEMODE="1"
export PW_DX12_DISABLE="0"
export PW_PRIME_RENDER_OFFLOAD="0"
export PW_USE_D3D_EXTRAS="0"
export PW_FIX_VIDEO_IN_GAME="0"
export PW_USE_AMDVLK_DRIVER="0"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_USE_SHADER_CACHE="1"
