#!/bin/bash
#Author: xuser
#WorldOfTanks.exe 
#Rating=5
################################################
export PW_VULKAN_USE=dxvk                       #dxvk, vkd3d or 0 for OpenGL
export PW_DLL_INSTALL="lucida"     # Install DDL in port prefix (used winetricks) 
export WINEDLLOVERRIDES="xaudio2_7="            
