#!/usr/bin/env bash
    #Author: cefeiko
    #WorldOfTanksEnCoreLauncher.exe 
    #Rating=1-5
    ################################################
    export PP_VULKAN_USE=1
    export PP_USE_TERMINAL=0
    export PP_PREFIX_NAME="DOTNET"
    export PP_DLL_INSTALL="mfc42 vb6run physx dotnet40"        # Install DDL in port prefix (used winetricks) 
    export PP_COMMENT_DB="World Of Tanks EnCore"
    export PP_USE_D3D_EXTRAS=0
    ## export DXVK_HUD=fps,devinfo
    ## export PP_MANGOHUD=1
#####################examples###########################
while [ `pidof -s dotNetFx40_Full_x86_x64.exe` ] ; do
    if  [ $? -eq 0 ] ; then
        sleep 1
    elif
        export dotnet_pids=`ps -ax | grep mscorsvw.exe | awk '{print $1}' | uniq`
        [ ! -z $dotnet_pids ]
        kill -n 9 $dotnet_pids
        sleep 1
    fi
done
