#!/usr/bin/env bash
#Author: xuser
#WorldOfTanks.exe
#Rating=5
################################################
export PW_VULKAN_USE=1                       #dxvk, vkd3d or 0 for OpenGL
export PW_DLL_INSTALL="lucida vcrun2019"     # Install DDL in port prefix (used winetricks) 
export WINEDLLOVERRIDES="xaudio2_7="
export PW_WINEDBG_DISABLE=1                     # Disabled WINEDBG
export PW_USE_D3D_EXTRAS=0
