#!/usr/bin/env bash
#Author: xuser
#WorldOfTanks.exe
#Rating=5
################################################
export PP_VULKAN_USE=1                       #dxvk, vkd3d or 0 for OpenGL
export PP_DLL_INSTALL="lucida vcrun2019"     # Install DDL in port prefix (used winetricks) 
export WINEDLLOVERRIDES="xaudio2_7="
export PP_WINEDBG_DISABLE=1                     # Disabled WINEDBG
export PP_USE_D3D_EXTRAS=0
