#!/usr/bin/env bash
#Author: Cefeiko
#wosb_launcher_ru.exe
#Rating=?
################################################
export PW_COMMENT_DB="С этим ДБ файлом писать на АНГЛИЙСКОМ не получится.
Для входа в игру используйте ярлык World of Sea Battle (EN)"
export PW_PREFIX_NAME="DOTNET"
export PW_WINDOWS_VER="10"
export PW_VULKAN_USE="2"
export WINEDLLOVERRIDES="vulkan-1=n,b"
export PW_NO_ESYNC="1"
export PW_USE_D3D_EXTRAS="1"
export PW_USE_GSTREAMER="1"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_USE_SHADER_CACHE="1"
export LAUNCH_PARAMETERS=""
