#!/usr/bin/env bash
#Author: Cefeiko
#wos_client.exe
#WorldOfSeaBattleClient.exe
#Rating=1-5
#####################examples###########################
export PW_PREFIX_NAME="DOTNET"
export PW_DLL_INSTALL="faudio dotnet48 dotnet20sp2 dotnetdesktop7"
export WINEDLLOVERRIDES="quartz=b"
