#!/bin/bash
    #Author: cefeiko
    #WorldOfTanksEnCoreLauncher.exe 
    #Rating=1-5
    ################################################
    export PW_VULKAN_USE=1
    export PW_USE_TERMINAL=0
    export WINEPREFIX="${PORT_WINE_PATH}/data/pfx_dotnet/"
    export PW_DLL_INSTALL="vcrun2017  mfc42 vb6run physx dotnet40 "        # Install DDL in port prefix (used winetricks) 
    export PW_COMMENT_DB="World Of Tanks EnCore"
    ## export DXVK_HUD=fps,devinfo
    ## export PW_MANGOHUD=1
#####################examples###########################
while [ `pidof -s dotNetFx40_Full_x86_x64.exe` ] ; do
    if  [ $? -eq 0 ] ; then
        sleep 1
    elif
        export dotnet_pids=`ps -ax | grep mscorsvw.exe | awk '{print $1}' | uniq`
        [ ! -z $dotnet_pids ]
        kill -n 9 $dotnet_pids
        sleep 1
    fi
done
