#!/usr/bin/env bash
#Author: Cefeiko
#wosb_launcher_en.exe
#Rating=?
################################################
export PW_COMMENT_DB=""
export PW_PREFIX_NAME="DOTNET"
export PW_WINDOWS_VER="10"
export PW_VULKAN_USE="2"
export WINEDLLOVERRIDES="vulkan-1=n,b"
export PW_NO_ESYNC="1"
export PW_USE_D3D_EXTRAS="1"
export PW_USE_GSTREAMER="1"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_USE_SHADER_CACHE="1"
export LAUNCH_PARAMETERS=""
export LANG=en_US.UTF-8
