#!/usr/bin/env bash
#Author: user
#wot_encore_install_ru.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=dxvk
export PW_USE_TERMINAL=1
export PW_PREFIX_NAME="DOTNET"
export PW_DLL_INSTALL="dotnet40 vcrun2017  mfc42 vb6run physx"
export PW_COMMENT_DB="World Of Tanks EnCore Installer"
export PW_USE_D3D_EXTRAS=0
## export DXVK_HUD=fps,devinfo
## export PW_MANGOHUD=1
