#!/bin/bash
#Author: merkli
#XR_3DA.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=0
export LAUNCH_PARAMETERS="-nointro -noprefetch" # -nointro command line option to skip intro movies
                                                # -noprefetch command line option to shorten load times
