#!/usr/bin/env bash
#Author: merkli
#XR_3DA.exe 
#Rating=1-5
################################################
export PW_VULKAN_USE=dxvk
export LAUNCH_PARAMETERS="-nointro -noprefetch" # -nointro command line option to skip intro movies
                                                # -noprefetch command line option to shorten load times
#export PW_DLL_INSTALL="vcrun2019 mfc42 d3dcompiler_42 d3dcompiler_43 d3dcompiler_47 d3dx9
