#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
##########################################################
rm -f "${PORT_WINE_PATH}/data/version"
rm -f "${PORT_WINE_PATH}/data/"*.lock
rm -fr "${PORT_WINE_PATH}/data/__pycache__"
rm -fr "${PORT_WINE_PATH}/data/pfx/dosdevices"
rm -fr "${PORT_WINE_PATH}/data/dive_c/windows/Installer/"*
rm -fr "${PORT_WINE_PATH}/data/dive_c/windows/temp/"*
rm -fr "${PORT_WINE_PATH}/data/dive_c/users/steamuser/Local Settings/Temporary Internet Files/"*
rm -fr "${PORT_WINE_PATH}/data/dive_c/users/steamuser/Temp/"*
