#!/usr/bin/env bash
# Author: chal55rus, Castro-Fidel (linux-gaming.ru)
########################################################################
if [ "${update_loc}" = "RUS" ]
then
    KEY_CREDITS=$RANDOM

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=1 --show-uri \
--image-path="$PW_GUI_ICON_PATH" --image="port_proton" --window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
--text-align=center --scroll --text="PortProton v. ${install_ver}
scripts v. ${scripts_install_ver}

https://linux-gaming.ru

Авторские права © $(date +'%Y') Castro-Fidel (linux-gaming.ru)

Эта программа поставляется без каких-либо гарантий.
Подробнее см. в Лицензия." 2>/dev/null &


"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=2 \
--text-align=center --scroll --text="Автор:   Casro-Fidel (Михаил Тергоев)

Помощники разработчика и тестировщики:
Cefeiko
Dezert1r
Taz_mania
Anton_Famillianov
RidBowt
chal55rus
UserDiscord
Survolog
gavr
RusNor
aldiserg
an9949an
andrey4korop
zorn
Vano Majukin
Сергей 33(46)RUS
WelchDragon
Vuursteen
Boria138
Akai
" 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=3 --text-info --scroll <<< "          Лицензия Массачусетского технологического института (MIT License)

              Авторские права © $(date +'%Y') Castro-Fidel (linux-gaming.ru)

Настоящим предоставляется бесплатное разрешение любому лицу, получившему копию данного
программного обеспечения и связанных с ним файлов документации (Программное
обеспечение), для в Программном обеспечении без ограничений, включая, помимо прочего,
права использовать, копировать, изменять, объединять, публиковать, распространять,
сублицензировать и/или продавать копий Программного обеспечения, а также разрешить
лицам, которым Программное обеспечение предоставляется для этого при соблюдении
следующих условий:

Вышеприведенное уведомление об авторских правах и это уведомление о разрешении должны
быть включены во все копии или существенные части Программного обеспечения.

ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ (КАК ЕСТЬ), БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ, ЯВНЫХ ИЛИ
ПОДРАЗУМЕВАЕТСЯ, ВКЛЮЧАЯ, ПОМИМО ПРОЧЕГО, ГАРАНТИИ КОММЕРЧЕСКОЙ ЦЕННОСТИ,
ПРИГОДНОСТЬ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ И НЕНАРУШЕНИЕ ПРАВ. НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ
АВТОРЫ ИЛИ ВЛАДЕЛЕЦ АВТОРСКИХ ПРАВ НЕСУТ ОТВЕТСТВЕННОСТЬ ЗА ЛЮБЫЕ ПРЕТЕНЗИИ, УЩЕРБ ИЛИ
ДРУГОЕ. ОТВЕТСТВЕННОСТЬ, БУДУЩАЯ ПО ДОГОВОРУ, ДЕЛИКТУ ИЛИ ИНЫМ ОБРАЗОМ, ВОЗНИКАЮЩАЯ ИЗ
ВНЕ ИЛИ В СВЯЗИ С ПРОГРАММНЫМ ОБЕСПЕЧЕНИЕМ ИЛИ ИСПОЛЬЗОВАНИЕМ ИЛИ ДРУГИМИ СДЕЛКАМИ В
ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ." 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=4 \
--text-info --fontname="Serif bold italic 12" --show-uri --scroll \
<<< '                                            Проект поддержали:
                                    https://boosty.to/portwine-linux.ru

    1 1
    A B
    AdamArclight666
    Akai
    AkiraKai
    Aleks
    Aleksey Shvetcov
    Alex Sh
    Alexey RasskazovskyQ
    Alexsei Cherniavskiy
    Allegra_g
    AlxChkln
    amikha1lov
    Andrei K
    anisan_sg
    Another games
    Apofis Smab
    apolon
    Aule Mahal
    Azartiny Mor
    Bat1stuff
    BELIJJAaL
    benya
    BRXC
    Bunny Sword
    CanBoo
    Captain Dmitro
    caradat
    chal55rusSergey P.
    Coin Hunt
    Cruze
    D M_y
    d.kostroma
    Dadenard
    Dallasss
    Daniil Go
    Dencher12
    Denis Veduta
    devmorro
    Dezert1r
    didi_side
    Dima Manshin
    Dmitriy Tokarev
    Dnevnnoy
    Drakorgaur
    DSergeev
    dunkanMcLoud
    dupster mailbox
    El Mago
    Eliot
    Ethan Winters
    Evgen Buiko
    Evgeniy Politov
    EvilDevolver
    fight fox
    funti2f
    fusiok
    GaiverX
    Gekko
    Geomant17
    gg_harper
    Graddlly
    Happy Husky
    haravara
    Haschwalth
    haunteduser
    Homyakin
    horuno2020
    Igor14936
    Ivan Vlasov
    ivboss
    Ivory_drive
    Jackie
    Jeta
    JRX
    July April
    Kitsune_Yagiza
    ksandr4370
    LeGi0neR
    Lexa XLS
    lifeteo
    Linux Vumtut
    Lonely Lonely
    Looter-bit
    Lynx Jam
    Maks Jjot
    Maksami Cordyceps
    Maktub
    Melord
    MetaP
    Michael Karpenya
    MICROFARAT
    MLogaut
    Monti Roquefort
    Mr. Gex
    MrBatonio
    mrquokka
    nanCreate
    Nesterik
    Nikola P.
    Nuclearsun
    Nurik
    Oleg55Rus
    onix
    Optimus
    Ottakvot
    paulscathedral
    PaveL SakharuK
    penguin4ek
    Pependos
    PLAFON
    PlagueEvgeny
    Rojok56
    Ruslan Vlasov
    Rustam
    Saireg
    SamualV
    sanelasan
    sashman
    Seeropoonya
    sendependa_dio
    Sergey Zotov
    shecspir
    Slir3x
    Soma
    sship
    Subscript
    Sudo Connect
    sugoyako
    svo
    Taras Zagibalov
    The End
    tima
    typedef
    ua3dko
    V1ktr
    Valevicor
    VanBugel
    vano_364
    VAtiB
    Vikthor Prieto
    vlad petrov
    Vosarat
    VUMtut
    Windchester
    WK217
    wrager
    xpamych
    Xpamych
    Yasiok
    Yurec
    Zillah Giovanni
    Zloy Ivan
    Zorit
    Александр Абдулов
    Александр Аброськин
    Александр Кладов
    Александр Лобанов
    Александр Мерзликин
    Алексей Ultralin
    Алексей Войтенко
    Алексей Галаш
    Алексей Зубрийчук
    Алексей Ивушкин
    Алексей Самойлов
    Алексей Чугунов
    Андрей Гусаков
    Андрей Карпенцов
    Андрей Нешта
    Антон Рудковский
    Антон Фамилианов
    Антоний Дамикан
    Артём К.
    Артём М.
    Валерий Толмачёв
    Виктор Щетинин
    Виндэтарог
    Виталий Богаченко
    Виталий Нуров
    Виталий Росляков
    Виталий Яновский
    Влад Блинов
    Влад Кладиев
    Владимир Бильдюкевич
    Владимир Гл-Ко
    Владимир Дарвин
    Владимир Мурзин
    Вячеслав Шитюков
    Вячеслав Шустров
    Георгий Гурский
    Григорий Кожуханцев
    Данил Лужецкий
    Данил Павлов
    Дед Мазай
    Денис Мальцев
    Денис Матій
    Денис Олефиренко
    Дмитрий
    Дмитрий Круглов
    Дмитрий Лихачёв
    Дмитрий Мазанка
    Дмитрий Маньшин
    Дмитрий Матвеенко
    Дмитрий Сидоров
    Евгений Бебин
    Евгений Горенков
    Евгений Долгополов
    Евгений Хирвонен
    Евгений Храмов
    Егор Кречун
    Жан-Люк Пикар
    Женя Рябушкин
    Иван Белекеев
    Иван Сильянов
    Иван Чевычелов
    Кирилл Пушкарский
    Кирилл Т
    Коляныч Королёв
    Константин __
    Константин Абадонна
    Леонид
    Макс Безумный
    Максим Хмара-Миронов
    Маленькая сосна
    Марат
    Марат Рахимов
    Михаил Полозов
    Неизвестый Дмитрий
    Никита Булавин
    Никита Иванов
    Никита Попков
    николай гинтов
    Николай Садомов
    Олег Скакунов
    Павел Иванов
    Павел Пашенцев
    Павел Хозяинимени
    Равич Ревес
    Рамиль Миннигалиев
    Рома Б.
    Роман Игнатьев
    Роман Паженский
    Ростислав Кузнецов
    Саша
    Семён
    Семён Клишин
    Семён Сорокин
    Сергей Sid
    Сергей Александрович К.
    Сергей Шипарев
    Серёга Сапрыкин
    Стас Толкачёв
    Тима Суеубаев
    Тимофей Ковалев
    Тимур Сафонов
    Удалить Аккаунт
    Хоттабыч
    Энвер
    Юрий Константинов
    Юрий С.
    Юрий Семен
    Ярослав Москвин

                                    Список будет дополняться...' 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=5 --text="Хотите присоединится и помочь в развитии проекта:" \
--title=JOIN --window-icon=group  --image=system-config-users --uri-color=red --show-uri \
--text-info --scroll <<< \
"Website:  https://linux-gaming.ru/
Discord:  http://discord.gg/yJSEFjF
VK:       https://vk.com/linuxgamingru
-------------------------------------------
Стать платным подписчиком:
boosty: https://boosty.to/portwine-linux.ru
Yandex кошелек:   410012267513818
-------------------------------------------" 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=6 --show-uri --title="THIRD PARTY LIBRARIES" \
--fontname="Serif bold italic 10" --text-info <<< "                   Сторонние библиотеки, которые используются в PortProton

    PortProton собран на основе бесплатных библиотек программного обеспечения:

WINE-PROTON: https://github.com/ValveSoftware/Proton
WINE-PROTON-GE: https://github.com/GloriousEggroll/proton-ge-custom/
Kron4ek/Wine: https://github.com/Kron4ek/Wine-Builds
YAD: https://github.com/v1cont/yad" 2>/dev/null &

"${pw_yad_v13_0}" --title "О НАС" --key="${KEY_CREDITS}" --window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
 --notebook --no-buttons  --tab-pos=bottom \
--tab="О PORTPROTON" --tab="АВТОРЫ" --tab="ЛИЦЕНЗИЯ" --tab="СПОНСОРЫ" --tab="ПРИСОЕДИНИТЬСЯ" \
--tab="БИБЛИОТЕКИ"
    echo "Exit from credits"
    /usr/bin/env bash -c ${pw_full_command_line[*]} &
    exit 0

else

    KEY_CREDITS=$RANDOM


"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=1 --show-uri \
--image-path="$PW_GUI_ICON_PATH" --image="port_proton" \
--text-align=center --scroll --text="PortProton v. ${install_ver}
scripts v. ${scripts_install_ver}


https://linux-gaming.ru

Copyright © 2022 Castro-Fidel (linux-gaming.ru)

This program comes with absolutely no warranty.
See the License for details." 2>/dev/null &


"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=2 \
--text-align=center --scroll --text="Author:   Casro-Fidel (Mikhail Tergoev)

Developer assistants and testers:
Cefeiko
Dezert1r
Taz_mania
Anton_Famillianov
RidBowt
chal55rus
UserDiscord
Survolog
gavr
RusNor
aldiserg
an9949an
andrey4korop
zorn
Vano Majukin
Sergey 33(46)RUS
WelchDragon
Vuursteen
Boria138
Akai
" 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=3 --text-info --scroll <<< "MIT License

Copyright (©) 2022 Castro-Fidel (linux-gaming.ru)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED (AS IS), WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE." 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=4 \
--text-info --fontname="Serif bold italic 12" --show-uri --scroll \
<<< '                                    The project was supported:
                              https://boosty.to/portwine-linux.ru:

    1 1
    A B
    AdamArclight666
    Akai
    AkiraKai
    Aleks
    Aleksey Shvetcov
    Alex Sh
    Alexey RasskazovskyQ
    Alexsei Cherniavskiy
    Allegra_g
    AlxChkln
    amikha1lov
    Andrei K
    anisan_sg
    Another games
    Apofis Smab
    apolon
    Aule Mahal
    Azartiny Mor
    Bat1stuff
    BELIJJAaL
    benya
    BRXC
    Bunny Sword
    CanBoo
    Captain Dmitro
    caradat
    chal55rusSergey P.
    Coin Hunt
    Cruze
    D M_y
    d.kostroma
    Dadenard
    Dallasss
    Daniil Go
    Dencher12
    Denis Veduta
    devmorro
    Dezert1r
    didi_side
    Dima Manshin
    Dmitriy Tokarev
    Dnevnnoy
    Drakorgaur
    DSergeev
    dunkanMcLoud
    dupster mailbox
    El Mago
    Eliot
    Ethan Winters
    Evgen Buiko
    Evgeniy Politov
    EvilDevolver
    fight fox
    funti2f
    fusiok
    GaiverX
    Gekko
    Geomant17
    gg_harper
    Graddlly
    Happy Husky
    haravara
    Haschwalth
    haunteduser
    Homyakin
    horuno2020
    Igor14936
    Ivan Vlasov
    ivboss
    Ivory_drive
    Jackie
    Jeta
    JRX
    July April
    Kitsune_Yagiza
    ksandr4370
    LeGi0neR
    Lexa XLS
    lifeteo
    Linux Vumtut
    Lonely Lonely
    Looter-bit
    Lynx Jam
    Maks Jjot
    Maksami Cordyceps
    Maktub
    Melord
    MetaP
    Michael Karpenya
    MICROFARAT
    MLogaut
    Monti Roquefort
    Mr. Gex
    MrBatonio
    mrquokka
    nanCreate
    Nesterik
    Nikola P.
    Nuclearsun
    Nurik
    Oleg55Rus
    onix
    Optimus
    Ottakvot
    paulscathedral
    PaveL SakharuK
    penguin4ek
    Pependos
    PLAFON
    PlagueEvgeny
    Rojok56
    Ruslan Vlasov
    Rustam
    Saireg
    SamualV
    sanelasan
    sashman
    Seeropoonya
    sendependa_dio
    Sergey Zotov
    shecspir
    Slir3x
    Soma
    sship
    Subscript
    Sudo Connect
    sugoyako
    svo
    Taras Zagibalov
    The End
    tima
    typedef
    ua3dko
    V1ktr
    Valevicor
    VanBugel
    vano_364
    VAtiB
    Vikthor Prieto
    vlad petrov
    Vosarat
    VUMtut
    Windchester
    WK217
    wrager
    xpamych
    Xpamych
    Yasiok
    Yurec
    Zillah Giovanni
    Zloy Ivan
    Zorit
    Александр Абдулов
    Александр Аброськин
    Александр Кладов
    Александр Лобанов
    Александр Мерзликин
    Алексей Ultralin
    Алексей Войтенко
    Алексей Галаш
    Алексей Зубрийчук
    Алексей Ивушкин
    Алексей Самойлов
    Алексей Чугунов
    Андрей Гусаков
    Андрей Карпенцов
    Андрей Нешта
    Антон Рудковский
    Антон Фамилианов
    Антоний Дамикан
    Артём К.
    Артём М.
    Валерий Толмачёв
    Виктор Щетинин
    Виндэтарог
    Виталий Богаченко
    Виталий Нуров
    Виталий Росляков
    Виталий Яновский
    Влад Блинов
    Влад Кладиев
    Владимир Бильдюкевич
    Владимир Гл-Ко
    Владимир Дарвин
    Владимир Мурзин
    Вячеслав Шитюков
    Вячеслав Шустров
    Георгий Гурский
    Григорий Кожуханцев
    Данил Лужецкий
    Данил Павлов
    Дед Мазай
    Денис Мальцев
    Денис Матій
    Денис Олефиренко
    Дмитрий
    Дмитрий Круглов
    Дмитрий Лихачёв
    Дмитрий Мазанка
    Дмитрий Маньшин
    Дмитрий Матвеенко
    Дмитрий Сидоров
    Евгений Бебин
    Евгений Горенков
    Евгений Долгополов
    Евгений Хирвонен
    Евгений Храмов
    Егор Кречун
    Жан-Люк Пикар
    Женя Рябушкин
    Иван Белекеев
    Иван Сильянов
    Иван Чевычелов
    Кирилл Пушкарский
    Кирилл Т
    Коляныч Королёв
    Константин __
    Константин Абадонна
    Леонид
    Макс Безумный
    Максим Хмара-Миронов
    Маленькая сосна
    Марат
    Марат Рахимов
    Михаил Полозов
    Неизвестый Дмитрий
    Никита Булавин
    Никита Иванов
    Никита Попков
    николай гинтов
    Николай Садомов
    Олег Скакунов
    Павел Иванов
    Павел Пашенцев
    Павел Хозяинимени
    Равич Ревес
    Рамиль Миннигалиев
    Рома Б.
    Роман Игнатьев
    Роман Паженский
    Ростислав Кузнецов
    Саша
    Семён
    Семён Клишин
    Семён Сорокин
    Сергей Sid
    Сергей Александрович К.
    Сергей Шипарев
    Серёга Сапрыкин
    Стас Толкачёв
    Тима Суеубаев
    Тимофей Ковалев
    Тимур Сафонов
    Удалить Аккаунт
    Хоттабыч
    Энвер
    Юрий Константинов
    Юрий С.
    Юрий Семен
    Ярослав Москвин


                                      The list will be updated...' 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=5 --text="Do you want to join and help in the development of the project:" \
--title=JOIN --window-icon=group  --image=system-config-users --uri-color=red --show-uri \
--text-info --scroll <<< \
"Website:  http://linux-gaming.ru
Discord:  http://discord.gg/yJSEFjF
VK:       https://vk.com/linuxgamingru
-------------------------------------------
Become a paid subscriber:
boosty:  https://boosty.to/portwine-linux.ru
Yandex wallet:   410012267513818
-------------------------------------------" 2>/dev/null &

"${pw_yad_v13_0}" --plug="${KEY_CREDITS}" --tabnum=6 --show-uri --title="THIRD PARTY LIBRARIES" \
--fontname="Serif bold italic 10" --text-info <<< "                               Third-party libraries that are used in PortProton

              PortProton is built on the basis of the following free software libraries:

WINE-PROTON: https://github.com/ValveSoftware/Proton
WINE-PROTON-GE: https://github.com/GloriousEggroll/proton-ge-custom/
Kron4ek/Wine: https://github.com/Kron4ek/Wine-Builds
YAD: https://github.com/v1cont/yad" 2>/dev/null &


"${pw_yad_v13_0}" --title "ABOUT US" --key="${KEY_CREDITS}" ---window-icon="$PW_GUI_ICON_PATH/portproton.svg" \
--notebook --no-buttons  --tab-pos=bottom \
--tab="ABOUT PORTPROTON" --tab="AUTORS" --tab="LICENSE" --tab="SPONSORS" --tab="JOIN" \
--tab="THIRD PARTY LIBRARIES"

    echo "Exit from credits"
    /usr/bin/env bash -c ${pw_full_command_line[*]} &
    exit 0
fi
