#!/usr/bin/env bash
# Author: chal55rus, Castro-Fidel (linux-gaming.ru)
########################################################################
if [ "${update_loc}" = "RUS" ]
then
    KEY_CREDITS=$RANDOM

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=1 --show-uri \
--image-path="$PW_GUI_ICON_PATH" --image="port_proton" \
--text-align=center --scroll --text="PortProton v. ${install_ver}
scripts v. ${scripts_install_ver}

https://linux-gaming.ru

Авторские права © 2022 Castro-Fidel (linux-gaming.ru)

Эта программа поставляется без каких-либо гарантий.
Подробнее см. в Лицензия." &


"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=2 \
--text-align=center --scroll --text="Автор:   Casro-Fidel (Михаил Тергоев)

Помощники разработчика и тестировщики:
Cefeiko
Dezert1r
Taz_mania
Anton_Famillianov
RidBowt
chal55rus
UserDiscord
Survolog
gavr
RusNor
aldiserg
an9949an
andrey4korop
zorn
Vano Majukin
" &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=3 --text-info --scroll <<< "          Лицензия Массачусетского технологического института (MIT License)

              Авторские права (©) 2022 Castro-Fidel (linux-gaming.ru)

Настоящим предоставляется бесплатное разрешение любому лицу, получившему копию данного
программного обеспечения и связанных с ним файлов документации (Программное
обеспечение), для в Программном обеспечении без ограничений, включая, помимо прочего,
права использовать, копировать, изменять, объединять, публиковать, распространять,
сублицензировать и/или продавать копий Программного обеспечения, а также разрешить
лицам, которым Программное обеспечение предоставляется для этого при соблюдении
следующих условий:

Вышеприведенное уведомление об авторских правах и это уведомление о разрешении должны
быть включены во все копии или существенные части Программного обеспечения.

ПРОГРАММНОЕ ОБЕСПЕЧЕНИЕ ПРЕДОСТАВЛЯЕТСЯ (КАК ЕСТЬ), БЕЗ КАКИХ-ЛИБО ГАРАНТИЙ, ЯВНЫХ ИЛИ
ПОДРАЗУМЕВАЕТСЯ, ВКЛЮЧАЯ, ПОМИМО ПРОЧЕГО, ГАРАНТИИ КОММЕРЧЕСКОЙ ЦЕННОСТИ,
ПРИГОДНОСТЬ ДЛЯ ОПРЕДЕЛЕННОЙ ЦЕЛИ И НЕНАРУШЕНИЕ ПРАВ. НИ ПРИ КАКИХ ОБСТОЯТЕЛЬСТВАХ
АВТОРЫ ИЛИ ВЛАДЕЛЕЦ АВТОРСКИХ ПРАВ НЕСУТ ОТВЕТСТВЕННОСТЬ ЗА ЛЮБЫЕ ПРЕТЕНЗИИ, УЩЕРБ ИЛИ
ДРУГОЕ. ОТВЕТСТВЕННОСТЬ, БУДУЩАЯ ПО ДОГОВОРУ, ДЕЛИКТУ ИЛИ ИНЫМ ОБРАЗОМ, ВОЗНИКАЮЩАЯ ИЗ
ВНЕ ИЛИ В СВЯЗИ С ПРОГРАММНЫМ ОБЕСПЕЧЕНИЕМ ИЛИ ИСПОЛЬЗОВАНИЕМ ИЛИ ДРУГИМИ СДЕЛКАМИ В
ПРОГРАММНОГО ОБЕСПЕЧЕНИЯ." &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=4 \
--text-info --fontname="Serif bold italic 12" --show-uri --scroll \
<<< '                                            Проект поддержали:
                                    https://boosty.to/portwine-linux.ru

    1 1
    A B
    AdamArclight666
    Akai
    Aleks
    Alexsei Cherniavskiy
    Alex Sh
    Allegra_g
    AlxChkln
    amikha1lov
    Andrei K
    anisan_sg
    Another games
    Apofis Smab
    apolon
    Aule Mahal
    Azartiny Mor
    BELIJJAaL
    benya
    Bunny Sword
    CanBoo
    chal55rus
    Coin Hunt
    Cruze
    Dadenard
    Dallasss
    Daniil Go
    Dencher12
    Denis
    Dezert1r
    Dima Manshin
    DIO
    d.kostroma
    Dmitriy Tokarev
    Drakorgaur
    dunkanMcLoud
    dupster mailbox
    Eliot
    El Mago
    Ethan Winters
    Evgen Buiko
    EvilDevolver
    fight fox
    funti2f
    fusiok
    GaiverX
    Gekko
    Geomant17
    gg_harper
    Happy Husky
    haravara
    Homyakin
    Ivan Vlasov
    ivboss
    ksandr4370
    LeGi0neR
    Lexa XLS
    Linux Vumtut
    Lonely Lonely
    Maksami Cordyceps
    Maktub
    Melord
    MICROFARAT
    MLogaut
    Monti Roquefort
    MrBatonio
    Nesterik
    Nikola P.
    Nuclearsun
    Nurik
    Oleg55Rus
    onix
    Optimus
    Ottakvot
    paulscathedral
    penguin4ek
    Pependos
    PLAFON
    PlagueEvgeny
    Rojok56
    Ruslan Vlasov
    Rustam
    Saireg
    sanelasan
    sashman
    Seeropoonya
    sendependa_dio
    shecspir
    Soma
    sship
    StGdG
    Subscript
    Sudo Connect
    sugoyako
    Taras Zagibalov
    The End
    tima
    Tykva
    ua3dko
    V1ktr
    VanBugel
    VAtiB
    Vikthor Prieto
    vlad petrov
    Vosarat
    VUMtut
    Windchester
    wrager
    Xpamych
    Yurec
    Yuri Emelyanov
    Zillah Giovanni
    Zloy Ivan
    Zorit
    zorn
    Александр
    Александр Абдулов
    Александр Кладов
    Александр Лобанов
    Алексей Ultralin
    Алексей Войтенко
    Алексей Галаш
    Алексей Зубрийчук
    Алексей Ивушкин
    Алексей Кравчук
    Алексей Чугунов
    Андрей Гусаков
    Андрей Карпенцов
    Антоний Дамикан
    Антон Рудковский
    Антон Фамилианов
    Артём К.
    Валерий Толмачёв
    Виктор Шварц
    Виктор Щетинин
    Виндэта(рог)
    Виталий Нуров
    Влад Блинов
    Владимир Бильдюкевич
    Владимир Дарвин
    Влад Кладиев
    Вячеслав Шитюков
    Вячеслав Шустров
    Георгий Гурский
    Данил Павлов
    Дед Мазай
    Денис Мальцев
    Денис Матій
    Денис Олефиренко
    Дмитрий Круглов
    Дмитрий Мазанка
    Дмитрий Сидоров
    Евгений Бебин
    Евгений Долгополов
    Евгений Хирвонен
    Евгений Храмов
    Егор Кречун
    Женя Рябушкин
    Иван Белекеев
    Коляныч Королёв
    Константин __
    Константин Абадонна
    Леонид
    Максим Хмара-Миронов
    Маленькая сосна
    Марат
    Марат Рахимов
    Неизвестый Дмитрий
    Никита Булавин
    Николай Гинтов
    Павел Иванов
    Павел Пашенцев
    Равич Ревес
    Рамиль
    Рома Б.
    Роман Игнатьев
    Роман Паженский
    Ростислав Кузнецов
    Росляков Виталий
    Саша
    Семён Клишин
    Семён Ярополов
    Сергей Казёнкин
    Сергей Круглов
    Серёга Сапрыкин
    Стас Толкачёв
    Тима Суеубаев
    Тимофей Ковалев
    Тимур Сафонов
    Удалить Аккаунт
    Хоттабыч


                                    Список будет дополняться...' &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=5 --text="Хотите присоединится и помочь в развитии проекта:" \
--title=JOIN --window-icon=group  --image=system-config-users --uri-color=red --show-uri \
--text-info --scroll <<< \
"Website:  https://linux-gaming.ru/
Discord:  http://discord.gg/yJSEFjF
VK:       https://vk.com/linuxgamingru
-------------------------------------------
Стать платным подписчиком:
boosty: https://boosty.to/portwine-linux.ru
patreon: https://www.patreon.com/portproton
Кошельки WebMoney:   WMZ-Z135951244401   WME-E325631629973
Yandex кошелек:   410012267513818
-------------------------------------------
Задонатить на стрим:
https://www.donationalerts.com/r/portwine_linux" &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=6 --show-uri --title="THIRD PARTY LIBRARIES" \
--fontname="Serif bold italic 10" --text-info <<< "                   Сторонние библиотеки, которые используются в PortProton

    PortProton собран на основе бесплатных библиотек программного обеспечения:

WINE-PROTON: https://github.com/ValveSoftware/Proton
WINE-PROTON-GE: https://github.com/GloriousEggroll/proton-ge-custom/
Kron4ek/Wine: https://github.com/Kron4ek/Wine-Builds
YAD: https://github.com/v1cont/yad
ZENITY: https://github.com/GNOME/zenity" &
        
"${pw_yad_new}" --title "О НАС" --key="${KEY_CREDITS}" --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
--center --notebook --no-buttons  --tab-pos=bottom \
--tab="О PORTPROTON" --tab="АВТОРЫ" --tab="ЛИЦЕНЗИЯ" --tab="СПОНСОРЫ" --tab="ПРИСОЕДИНИТЬСЯ" \
--tab="БИБЛИОТЕКИ"
    echo "Exit from credits"
    /usr/bin/env bash -c ${pw_full_command_line[*]} 

else

    KEY_CREDITS=$RANDOM


"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=1 --show-uri \
--image-path="$PW_GUI_ICON_PATH" --image="port_proton" \
--text-align=center --scroll --text="PortProton v. ${install_ver}
scripts v. ${scripts_install_ver}


https://linux-gaming.ru

Copyright © 2022 Castro-Fidel (linux-gaming.ru)

This program comes with absolutely no warranty.
See the License for details." &


"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=2 \
--text-align=center --scroll --text="Author:   Casro-Fidel (Mikhail Tergoev)

Developer assistants and testers:
Cefeiko
Dezert1r
Taz_mania
Anton_Famillianov
RidBowt
chal55rus
UserDiscord
survolog
gavr
RusNor
aldiserg
an9949an
andrey4korop
zorn
" &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=3 --text-info --scroll <<< "MIT License

Copyright (©) 2022 Castro-Fidel (linux-gaming.ru)

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED (AS IS), WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE." &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=4 \
--text-info --fontname="Serif bold italic 12" --show-uri --scroll \
<<< '                                    The project was supported:
                              https://boosty.to/portwine-linux.ru:

    1 1
    A B
    AdamArclight666
    Akai
    Aleks
    Alex Sh
    Alexsei Cherniavskiy
    Allegra_g
    AlxChkln
    Andrei K
    Another games
    Apofis Smab
    Aule Mahal
    Azartiny Mor
    BELIJJAaL
    CanBoo
    Coin Hunt
    Cruze
    DIO
    Dadenard
    Dallasss
    Daniil Go
    Dencher12
    Denis
    Dezert1r
    Dima Manshin
    Dmitriy Tokarev
    Drakorgaur
    El Mago
    Eliot
    Ethan Winters
    Evgen Buiko
    EvilDevolver
    GaiverX
    Gekko
    Geomant17
    Happy Husky
    Homyakin
    Ivan Vlasov
    LeGi0neR
    Lexa XLS
    Linux Vumtut
    Lonely Lonely
    MICROFARAT
    MLogaut
    Maksami Cordyceps
    Maktub
    Melord
    Monti Roquefort
    MrBatonio
    Nesterik
    Nikola P.
    Nuclearsun
    Nurik
    Oleg55Rus
    Optimus
    Ottakvot
    PLAFON
    Pependos
    PlagueEvgeny
    Rojok56
    Ruslan Vlasov
    Rustam
    Saireg
    Seeropoonya
    Soma
    StGdG
    Subscript
    Sudo Connect
    Taras Zagibalov
    The End
    Tykva
    V1ktr
    VAtiB
    VUMtut
    VanBugel
    Vikthor Prieto
    Vosarat
    Windchester
    Xpamych
    Yurec
    Yuri Emelyanov
    Zillah Giovanni
    Zloy Ivan
    Zorit
    amikha1lov
    anisan_sg
    apolon
    benya
    chal55rus
    d.kostroma
    dunkanMcLoud
    dupster mailbox
    fight fox
    funti2f
    fusiok
    gg_harper
    haravara
    ivboss
    ksandr4370
    onix
    paulscathedral
    penguin4ek
    sanelasan
    sashman
    sendependa_dio
    shecspir
    sship
    sugoyako
    tima
    ua3dko
    vlad petrov
    wrager
    xpamych
    zorn
    Alexander
    Alexander Abdulov
    Alexander Kladov
    Alexander Lobanov
    Alexey Ultralin
    Alexey Voitenko
    Alexey Galash
    Alexey Zubriychuk
    Alexey Ivushkin
    Alexey Kravchuk
    Alexey Chugunov
    Andrey Gusakov
    Andrey Karpentsov
    Anton Rudkovsky
    Anton Surnames
    Antony Damikan
    Artyom K.
    Valery Tolmachev
    Victor Schwartz
    Victor Shchetinin
    Vindeta (horn)
    Vitaly Nurov
    Vlad Blinov
    Vlad Kladiev
    Vladimir Bildyukevich
    Vladimir Darwin
    Vyacheslav Shityukov
    Vyacheslav Shustrov
    George Gursky
    Danil Pavlov
    Grandfather Mazai
    Denis Maltsev
    Denis Matiy
    Denis Olefirenko
    Dmitry Kruglov
    Dmitry Mazanka
    Dmitry Sidorov
    Evgeny Bebin
    Evgeny Dolgopolov
    Evgeny Hirvonen
    Evgeny Khramov
    Egor Krechun
    Zhenya Ryabushkin
    Ivan Belekeyev
    Kolyanich Korolev
    Konstantin __
    Konstantin Abadonna
    Leonid
    Maxim Khmara-Mironov
    Little Pine
    Marat
    Marat Rakhimov
    Unknown Dmitry
    Nikita Bulavin
    Pavel Ivanov
    Pavel Pashentsev
    Ravich Reves
    Ramil
    Roma B.
    Roman Ignatiev
    Roman Pazhensky
    Sasha
    Semyon Klishin
    Semyon Yaropolov
    Sergey Kazenkin
    Sergey Kruglov
    Serega Saprykin
    Stas Tolkachev
    Tima Sueubaev
    Timofey Kovalev
    Timur Safonov
    Delete Account
    Hottabych
    Nikolai Gintov


                                      The list will be updated...' &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=5 --text="Do you want to join and help in the development of the project:" \
--title=JOIN --window-icon=group  --image=system-config-users --uri-color=red --show-uri \
--text-info --scroll <<< \
"Website:  http://linux-gaming.ru
Discord:  http://discord.gg/yJSEFjF
VK:       https://vk.com/portwinelinux
-------------------------------------------
Become a paid subscriber:
boosty:  https://boosty.to/portwine-linux.ru
patreon: https://www.patreon.com/portproton
WebMoney wallets:   WMZ-Z135951244401   WME-E325631629973
Yandex wallet:   410012267513818
-------------------------------------------
Donat on stream:
https://www.donationalerts.com/r/portwine_linux" &

"${pw_yad_new}" --plug="${KEY_CREDITS}" --tabnum=6 --show-uri --title="THIRD PARTY LIBRARIES" \
--fontname="Serif bold italic 10" --text-info <<< "                               Third-party libraries that are used in PortProton

              PortProton is built on the basis of the following free software libraries:

WINE-PROTON: https://github.com/ValveSoftware/Proton
WINE-PROTON-GE: https://github.com/GloriousEggroll/proton-ge-custom/
Kron4ek/Wine: https://github.com/Kron4ek/Wine-Builds
YAD: https://github.com/v1cont/yad
ZENITY: https://github.com/GNOME/zenity" &


"${pw_yad_new}" --title "ABOUT US" --key="${KEY_CREDITS}" --window-icon="$PW_GUI_ICON_PATH/port_proton.png" \
--center --notebook --no-buttons  --tab-pos=bottom \
--tab="ABOUT PORTPROTON" --tab="AUTORS" --tab="LICENSE" --tab="SPONSORS" --tab="JOIN" \
--tab="THIRD PARTY LIBRARIES"

    echo "Exit from credits"
    /usr/bin/env bash -c ${pw_full_command_line[*]} 
fi
