#!/usr/bin/env bash
# Author: linux-gaming.ru
# Helped in translation: ConTI1NuEsZZZ and Boria138

unset update_loc
if [[ -f "${PORT_WINE_TMP_PATH}/PortProton_loc" ]] ; then
	update_loc=$(cat "${PORT_WINE_TMP_PATH}/PortProton_loc")
	export update_loc
fi

if ! check_flatpak \
&& [[ -z "${LANG}" ]] ; then
	export LANG=C
	export update_loc="ENG"
else
	if [[ "${update_loc}" == "RUS" || "${update_loc}" == "ENG" ]] && [[ -f "${PORT_WINE_TMP_PATH}/PortProton_loc" ]] ; then
		echo ""
	else
		[[ ! -f "${pw_yad_v13_0}" ]] && pw_yad_v13_0="yad"
		SET_LANG=$("${pw_yad_v13_0}" --title  "LAUNGUAGE" --text "Select the language:" --list --radiolist \
		--column="Set:" --column "Choose language:" TRUE "RUS" FALSE "ENG" \
		--window-icon "$PW_GUI_ICON_PATH/portproton.svg" --width=300 --height=150)
		SET_LANG="$(echo "${SET_LANG}" | awk -F'|' '{print $2}')"
		echo "${SET_LANG}" > "${PORT_WINE_TMP_PATH}/PortProton_loc"
		if [[ ! -z "${SET_LANG}" ]]
		then export update_loc=${SET_LANG}
		else exit 1
		fi
	fi
fi

if [[ "${update_loc}" == "RUS" ]] ; then
	# check_flatpak && export LANG=ru_RU.UTF-8

	export loc_gui_pw_reinstall_pp="Переустановить PortProton"
    export loc_gui_rm_pp="Удалить PortProton"
    export loc_gui_upd_pp="Проверить обновления"
    export loc_gui_changelog="История изменений"
	export loc_gui_change_loc="Сменить язык интерфейса"
    export loc_gui_edit_usc="Редактировать USER.CONF"
    export loc_gui_scripts_fb="Откатить версию скриптов"
    export loc_gui_credits="Авторы и спасибы =)"

    export loc_gui_clear_pfx="Очистить префикс"
    export loc_gui_download_other_wine="Скачать другую версию wine"
    export loc_gui_create_pfx_backup="Создать резервную копию префикса"

    export loc_create_pfx_backup_path="РЕЗЕРВНОЕ КОПИРОВАНИЕ ПРЕФИКСА В..."

    export loc_gui_wine_uninstaller="Удаление программ"
    export loc_gui_wine_cfg="Настройка префикса"
    export loc_gui_wine_file="Файловый менеджер"
    export loc_gui_wine_cmd="Командная строка"
    export loc_gui_wine_reg="Редактор реестра"

	export loc_tray_winefile="Файловый менеджер WINE"
	export loc_tray_tascmng="Диспетчер задач WINE"
	export loc_tray_cangelog="История изменений"
	export loc_tray_force_exit="Завершить работу PortProton"

	export loc_mg_autoinstall="АВТОУСТАНОВКА"
	export loc_mg_emulators="ЭМУЛЯТОРЫ"
	export loc_mg_wine_settings="НАСТРОЙКИ WINE"
	export loc_mg_portproton_settings="НАСТРОЙКИ PORTPROTON"
	export loc_mg_installed="УСТАНОВЛЕННЫЕ"

	export PW_CHANGELOG_FILE="changelog_rus"
	export PW_SELECTION_DB_LOC="Найдено более одного DB файла для запускаемого приложения.\nВыберите необходимый, или перед следующим запуском удалите лишний DB файл.\n"

	export inst_set="Выбор"
	export inst_set_top="Установка PortProton"
	export sc_info="Ярлык будет создан в каталоге PortProton."
	export sc_name="Название"
	export sc_menu_desktop="Добавить ярлык в МЕНЮ -> Игры"
	export sc_desktop_desktop="Добавить ярлык на Рабочий стол"
	export sc_add_in_steam="Добавить ярлык в библиотеку STEAM"
	export sc_restert_steam="Для добавления ярлыка в STEAM, необходим перезапуск.\n\nПерезапустить STEAM?"

	export inst_succ="Установка завершена успешно!"

	export port_upd1="Обновление PortProton"
	export port_upd2="На сайте linux-gaming.ru вышло обновление для PortProton\n"
	export port_upd3="Действие:"
	export port_upd4="Перейти на сайт"
	export port_upd5="Напомнить позже"
	export port_upd6="Больше не напоминать"

	export scripts_upd1="Обновление скриптов"
	export scripts_upd2="Доступно обновление скриптов для PortProton"
	export scripts_upd3="ВЫХОД"
	export scripts_upd4="ОБНОВИТЬ СЕЙЧАС"
	export scripts_upd5="НАПОМНИТЬ ПОЗЖЕ"
	export scripts_upd6="НЕ НАПОМИНАТЬ"

	export port_clear_pfx="Вы действительно хотите очистить префикс PortProton?"

	export port_del1="Удаление PortProton"
	export port_del2="Вы действительно хотите полностью удалить PortProton?"

	export port_reinstall="Вы действительно хотите переустановить PortProton?\nДля этого будет необходимо интернет соединение."

	export port_deb1="PortWINE был запущен в режиме создания PortProton.log и он успешно сохранен в корне каталога порта"
	export port_deb2="Для диагностики проблемы, скопируйте ВЕСЬ лог в соответствующий канал у нас на сервере дискорда: https://discord.gg/FTaheP99wE"

	export port_start1="Запуск PortProton"
	export port_start2="В каком режиме вы хотите запустить PortProton?"
	export port_start3="Режим:"
	export port_start4="Обычный"
	export port_start5="Отдельной X-сессии"
	export port_start6="Создать ЛОГ-файл"
	export port_start7="Запустить winetricks"
	export port_start8="DXVK"

	export port_debug="Не торопитесь! После окончания работы PortProton, нажмите STOP."

	export loc_create_shortcut_from_gui="Создать ярлык..."
	export loc_create_shortcut="Создать ярлык для запускаемого файла."
	export loc_delete_shortcut="Удалить ярлык для запускаемого файла."
	export loc_debug="Запуск c созданием .log файла в корне PortProton"
	export loc_launch="Запустить файл..."
	export loc_winecfg="Запустить winecfg для редактирования настроек выбранного префикса"
	export loc_winefile="Запустить файловый менеждер встроенный в wine"
    export loc_winecmd="Запустить командную строку wine"
	export loc_winereg="Запустить редактор реестра выбранного префикса"
    export loc_wineuninstaller="Запустить средство удаление программ встроенное в wine"
    export loc_winetricks="Запустить префикс менеджер для установки доп. библиотек в выбранный префикс"
	export loc_edit_db="Изменить файл настроек для"
	export loc_download_other_wine="Открыть меню для скачивания других версий WINE-PROTON"
	export loc_downloading="Скачивание"

	export loc_clear_pfx="Очистить префикс для исправления проблем"

	export loc_gui_dll_new_pfx="Установить рекомендованные библиотеки в новый префикс:  "

	export loc_gui_portproton_lock='Обнаружена запущенная сессия PortProton.\nХотите завершить предыдущую сессию?'

	export ENABLE_VKBASALT_INFO='Включить vkBasalt по умолчанию для улучшение графики в играх работающих под Vulkan. (Горячая клавиша HOME отключает vkbasalt)'
	export PW_NO_ESYNC_INFO='Не использовать примитивы внутрипроцессной синхронизации на основе eventfd. (Рекомендуется не изменять значение)'
	export PW_NO_FSYNC_INFO='Не использовать примитивы внутрипроцессной синхронизации на основе фьютексов. (Автоматически отключается в системах без FUTEX_WAIT_MULTIPLE поддержки) (Рекомендуется не изменять значение)'
	export PW_USE_RAY_TRACING_INFO='Включить поддержку vkd3d - Ray Tracing'
	export PW_FIX_VIDEO_IN_GAME_INFO='Требуется для воспроизведения видео в некоторых играх, чтобы оно не было искажено (обычно окрашено в розовый цвет)'
	export PW_VULKAN_NO_ASYNC_INFO='Выключить асинхронные вызовы для режимов VULKAN и DXVK'
	export PW_USE_NVAPI_AND_DLSS_INFO='Включить DLSS на поддерживаемых видеокартах NVIDIA'
	export PW_OLD_GL_STRING_INFO='Принудительное использование старых версий OpenGL'
	export PW_HIDE_NVIDIA_GPU_INFO='Замаскировать все функции используемые для видеокарт NVIDIA'
	export PW_FORCE_USE_VSYNC_INFO='Принудительное включение вертикальной синхронизации'
	export PW_VIRTUAL_DESKTOP_INFO='Включить запуск приложение в виртуальном рабочем столе WINE'
	export PW_USE_TERMINAL_INFO='Запускать приложение в терминале'
	export PW_HEAP_DELAY_FREE_INFO='Включить задержку освобождения некоторой памяти, чтобы обойти ошибки, связанные с использованием приложения после освобождения памяти.'
	export PW_NO_WRITE_WATCH_INFO='Очень опасный способ взлома таймера записи в памяти в ntdll. Это улучшает производительность некоторых очень специфических игр. (Рекомендуется не изменять значение)'
	export PW_GUI_DISABLED_CS_INFO='Отключить окно выбора режимов запуска и версии WINE'
	export PW_USE_GSTREAMER_INFO='Использовать Gstreamer для вывода роликов в играх (поддержка WMF)'
	export PW_FORCE_LARGE_ADDRESS_AWARE_INFO='Увеличивает ограничения на использование оперативной памяти для 32 битных приложений с двух до четырёх гигабайт'
	export PW_USE_RUNTIME_INFO='Использовать контейнерный режим запуска (Рекомендуется не изменять значение)'
	export PW_MANGOHUD_INFO='Использование мониторинга FPS и нагрузки системы (Включается и выключается сочитанием клавиш - правый Shift + F12)'
	export PW_USE_GAMEMODE_INFO='Использование автоматической оптимизации системы для увеличения производительности в играх (при условии установленного пакета gamemode в системе)'
	export PW_USE_WINE_DXGI_INFO='Принудительное использование встроенной библиотеки DXGI (в редких случаях решает проблемы с запуском игр под DX12)'
	export PW_MANGOHUD_USER_CONF_INFO='Принудительное использование системных настроек MANGOHUD (GOverlay и т.п.)'
	export PW_VKBASALT_USER_CONF_INFO='Принудительное использование системных настроек VKBASALT (GOverlay и т.п.)'
	export PW_USE_D3D_EXTRAS_INFO='Включить принудительное использование сторонних библиотек DirectX'
	export PW_USE_WINDOWS_7_INFO='Изменить версию WINDOWS 10 на WINDOWS 7 в префиксе'
	export PW_USE_SHADER_CACHE_INFO='Использовать кеширование шейдеров средствами WINE (отключать только при наличии микрофризов в игре)'
	export PW_WINE_FULLSCREEN_FSR_INFO='Работает во время использования любой версии ProtonGE в полноэкранном режиме при разрешении ниже стандартного для экрана'
	export PW_USE_FAKE_DLSS_INFO='Включить транслятор DLSS в FSR 2 в играх DirectX 12 (проект CyberFSR2)'
	export PW_USE_FAKE_DLSS_3_INFO='Включить транслятор DLSS в FSR 3 в играх DirectX 12 (Эксперементальный проект dlssg-to-fsr3)'
    export PW_USE_EAC_AND_BE_INFO='Включить Easy Anti-Cheat and BattlEye Anti-Cheat (требуется если игра использует какой-то из этих античитов)'
    export PW_REDUCE_PULSE_LATENCY_INFO='Уменьшить задержку pulseaudio для исправления прерывистого звука'
    export PW_USE_US_LAYOUT_INFO='Принудительное использование английской раскладки (полезно для игр в которых управление верно работает исключительно на английской раскладке)'
    export PW_RESTORE_RESOLUTION_INFO='Запомнить разрешение экрана при запуске игры и вернуть при закрытие (полезно для игр которые при закрытие меняют разрешение экрана)'
	export PW_USE_SYSTEM_VK_LAYERS_INFO='Использовать системные mangohud, vkBasalt, obs-vkcapture и прочие приложения использующие vulkan layers'
	export PW_USE_OBS_VKCAPTURE_INFO='Включить возможность записи в OBS Studio с помощью obs-vkcapture (ВНИМАНИЕ: будет включено принудительное использование системных mangohud, vkBasalt, obs-vkcapture и прочих приложений использующих vulkan layers)'
	export PW_USE_GALLIUM_ZINK_INFO='Использовать драйвер zink (OpenGL поверх Vulkan), позволяет использовать vkBasalt в играх на OpenGL (ВНИМАНИЕ: необходима поддержка vulkan, используется wined3d (opengl) вместо dxvk, подходит для игр на OpenGL и старых версий DirectX, на более новых версиях DirectX возможны артефакты)'
	export PW_DISABLE_COMPOSITING_INFO='Отключить композитинг (эффекты) рабочего стола. Зачастую улучшает производительность.'

	export PW_3DFX_INFO='Имитация старого графического ускорителя 3dfx (добавляет горизонтальные полосы)'
	export PW_AdaptiveSharpen_INFO='Увеличение резкости, можно использовать совместно с CAS'
	export PW_Bloom_INFO='Добавляет свечения от ярких источников света в игре'
	export PW_Border_INFO='Обрезка изображения сверху и снизу (как в кино =)'
	export PW_Cartoon_INFO='Сильное увеличение резкости краев текстур'
	export PW_ChromaticAberration_INFO='Добавляет хроматические аберрации к изображению'
	export PW_Clarity_INFO='Увеличение резкости текстур с небольшими модификациями контраста изображения (похож по эффекту на CAS)'
	export PW_ColorMatrix_INFO='Добавление холодных цветов'
	export PW_Colourfulness_INFO='Увеличение насыщенности цветов'
	export PW_FakeHDR_INFO='Расширение динамического диапазона цветов'
	export PW_FilmGrain2_INFO='Добавление эффекта зерна кинопленки'
	export PW_Curves_INFO='Увеличивает контрастность изображения, при этом не трогая яркие и тёмные участки, чтобы не пропала детализация в тенях и небе'
	export PW_Denoise_INFO='Уменьшение шумов за счет смазывания изображения'
	export PW_Emphasize_INFO='Уменьшение разрядности цветопередачи'
	export PW_FakeMotionBlur_INFO='Сильное размытие объектов в движении'
	export PW_FilmicAnamorphSharpen_INFO='Увеличение резкости (рекомендую для мультяшных игр)'
	export PW_FilmicPass_INFO='Добавление холодных цветов'
	export PW_SMAA_INFO='Альтернативный вариант сглаживания (меньший эффект, но с меньшим потреблением ресурсов GPU, относительно стандартного SMAA)'
	export PW_GaussianBlur_INFO='Небольшой эффект размытия ярких объектов (например пламя)'
    export PW_Glitch_INFO='Эффект глючной картинки'
    export PW_HighPassSharpen_INFO='Повышения резкости с использованием высокочастотных частот'
    export PW_HQ4X_INFO='Сглаживание близлежащих пикселей с дорисовкой недостающих частей (в обычных играх картинка размывается)'
    export PW_HSLShift_INFO='Усовершенствованный сдвиг HSL (для каждого оттенка)'
    export PW_Layer_INFO="Наложение изображения на игру (изображение лежит в папке $PORT_WINE_TMP_PATH/libs_v$PW_LIBS_VER/pressure-vessel/reshade/textures)"
    export PW_Levels_INFO='Увеличивает контрастность, но некоторые детали в тенях или бликах могут быть потеряны'
    export PW_LevelsPlus_INFO='Тоже что и Levels, но с меньшей потерей деталей'
    export PW_LiftGammaGain_INFO='Коррекция гаммы по отдельным цветовым каналам: красному, зелёному и синему'
    export PW_LightDoF_INFO='Увеличивает глубину резкости (сильно влияет на FPS)'
    export PW_LumaSharpen_INFO='Повышает резкость изображения для улучшения деталей'
    export PW_LUT_INFO='Цветокорекция изображения'
    export PW_MagicBloom_INFO='Тоже самое что Bloom, но более естественный'
    export PW_Monochrome_INFO='Преобразует изображение в черно-белое'
    export PW_MultiLUT_INFO='Расширенная версия LUT (предустановлен лут Hollywood)'
    export PW_MXAO_INFO='Алгоритм SSAO (сильно влияет на FPS)'
    export PW_NightVision_INFO='Эффект ночного зрения'
    export PW_Nostalgia_INFO='Делает картинку похожей на старые фотографии'
    export PW_PerfectPerspective_INFO='Эффект рыбьего глаза (подходит для VR)'
    export PW_PPFX_Godrays_INFO='Объёмное рассеяние света'
    export PW_Prism_INFO='Эффект призматической линзы'
    export PW_ReflectiveBumpMapping_INFO='Создаёт иллюзию глубины текстур'
    export PW_Sepia_INFO='Добавляет эффект сепии со старых фотографий'
    export PW_Splitscreen_INFO='Разделяет изображение на необработанное и обработанный вывод для сравнения'
    export PW_SurfaceBlur_INFO='Снижение детализации объектов без размытия контрастных контуров'
    export PW_Technicolor_INFO='Делает картинку похожей на фильмы 1930 годов'
    export PW_Technicolor2_INFO='Обновлённая версия Technicolor, даёт иную картинку, агрессивнее меняя цвета'
    export PW_TiltShift_INFO='Размытие по краям экрана для создания эффекта миниатюры'
    export PW_Tonemap_INFO='Изменяет насыщенность картинки'
    export PW_TriDither_INFO='Уменьшает количество шумов'
    export PW_UIDetect_INFO='Автоматически переключает эффекты в зависимости от видимости UI'
    export PW_Vibrance_INFO='Насыщает блеклые цвета, не трогая яркие'
    export PW_Vignette_INFO='Добавляет к изображению виньетку'
    export PW_AspectRatio_INFO='Эффект для настройки соотношения сторон (для игр которые не поддерживают широкоформатные мониторы)'
    export PW_UIMask_INFO='Часть общего шейдера ReShade . Он использует маску с градиентами от черного к белому, чтобы определить, где будут применены эффекты'
    export PW_StageDepth_INFO='Позволяет добавлять новые элементы в 3d-пространство внутри игры и применять пользовательские текстуры'
    export PW_PPFX_Bloom_INFO='Добавляет Bloom эффект'

	export ENABLE_MANGOHUD_INFO='Включите MangoHud по умолчанию (горячие клавиши R_SHIFT + F12 отключают MangoHud).'
	export PW_MH_arch_INFO='Показывает, является ли приложение 32-разрядным или 64-разрядным'
	export PW_MH_battery_INFO='Display current battery percent and energy consumption'
	export PW_MH_battery_icon_INFO='Отображение текущего процента заряда батареи и энергопотребления'
	export PW_MH_battery_time_INFO='Отображение оставшегося времени работы от аккумулятора'
	export PW_MH_battery_watt_INFO='Отображать мощность для опции батареи'
	export PW_MH_core_bars_INFO='Измените отображение core_load с цифр на вертикальные полосы'
	export PW_MH_core_load_INFO='Отображать нагрузку и частоту на ядро'
	export PW_MH_cpu_mhz_INFO='Показывает текущую частоту процессора в МГц'
	export PW_MH_cpu_power_INFO='Отображать потребляемую процессором мощность в ваттах'
	export PW_MH_cpu_temp_INFO='Отображение текущей температуры процессора'
	export PW_MH_device_battery_icon_INFO='Отобразите значок батареи беспроводного устройства.'
	export PW_MH_engine_short_names_INFO='Отобразите краткую версию используемого движка (например, OGL вместо OpenGL).'
	export PW_MH_engine_version_INFO='Отображать версию OpenGL или vulkan и движков рендеринга на основе vulkan'
	export PW_MH_exec_name_INFO='Отображать текущее имя исполняемого файла'
	export PW_MH_fcat_INFO='Позволяет анализировать захват кадра'
	export PW_MH_fps_metrics_INFO='Принимает список десятичных значений или значение avg, например avg,0,001'
	export PW_MH_frame_count_INFO='Показывать FPS'
	export PW_MH_full_INFO='Включите большинство переключаемых параметров (в настоящее время исключается гистограмма)'
	export PW_MH_gamemode_INFO='Отображает активность gamemode'
	export PW_MH_gpu_core_clock_INFO='Отображение частоты ядра графического процессора'
	export PW_MH_gpu_fan_INFO='Скорость врашение кулеров графического процессора'
	export PW_MH_gpu_junction_temp_INFO='Отображение текущей температуры графического процессора'
	export PW_MH_gpu_mem_clock_INFO='Отображение частоты памяти графического процессора'
	export PW_MH_gpu_mem_temp_INFO='Отображение текущей температуры графического процессора'
	export PW_MH_gpu_name_INFO='Отобразить имя графического процессора из pci.ids'
	export PW_MH_gpu_power_INFO='Отображение потребляемой мощности графического процессора в ваттах'
	export PW_MH_gpu_temp_INFO='Отображение текущей температуры графического процессора'
	export PW_MH_gpu_voltage_INFO='Отображение напряжения на графическом процессоре (работает только на графических процессорах AMD'
	export PW_MH_histogram_INFO='Измените график FPS на гистограмму'
	export PW_MH_horizontal_INFO='Отображение Mangohud в горизонтальном положении'
	export PW_MH_horizontal_stretch_INFO='Растягивает фон до ширины экрана в горизонтальном режиме'
	export PW_MH_hud_compact_INFO='Отображать компактную версию MangoHud'
	export PW_MH_hud_no_margin_INFO='Удалите отступы вокруг MangoHud'
	export PW_MH_io_read_INFO='Показать некэшированное чтение IO, в МБ/с'
	export PW_MH_io_write_INFO='Показать некэшированные записи, в МБ/с'
	export PW_MH_no_display_INFO='Скрыть MangoHud по умолчанию'
	export PW_MH_no_small_font_INFO='Используйте основной размер шрифта для мелкого текста, например, единиц измерения'
	export PW_MH_procmem_INFO='Отображает использование памяти процесса: resident, а также включает другие, если они отключены'
	export PW_MH_procmem_shared_INFO='Отображает использование памяти процесса: shared'
	export PW_MH_procmem_virt_INFO='Отображает использование памяти процесса: virtual'
	export PW_MH_ram_INFO='Отображение использования оперативной памяти системы'
	export PW_MH_resolution_INFO='Отображение текущего разрешения экрана'
	export PW_MH_show_fps_limit_INFO='Отображение текущего ограничения FPS'
	export PW_MH_swap_INFO='Отображение использования пространства для свопа рядом с использованием системной оперативной памяти'
	export PW_MH_temp_fahrenheit_INFO='Показывать температуру в градусах Фаренгейта'
	export PW_MH_throttling_status_INFO='Показывает, сбрасывает ли GPU мощность, ток, температуру или "другое" (показывает только, если сбрасывание происходит в данный момент). В настоящее время отключено по умолчанию для Nvidia, так как вызывает задержки на 3000-й серии.'
	export PW_MH_throttling_status_graph_INFO='То же, что и throttling_status, но отображает throttling на графике времени кадра и только throttling мощности и температуры.'
	export PW_MH_time_INFO='Отоброжение времени'
	export PW_MH_version_INFO='Показать текущую версию MangoHud'
	export PW_MH_vkbasalt_INFO='Показать включён ли vkBasalt'
	export PW_MH_vram_INFO='Отображение использования VRAM'
	export PW_MH_vulkan_driver_INFO='Отображает используемый драйвер vulkan (radv/amdgpu-pro/amdvlk)'
	export PW_MH_frametime='Отображение времени кадра рядом FPS'
	export PW_MH_wine_INFO='Показать используемую версию Wine или Proton'

	export PW_PFX_BACKUP_INFO="Внимание! Не передавайте резевную копию третьим лицам, есть риск потери аккаунтов"
	export PW_PFX_BACKUP_SUCCESS="Успешно создана резервная копия префикса:"
	export PW_PFX_BACKUP_ERROR="Произошла ошибка во время создания резервной копии префикса:"

	export loc_find_d3dadapter9_error="Не найден в системе.\nУстановите недостающий пакет: d3dadapter9"

	export loc_gui_create_shortcut_for_exe="Выберите .exe файл для которого необходимо создать ярлык и нажмите ОК.\n"

	export loc_gui_error='Ошибка.'
	export loc_gui_error_download="Проверьте интернет соединение и\nнажмите Repeat для повторной попытки скачивания"
	export loc_gui_settings="Пожалуйста подождите."
	export loc_gui_sett_info="Обновление конфигурации <b>PortProton</b>..."
	export loc_gui_edit_db="Изменение файла настроек для:"
	export loc_gui_edit_db_help="<b>ПРИМЕЧАНИЕ:</b> Для вывода справки по каждому пункту, просто наведите курсор мыши на текст."

	export loc_cancel="ОТМЕНИТЬ"
	export loc_gui_cancel="ОТМЕНИТЬ ИЗМЕНЕНИЯ"
	export loc_gui_cancel_help="Отменить текущие изменения и вернутся в предыдущее меню."

	export loc_gui_reset_db="СБРОСИТЬ НАСТРОЙКИ"
	export loc_gui_reset_db_help="Востановить все настройки по умолчанию."

	export loc_disabled="Отключено"
	export loc_skip="ПРОПУСТИТЬ"
	export loc_repeat="ПОВТОРИТЬ"

	export loc_gui_open_db="ОТКРЫТЬ ФАЙЛ НАСТРОЕК"
	export loc_gui_open_db_help="Открыть файл настроек <b>.ppdb</b> в системном текстовом редакторе для просмотра и изменений переменных вручную."

	export loc_gui_save_changes="СОХРАНИТЬ ИЗМЕНЕНИЯ"
	export loc_gui_save_changes_help="Сохранить текущие изменения, и перейти в предыдущее меню."

	export loc_gui_ver_windows="Изменить версию эмуляции <b>WINDOWS</b>"
	export loc_gui_ver_windows_help="Изменение версии эмуляции <b>WINDOWS</b> может потребоваться для запуска старых игр. Версии <b>WINDOWS</b> ниже 10 не поддерживает новые игры с DirectX 12."

	export loc_gui_aut_winetricks="Автоматически установить с помощью <b>WINETRICKS</b>"
	export loc_gui_aut_winetricks_help="Автоматически установить с помощью <b>WINETRICKS</b> дополнительных библиотек необходимых для запуска игры/программы. Список библиотек разделяются пробелами. (Пример есть в выпадающем списке)"

	export loc_gui_winedllover="Принудительно использовать/отключить библиотеки"
	export loc_gui_winedllover_help="Принудительное использование/отключиение библиотеки только для даного приложения. (Примеры есть в выпадающем списке)

Краткая инструкция:
	* библиотеки пишутся <b>БЕЗ</b> расширения файлов .dll
	* библиотеки разделяются точкой с запятой - <b>;</b>
	* библиотека=n     - использовать библиотеку <b>WINDOWS</b> (сторонюю)
	* библиотека=b     - использовать библиотеку <b>WINE</b> (встроенную)
	* библиотека=n,b  - использовать <b>WINDOWS</b> библиотеку, а затем <b>WINE</b>
	* библиотека=b,n  - использовать библиотеку <b>WINE</b>, а затем <b>WINDOWS</b>
	* библиотека=       - отключить использование данной библиотеки"

	export loc_gui_arg_exe="Добавить аргумент после <b>.exe</b> файла"
	export loc_gui_arg_exe_help="Добавление аргумента после <b>.exe</b> файла, так же как если бы вы добавили аргумент в ярлыке в системе  <b>WINDOWS </b>"

	export loc_gui_mango_fps="Ограничить FPS"
	export loc_gui_mango_fps_help="Включение ограничения количества кадров в секунду средстами MANGOHUD встроенного в PortProton"

	export loc_gui_arg_gamescope="Добавить аргументы для GAMESCOPE:"
	export loc_gui_arg_gamescope_help="Аргументы:

<b>-W, -H:</b>  установите разрешение, используемое game scope. Изменение размера окна gamescope обновит эти настройки. Если указано -H, а -W нет, предполагается соотношение сторон 16:9. По умолчанию установлено значение 1280×720.
<b>-w, -h:</b>  установите разрешение, используемое в игре. Если указано -h, а -w нет, предполагается соотношение сторон 16:9. По умолчанию используются значения, указанные в -W и -H.
<b>-r:</b>  установите ограничение частоты кадров для игры. По умолчанию значение неограниченно.
<b>-F fsr:</b>  используйте Fidelity FX Super Resolution 1.0 для увеличения масштаба.
<b>-F nis:</b>  используйте NVIDIA Image Scaling версии 1.0.3 для увеличения масштаба.
<b>-S integer:</b>  используйте целочисленное масштабирование.
<b>-S stretch:</b>  используйте масштабирование по ширине, игра заполнит окно. (например, с 4:3 до 16:9).
<b>-b:</b>  создайте окно без полей.
<b>-f:</b>  создайте полноэкранное окно."

	export PW_USE_GAMESCOPE_INFO="Включение использования gamescope для запуска приложения.
Горячие клавиши:

<b>Super + F:</b>  Переключение полноэкранного режима
<b>Super + N:</b>  Переключение фильтрации
<b>Super + U:</b>  Переключение масштабирования на FSR
<b>Super + Y:</b>  Переключение масштабирования на NIS
<b>Super + I:</b>  Увеличение резкости FSR на 1
<b>Super + O:</b>  Уменьшение резкости FSR на 1
<b>Super + S:</b>  Сделайте снимок экрана (находится в /tmp/gamescope_DATE.png)
<b>Super + G:</b>  Переключите захват клавиатуры
<b>Super + C:</b>  Обновить буфер обмена"

	export loc_gui_cpu_limit="Ограничить использование ядер процессора"
	export loc_gui_cpu_limit_help="Ограничения количества ядер процессора полезно для игр на движке Unity (Рекомендуется выставить значение равное 8)"

	export loc_gui_amd_vulkan_select="Изменить используемый драйвер vulkan для AMD"
	export loc_gui_amd_vulkan_select_help="Выбор какая реализация vulkan будет использоваться для запуска игры"

	export loc_gui_gpu_select="Выбрать видеокарту для запуска игры (в user.conf)"
	export loc_gui_gpu_select_help="Выбор какая видеокарта будет использоваться для запуска игры (используется для всех запускаемых игр и программ в PortProton.)"

	export loc_gui_check_new_wine="Проверяем новые версии WINE"
	export loc_gui_check_new_wine_error="Не удается проверить новые версии WINE."
	export loc_gui_set_new_wine="Выберите версию WINE для загрузки:"
	export loc_gui_del_wine="Выберите версию WINE для удаления:"
	export loc_gui_installed_wine="УСТАНОВЛЕННЫЕ"

	export loc_gui_ffx_cas="AMD FidelityFX - CAS предназначе для значительного улучшения резкости текстур без дополнительных установок модификаций для игр, с минимальной потерей производительности. (Для старых игр рекомендуется значение = 100)"
	export loc_gui_disabled_vkbas="ВЫКЛЮЧИТЬ VKBASALT"
	export loc_gui_disabled_vkbas_help="Выключить vkBasalt и перейти в предыдущее меню."
	export loc_gui_vkbasalt_top="Настройки vkBasalt для добавления эффектов в играх работающих под Vulkan. (Клавиша <b>HOME</b> отключает vkbasalt)\n<b>ПРИМЕЧАНИЕ:</b> Для вывода справки по каждому пункту, просто наведите курсор мыши на текст.\n"

	export loc_gui_disabled_mh="ВЫКЛЮЧИТЬ MANGOHUD"
	export loc_gui_disabled_mh_help="Выключить MangoHud и перейти в предыдущее меню."
	export loc_gui_mh_top="Настройки MangoHud  (Клавиши <b>R_SHIFT + F12</b> отключают MangoHud)\n<b>ПРИМЕЧАНИЕ:</b> Для вывода справки по каждому пункту, просто наведите курсор мыши на текст.\n"

	export loc_gui_no="НЕТ"
	export loc_gui_yes="ДА"

	export loc_gui_missing_shortcut="\nНе удалось найти файл:\n${portwine_exe}\n\nВНИМАНИЕ:\nЕсли вы забыли примонтировать диск с запускаемым приложением, нажмите ОТМЕНИТЬ!"
	export loc_gui_create_shortcut="СОЗДАТЬ ЯРЛЫК"
	export loc_gui_delete_shortcut="УДАЛИТЬ ЯРЛЫКИ"
	export loc_gui_launch="ЗАПУСТИТЬ"
	export loc_gui_debug="СОЗДАТЬ ЛОГ"
	export loc_gui_edit_db_start="НАСТРОИТЬ"
	export loc_gui_vkbasalt_start="VKBASALT"
	export loc_gui_mh_start="MANGOHUD"

	export loc_gui_db_comments="Найден файл настроек PortProton для"

	export loc_gui_vulkan_stable="Стабильные DXVK ${DXVK_STABLE_VER} и VKD3D ${VKD3D_STABLE_VER}"
	export loc_gui_vulkan_git="Новейшие DXVK ${DXVK_GIT_VER} и VKD3D ${VKD3D_GIT_VER}"
	export loc_gui_gallium_nine="GALLIUM_NINE (DX9 для MESA)"
	export loc_gui_open_gl="OPENGL (Для видеокарт без VULKAN)"

	export loc_gui_installing_the="Устанавливаем"
	export loc_gui_please_wait="Пожалуйста подождите..."

	export loc_dolphin="Эмулятор для игровых консолей Nintendo с высокой совместимостью"
	export loc_mame="Мультиаркадный эмулятор, позволяющий играть в старые аркадные игры"
	export loc_scummvm="Эмулятор для классических квестовых игр от LucasArts и других студий"
	export loc_retroarch="Многоплатформенный фронтенд для эмуляторов с обширными настройками"
	export loc_ppsspp_windows="Windows - Эмулятор для игровой консоли PlayStation Portable (PSP)"
	export loc_citra="Эмулятор для игровой консоли Nintendo 3DS"
	export loc_cemu="Эмулятор для игровой консоли Wii U"
	export loc_duckstation="Эмулятор для игровой консоли PlayStation 1"
	export loc_epsxe="Эмулятор для игровой консоли PlayStation 1 с высокой совместимостью"
	export loc_project64="Эмулятор для игровой консоли Nintendo 64"
	export loc_vba_m="Эмулятор для игровой консоли Game Boy Advance"
	export loc_yabause="Эмулятор для игровой консоли Sega Saturn"
	export loc_xenia="Эмулятор для игровой консоли Xbox 360"
	export loc_fceux=" Эмулятор для игровой консоли Nintendo Entertainment System (NES или Dendy)"
	export loc_xemu="Эмулятор для игровой консоли Xbox"
	export loc_demul="Эмулятор для игровой консоли Sega Dreamcast"
	export loc_rpcs3="Эмулятор для игровой консоли PlayStation 3"

	export loc_prefix_manager_comp='Выберите компонент для установки в префикс:'
	export loc_prefix_manager_font='Выберите шрифт для установки в префикс:'
	export loc_prefix_manager_conf='Изменить дополнительные настройки префикса:'
	export loc_prefix_manager_wine='используя wine:'
	export loc_pm='МЕНЕДЖЕР ПРЕФИКСА'
	export loc_pm_dlls='БИБЛИОТЕКИ'
	export loc_pm_fonts='ШРИФТЫ'
	export loc_pm_settings='НАСТРОЙКИ'
	export loc_start_pfx_manager="Запускается менеджер префикса:"

	export loc_warn_cyrillic_in_path="Путь до исполняемого файла содержит кириллические символы.\nИногда это может привести к неработоспособности приложения."

	export loc_gui_terminal="ТЕРМИНАЛ"
	export loc_gui_logo="ЛОГО"


elif [[ "${update_loc}" == "ENG" ]] ; then

	export loc_gui_pw_reinstall_pp="REINSTALL PortProton"
    export loc_gui_rm_pp="REMOVE PortProton"
    export loc_gui_upd_pp="UPDATE PortProton"
    export loc_gui_changelog="CHANGELOG"
	export loc_gui_change_loc="CHANGE LANGUAGE"
    export loc_gui_edit_usc="EDIT USER.CONF"
    export loc_gui_scripts_fb="SCRIPTS FROM BACKUP"
    export loc_gui_credits="CREDITS"

	export loc_gui_clear_pfx="Clear prefix"
    export loc_gui_download_other_wine="Get other Wine"
    export loc_gui_create_pfx_backup="Create prefix backup"

    export loc_create_pfx_backup_path="BACKUP PREFIX TO..."

    export loc_gui_wine_uninstaller="Uninstaller"
    export loc_gui_wine_cfg="Prefix configuration"
    export loc_gui_wine_file="File manager"
    export loc_gui_wine_cmd="CMD"
    export loc_gui_wine_reg="Reg edit"

    export loc_tray_winefile="WINEFILE"
	export loc_tray_tascmng="TASKMNR"
	export loc_tray_cangelog="CHANGE  LOG"
	export loc_tray_force_exit="FORCE  EXIT"

    export loc_mg_autoinstall="AUTOINSTALL"
	export loc_mg_emulators="EMULATORS"
	export loc_mg_wine_settings="WINE SETTINGS"
	export loc_mg_portproton_settings="PORTPROTON SETTINGS"
	export loc_mg_installed="INSTALLED"

    export PW_CHANGELOG_FILE="changelog_eng"
	export PW_SELECTION_DB_LOC="More than one DB file found for the application being launched.\nSelect the required one, or delete the extra DB file before the next run.\n"

	export inst_set="Choices"
	export inst_set_top="Instaling PortProton"
	export sc_info="The shortcut will be created in the PortProton directory."
	export sc_name="Name"
	export sc_menu_desktop="Add shortcut to MENU -> GAMES"
	export sc_desktop_desktop="Add shortcut to Desktop"
	export sc_add_in_steam="Add shortcut to STEAM library"
	export sc_restert_steam="For adding shortcut to STEAM, needed restart.\n\nRestart STEAM now?"

	export inst_succ="The installation was successful."

	export port_upd1="New update for PortProton"
	export port_upd2="On linux-gaming.ru site published an update for PortProton\n"
	export port_upd3="Action:"
	export port_upd4="Go to the website"
	export port_upd5="Remind me later"
	export port_upd6="Do not remind me"

	export scripts_upd1="New update for scripts"
	export scripts_upd2="Scripts update avialable for PortProton"
	export scripts_upd3="EXIT"
	export scripts_upd4="UPDATING NOW"
	export scripts_upd5="REMIND ME LATER"
	export scripts_upd6="DO NOT REMIND ME"

	export port_clear_pfx="Do you want to clear prefix in PortProton?"

	export port_del1="Remove PortProton"
	export port_del2="Do you really want to remove PortProton?"

	export port_reinstall="Do you really want to reinstall PortProton?\nFor this, an internet connection will be required."

	export port_deb1="PortProton was launched in creation mode PortProton.log and it is successfully stored in the root directory of the port"
	export port_deb2="To diagnose the problem, copy ALL of the log to discord server: https://discord.gg/FTaheP99wE"

	export port_start1="Starting the PortProton"
	export port_start2="In what mode you want to start the PortProton?"
	export port_start3="Mode:"
	export port_start4="Normal"
	export port_start5="Individual X-Session"
	export port_start6="Create LOG-file"
	export port_start7="Run winetricks"
	export port_start8="DXVK"

	export port_debug="Please wait! After finishing the PortProton, click STOP."

	export loc_create_shortcut_from_gui="Create shortcut..."
	export loc_create_shortcut="Create shortcut for select file..."
	export loc_delete_shortcut="Delete shortcut for select file..."
	export loc_debug="Launch with the creation of a .log file at the root PortProton"
    export loc_launch="Run file ..."
	export loc_winecfg="Run winecfg to edit the settings of the selected prefix"
    export loc_winefile="Run wine file manager"
    export loc_winecmd="Run wine cmd"
	export loc_winereg="Run wine regedit"
	export loc_wineuninstaller="Run the program uninstaller built into wine"
    export loc_winetricks="Run winetricks to install additional libraries to the selected prefix"
	export loc_edit_db="Edit database file for"
	export loc_download_other_wine="Open the menu to download other versions of WINE-PROTON "
	export loc_downloading="Downloading"

	export loc_clear_pfx="Clear the prefix to fix problems"

	export loc_gui_dll_new_pfx="Do you want to installing recommended libraries in the new prefix:  "

	export loc_gui_portproton_lock='A running PortProton session was detected.\nDo you want to end the previous session?'

	export ENABLE_VKBASALT_INFO='Enable vkBasalt by default to improve graphics in games running on Vulkan. (The HOME hotkey disables vkbasalt)'
	export PW_NO_ESYNC_INFO='Do not use in-process synchronization primitives based on eventfd. (It is recommended not to change the value.)'
	export PW_NO_FSYNC_INFO='Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems without FUTEX_WAIT_MULTIPLE support) (It is recommended not to change the value)'
	export PW_USE_RAY_TRACING_INFO='Enable vkd3d support - Ray Tracing'
	export PW_FIX_VIDEO_IN_GAME_INFO='Required for video playback in some games so that it is not distorted (usually colored pink)'
	export PW_VULKAN_NO_ASYNC_INFO='Disable asynchronous calls for VULKAN and DXVK modes'
	export PW_USE_NVAPI_AND_DLSS_INFO='Enable DLSS on supported NVIDIA graphics cards'
	export PW_OLD_GL_STRING_INFO='Forced use of older versions of OpenGL'
	export PW_HIDE_NVIDIA_GPU_INFO='Disguise all features used for NVIDIA graphics cards'
	export PW_FORCE_USE_VSYNC_INFO='Forced activation of vertical sync'
	export PW_VIRTUAL_DESKTOP_INFO='Enable the application to run in the WINE virtual desktop'
	export PW_USE_TERMINAL_INFO='Run the application in the terminal'
	export PW_HEAP_DELAY_FREE_INFO='Include a delay in releasing some memory to bypass errors associated with using the application after the memory is released'
	export PW_NO_WRITE_WATCH_INFO='A very dangerous way to hack the memory write timer in ntdll. This improves the performance of some very specific games. (It is recommended not to change the value.)'
	export PW_GUI_DISABLED_CS_INFO='Disable the window for selecting startup modes and WINE versions'
	export PW_USE_GSTREAMER_INFO='Use Gstreamer to output clips in games (WMF support)'
	export PW_FORCE_LARGE_ADDRESS_AWARE_INFO='Increases RAM usage limits for 32-bit applications from two to four gigabytes'
	export PW_USE_RUNTIME_INFO='Use container launch mode (It is recommended not to change the value)'
	export PW_MANGOHUD_INFO='Using FPS and system load monitoring (Turns on and off by the key combination - right Shift + F12)'
	export PW_USE_GAMEMODE_INFO='Using automatic system optimization to improve performance in games (provided the gamemode package is installed on the system)'
	export PW_USE_WINE_DXGI_INFO='Forced use of built-in DXGI library (in rare cases it solves problems with DX12 games)'
	export PW_MANGOHUD_USER_CONF_INFO='Forced use of MANGOHUD system settings (GOverlay, etc.)'
	export PW_VKBASALT_USER_CONF_INFO='Forced use of VKBASALT system settings (GOverlay, etc.)'
	export PW_USE_D3D_EXTRAS_INFO='Enable forced use of third-party DirectX libraries'
	export PW_USE_WINDOWS_7_INFO='Change the version of WINDOWS 10 to WINDOWS 7 in the prefix'
	export PW_USE_SHADER_CACHE_INFO='Use WINE shader caching (disable only if there are microfreezes in the game)'
	export PW_WINE_FULLSCREEN_FSR_INFO='Works while using any version of ProtonGE in full screen mode at a resolution below the standard screen'
	export PW_USE_FAKE_DLSS_INFO='Enable DLSS translator in FSR 2 in DirectX 12 games (CyberFSR2)'
	export PW_USE_FAKE_DLSS_3_INFO='Enable DLSS translator in FSR 3 in DirectX 12 games (Experimental project dlssg-to-fsr3)'
	export PW_USE_EAC_AND_BE_INFO='Enable Easy Anti-Cheat and BattlEye Anti-Cheat runtimes (required if game used this anti-cheats)'
	export PW_REDUCE_PULSE_LATENCY_INFO='Reduce pulseaudio latency to fix intermittent sound'
	export PW_USE_US_LAYOUT_INFO='Forced use of the us layout (useful for games in which the control works correctly only on the us layout)'
	export PW_RESTORE_RESOLUTION_INFO='Remember the screen resolution when starting the game and return it when closing (useful for games that change the screen resolution when closing)'
	export PW_USE_SYSTEM_VK_LAYERS_INFO='Use system mangohud, vkBasalt, obs-vkcapture and other applications using vulkan layers'
	export PW_USE_OBS_VKCAPTURE_INFO='Enable the ability to write to OBS Studio using obs-vkcapture (ATTENTION: the forced use of system mangohud, vkBasalt, obs-vkcapture and other applications using vulkan layers will be enabled)'
	export PW_USE_GALLIUM_ZINK_INFO='Use the zink driver (OpenGL on top of Vulkan), allows you to use vkBasalt in OpenGL games (ATTENTION: vulkan support is required, wined3d (opengl) is used instead of dxvk, suitable for games on OpenGL and older versions of DirectX, artifacts are possible on newer versions of DirectX)'
	export PW_DISABLE_COMPOSITING_INFO='Disable desktop compositing (effects). It often improves performance.'

    export PW_3DFX_INFO='Simulation of an old 3dfx graphics accelerator (adds horizontal stripes)'
   	export PW_AdaptiveSharpen_INFO='Sharpness increase, can be used with CAS'
   	export PW_Bloom_INFO='Adds glow from bright light sources in the game'
   	export PW_Border_INFO='Cropping the image from the top and bottom (like in a movie =)'
   	export PW_Cartoon_INFO='Strong sharpening of texture edges'
   	export PW_ChromaticAberration_INFO='Adds chromatic aberration to an image'
   	export PW_Clarity_INFO='Sharpening textures with slight modifications of image contrast (similar in effect to CAS)'
   	export PW_ColorMatrix_INFO='Adding cool colors'
   	export PW_Colourfulness_INFO='Increasing color saturationIncreasing color saturation'
   	export PW_FakeHDR_INFO='Add fake HDR'
   	export PW_FilmGrain2_INFO='Adding the film grain effect'
   	export PW_Curves_INFO='Increases the contrast of the image without affecting the bright and dark areas, so that the detail in shadows and sky is not lost'
   	export PW_Denoise_INFO='Reducing noise by blurring the image'
   	export PW_Emphasize_INFO='Reducing the bit depth of color'
   	export PW_FakeMotionBlur_INFO='Strong blurring of objects in motion'
   	export PW_FilmicAnamorphSharpen_INFO='Sharpening (recommended for cartoon games)'
   	export PW_FilmicPass_INFO='Adding cold colors'
   	export PW_SMAA_INFO='Alternative antialiasing option (less effect, but with less consumption of GPU resources, relative to the standard SMAA)'
   	export PW_GaussianBlur_INFO='Slight blur effect on bright objects (such as flames)'
    export PW_Glitch_INFO='Glitch effect'
    export PW_HighPassSharpen_INFO='Another method of sharpening using highpass frequencies'
    export PW_HQ4X_INFO='Smoothing of nearby pixels with the drawing of missing parts (in normal games the picture is blurred)'
    export PW_HSLShift_INFO='Advanced HSL shift (for each shade)'
    export PW_Layer_INFO="Image overlay on the game (the image is in the $PORT_WINE_TMP_PATH/libs_v$PW_LIBS_VER/pressure-vessel/reshade/textures folder)"
    export PW_Levels_INFO='Increases contrast, but some detail in shadows or highlights may be lost'
    export PW_LevelsPlus_INFO='Same as Levels, but with less loss of detail'
    export PW_LiftGammaGain_INFO='Gamma correction by individual color channels: red, green and blue'
    export PW_LightDoF_INFO='Increases depth of field (greatly affects FPS)'
    export PW_LumaSharpen_INFO='Enhances image sharpness for improved detail'
    export PW_LUT_INFO='Image color correction'
    export PW_MagicBloom_INFO='Same as Bloom, but more natural'
    export PW_Monochrome_INFO='Converts the image into monochrome'
    export PW_MultiLUT_INFO='Extended version of the LUT (Hollywood loot is pre-installed)'
    export PW_MXAO_INFO='SSAO algorithm (Greatly affects FPS)'
    export PW_NightVision_INFO='Night vision effect'
    export PW_Nostalgia_INFO='Makes the picture look like old photos'
    export PW_PerfectPerspective_INFO='Fisheye effect (suitable for VR)'
    export PW_PPFX_Godrays_INFO='Add God rays (also called 3D light rays) effect'
    export PW_Prism_INFO='The prismatic lens effect'
    export PW_ReflectiveBumpMapping_INFO='Creates the illusion of depth in textures'
    export PW_Sepia_INFO='Adds a sepia effect like in old photos'
    export PW_Splitscreen_INFO='Splits the image into raw and processed output for comparison'
    export PW_SurfaceBlur_INFO='Reducing object detail without blurring contrast contours'
    export PW_Technicolor_INFO='Makes the picture look like films from the 1930s'
    export PW_Technicolor2_INFO='The updated version of Technicolor, gives a different picture by changing colors more aggressively'
    export PW_TiltShift_INFO='Blur on the edges of the screen to create a Tilt Shift effect'
    export PW_Tonemap_INFO='Changes the saturation of the picture'
    export PW_TriDither_INFO='Reduces the amount of noise'
    export PW_UIDetect_INFO='Automatically switches effects depending on the visibility of the UI'
    export PW_Vibrance_INFO='Saturates faded colors without touching the bright ones'
    export PW_Vignette_INFO='Adds a vignette to the image'
    export PW_AspectRatio_INFO='An effect for adjusting the aspect ratio (for games that do not support widescreen monitors)'
    export PW_UIMask_INFO='Part of the overall ReShade shader . It uses a mask with gradients from black to white to determine where the effects will be applied'
    export PW_StageDepth_INFO='Allows you to add new elements to the 3d space inside the game and apply custom textures'
    export PW_PPFX_Bloom_INFO='Adds a Bloom effect'

    export ENABLE_MANGOHUD_INFO='Включите MangoHud по умолчанию (горячие клавиши R_SHIFT + F12 отключают MangoHud)'
	export PW_MH_arch_INFO='Show if the application is 32- or 64-bit'
	export PW_MH_battery_INFO='Display current battery percent and energy consumption'
	export PW_MH_battery_icon_INFO='Display battery icon instead of percent'
	export PW_MH_battery_time_INFO='Display remaining time for battery option'
	export PW_MH_battery_watt_INFO='Display wattage for the battery option'
	export PW_MH_core_bars_INFO='Change the display of core_load from numbers to vertical bars'
	export PW_MH_core_load_INFO='Display load & frequency per core'
	export PW_MH_cpu_mhz_INFO='Show the CPUs current MHz'
	export PW_MH_cpu_power_INFO='Display CPU draw in watts'
	export PW_MH_cpu_temp_INFO='Display current CPU temperature'
	export PW_MH_device_battery_icon_INFO='Display wirless device battery icon.'
	export PW_MH_engine_short_names_INFO='Display a short version of the used engine (e.g. OGL instead of OpenGL)'
	export PW_MH_engine_version_INFO='Display OpenGL or vulkan and vulkan-based render engines version'
	export PW_MH_exec_name_INFO='Display current exec name'
	export PW_MH_fcat_INFO='Enables frame capture analysis'
	export PW_MH_fps_metrics_INFO='Takes a list of decimal values or the value avg, e.g avg,0.001'
	export PW_MH_frame_count_INFO='Display frame count'
	export PW_MH_full_INFO='Enable most of the toggleable parameters (currently excludes histogram)'
	export PW_MH_gamemode_INFO='Show if GameMode is on'
	export PW_MH_gpu_core_clock_INFO='Display GPU core frequency'
	export PW_MH_gpu_fan_INFO='GPU fan in rpm on AMD, FAN in percent on NVIDIA'
	export PW_MH_gpu_junction_temp_INFO='Display current GPU temperature'
	export PW_MH_gpu_mem_clock_INFO='Display GPU memory frequency'
	export PW_MH_gpu_mem_temp_INFO='Display current GPU temperature'
	export PW_MH_gpu_name_INFO='Display GPU name from pci.ids'
	export PW_MH_gpu_power_INFO='Display GPU draw in watts'
	export PW_MH_gpu_temp_INFO='Display current GPU temperature'
	export PW_MH_gpu_voltage_INFO='Display GPU voltage (only works on AMD GPUs)'
	export PW_MH_histogram_INFO='Change FPS graph to histogram'
	export PW_MH_horizontal_INFO='Display Mangohud in a horizontal position'
	export PW_MH_horizontal_stretch_INFO='Stretches the background to the screens width in horizontal mode'
	export PW_MH_hud_compact_INFO='Display compact version of MangoHud'
	export PW_MH_hud_no_margin_INFO='Remove margins around MangoHud'
	export PW_MH_io_read_INFO='Show non-cached IO read, in MiB/s'
	export PW_MH_io_write_INFO='Show non-cached IO write, in MiB/s'
	export PW_MH_no_display_INFO='Hide the HUD by default'
	export PW_MH_no_small_font_INFO='Use primary font size for smaller text like units'
	export PW_MH_procmem_INFO='Displays process memory usage: resident procmem (resident) also toggles others off if disabled'
	export PW_MH_procmem_shared_INFO='Displays process memory usage: shared'
	export PW_MH_procmem_virt_INFO='Displays process memory usage: virtual'
	export PW_MH_ram_INFO='Display system RAM usage'
	export PW_MH_resolution_INFO='Display the current resolution'
	export PW_MH_show_fps_limit_INFO='Display the current FPS limit'
	export PW_MH_swap_INFO='Display swap space usage next to system RAM usage'
	export PW_MH_temp_fahrenheit_INFO='Show temperature in Fahrenheit'
	export PW_MH_throttling_status_INFO='Show if GPU is throttling based on Power, current, temp or "other" (Only shows if throttling is currently happening). Currently disabled by default for Nvidia as it causes lag on 3000 series'
	export PW_MH_throttling_status_graph_INFO='Same as throttling_status but displays throttling in the frametime graph and only power and temp throttling'
	export PW_MH_time_INFO='Display local time'
	export PW_MH_version_INFO='Show current MangoHud version'
	export PW_MH_vkbasalt_INFO='Show if vkBasalt is on'
	export PW_MH_vram_INFO='Display system VRAM usage'
	export PW_MH_vulkan_driver_INFO='Display used Vulkan driver (radv/amdgpu-pro/amdvlk)'
	export PW_MH_frametime='Display frametime next to FPS text'
	export PW_MH_wine_INFO='Show current Wine or Proton version in use'

	export PW_PFX_BACKUP_INFO="Attention! Do not pass the resev copy to third parties, there is a risk of losing accounts"
	export PW_PFX_BACKUP_SUCCESS="Backup has been successfully created for prefix:"
	export PW_PFX_BACKUP_ERROR="An error occurred while backing up the prefix:"

	export loc_find_d3dadapter9_error="Not found in the system.\nInstall the missing package: d3dadapter9"

	export loc_gui_create_shortcut_for_exe="Choose the .exe file for which you need to create a shortcut and click OK.\n"

	export loc_gui_error='Error.'
	export loc_gui_error_download="You will need to check internet connection,and\npress Repeat for repeat download"
	export loc_gui_settings="Please wait."
	export loc_gui_sett_info="Updating configuration for <b>PortProton</b>..."
	export loc_gui_edit_db="Change settings in database file for"
	export loc_gui_edit_db_help="<b>NOTE:</b> To display help for each item, simply hover your mouse over the text"

	export loc_cancel="CANCEL"
	export loc_gui_cancel="CANCEL THE CHANGES"
	export loc_gui_cancel_help="Cancel the current changes and return to the previous menu."


	export loc_gui_reset_db="RESET SETTINGS"
	export loc_gui_reset_db_help="Restore default settings."

	export loc_disabled="Disabled"
	export loc_skip="SKIP"
	export loc_repeat="REPEAT"

	export loc_gui_open_db="OPEN THE SETTINGS FILE"
	export loc_gui_open_db_help="Open the <b>.ppdb</b> settings file in a system text editor to view and change variables manually."

	export loc_gui_save_changes="SAVE CHANGES"
	export loc_gui_save_changes_help="Save the current changes, and go to the previous menu."

	export loc_gui_ver_windows="Change the version of <b>WINDOWS</b> emulation"
	export loc_gui_ver_windows_help="Changing the <b>WINDOWS</b> emulation version may be required to run older games. <b>WINDOWS</b> versions below 10 do not support new games with DirectX 12"


	export loc_gui_aut_winetricks="AUTOINSTALL WITH <b>WINETRICKS</b>"
	export loc_gui_aut_winetricks_help="Automatically install with <b>WINETRICKS</b> additional libraries required to run the game/program. List of libraries separated by spaces"

	export loc_gui_winedllover="Forced to use/disable libraries"
	export loc_gui_winedllover_help="Forced to use/disable the library only for the given application. (There are examples in the drop-down list)

A brief instruction:
	* libraries are written <b>WITHOUT</b> the .dll file extension
	* libraries are separated by semicolons - <b>;</b>
	* library=n - use the <b>WINDOWS</b> (third-party) library
	* library=b - use <b>WINE</b> (built-in) library
	* library=n,b - use <b>WINDOWS</b> library and then <b>WINE</b>
	* library=b,n - use <b>WINE</b> library and then <b>WINDOWS</b>
	* library= - disable the use of this library"

	export loc_gui_arg_exe="ADD ARGUMENTS FOR .EXE FILE"
	export loc_gui_arg_exe_help="Adding an argument after the <b>.exe</b> file, just like you would add an argument in a shortcut on a <b>WINDOWS </b> system"

    export loc_gui_mango_fps="MANGOHUD FPS LIMIT"
	export loc_gui_mango_fps_help="Enabling FPS limits using MANGOHUD built into PortProton"

	export loc_gui_arg_gamescope="Add arguments for GAMESCOPE:"
	export loc_gui_arg_gamescope_help="
<b>-W, -H:</b> set the resolution used by gamescope. Resizing the gamescope window will update these settings. Ignored in embedded mode. If -H is specified but -W isn't, a 16:9 aspect ratio is assumed. Defaults to 1280×720.
<b>-w, -h:</b> set the resolution used by the game. If -h is specified but -w isn't, a 16:9 aspect ratio is assumed. Defaults to the values specified in -W and -H.
<b>-r:</b> set a frame-rate limit for the game. Specified in frames per second. Defaults to unlimited.
<b>-o:</b> set a frame-rate limit for the game when unfocused. Specified in frames per second. Defaults to unlimited.
<b>-F fsr:</b> use AMD FidelityFX™ Super Resolution 1.0 for upscaling.
<b>-F nis:</b> use NVIDIA Image Scaling v1.0.3 for upscaling.
<b>-S integer:</b> use integer scaling.
<b>-S stretch:</b> use stretch scaling, the game will fill the window. (e.g. 4:3 to 16:9).
<b>-b:</b> create a border-less window.
<b>-f:</b> create a full-screen window."

	export PW_USE_GAMESCOPE_INFO="
<b>Super + F :</b> Toggle fullscreen
<b>Super + N :</b> Toggle nearest neighbour filtering
<b>Super + U :</b> Toggle FSR upscaling
<b>Super + Y :</b> Toggle NIS upscaling
<b>Super + I :</b> Increase FSR sharpness by 1
<b>Super + O :</b> Decrease FSR sharpness by 1
<b>Super + S :</b> Take screenshot (currently goes to /tmp/gamescope_DATE.png)
<b>Super + G :</b> Toggle keyboard grab
<b>Super + C :</b> Update clipboard"

	export loc_gui_cpu_limit="Limit the use of processor cores"
	export loc_gui_cpu_limit_help="Limiting the number of CPU cores is useful for Unity games (It is recommended to set the value equal to 8)"

	export loc_gui_amd_vulkan_select="Select needed AMD vulkan implementation"
	export loc_gui_amd_vulkan_select_help="Choosing which implementation of vulkan will be used to run the game"

	export loc_gui_gpu_select="Choose a graphics card to run the game (in user.conf)"
	export loc_gui_gpu_select_help="Select which video card will be used to run the game (used for all running games and programs in PortProton)"

	export loc_gui_check_new_wine="Check new version WINE"
	export loc_gui_check_new_wine_error="Error: check wine."
	export loc_gui_set_new_wine="Select WINE for download:"
	export loc_gui_del_wine="Select installed WINE for delete:"
	export loc_gui_installed_wine="INSTALLED"

	export loc_gui_ffx_cas="AMD FidelityFX - CAS is designed to dramatically improve texture sharpness without additional modification settings for games, with minimal loss of performance. (For older games it is recommended to set value = 100)"
	export loc_gui_disabled_vkbas="DISABLE VKBASALT"
	export loc_gui_disabled_vkbas_help="Disable vkBasalt and go to the previous menu."

	export loc_gui_disabled_mh="DISABLE MANGOHUD"
	export loc_gui_disabled_mh_help="Disable MangoHud and go to the previous menu."
	export loc_gui_mh_top="MangoHud settings (Keys <b>R_SHIFT + F12</b> disable MangoHud)\n<b>note:</b> To display help for each item, just hover the mouse cursor over the text.\n"

	export loc_gui_no="NO"
	export loc_gui_yes="YES"

	export loc_gui_missing_shortcut="\nCould not find the file:\n${portwine_exe}\n\nATTENTION:\nIf you forgot to mount the disk with the running application, click CANCEL!"
	export loc_gui_create_shortcut="CREATE SHORTCUT"
	export loc_gui_delete_shortcut="DELETE SHORTCUT"
	export loc_gui_launch="LAUNCH"
	export loc_gui_debug="DEBUG"
	export loc_gui_edit_db_start="EDIT  DB"
	export loc_gui_vkbasalt_start="VKBASALT"
	export loc_gui_mh_start="MangoHud"

    export loc_gui_vkbasalt_top="vkBasalt settings for adding effects to games running under Vulkan. (The <b>HOME</b> key disables vkbasalt)\n<b>NOTE:</b> To display help for each item, simply hover over the text\n"

	export loc_gui_db_comments="PortProton database file was found for"

	export loc_gui_vulkan_stable="Stable DXVK ${DXVK_STABLE_VER} и VKD3D ${VKD3D_STABLE_VER}"
	export loc_gui_vulkan_git="Newest DXVK ${DXVK_GIT_VER} и VKD3D ${VKD3D_GIT_VER}"
	export loc_gui_gallium_nine="GALLIUM_NINE (DX9 for MESA)"
	export loc_gui_open_gl="OPENGL (For video cards without VULKAN)"

	export loc_gui_installing_the="Installing the"
	export loc_gui_please_wait="Please wait..."

	export loc_dolphin="Emulator for Nintendo game consoles with high compatibility"
	export loc_mame="Multi-arcade emulator that allows you to play old arcade games"
	export loc_scummvm="Emulator for classic adventure games from LucasArts and other studios"
	export loc_retroarch="Multi-platform frontend for emulators with extensive settings"
	export loc_ppsspp_windows="Windows - Emulator for the PlayStation Portable (PSP) game console"
	export loc_citra="Emulator for the Nintendo 3DS game console"
	export loc_cemu="Emulator for the Wii U game console"
	export loc_duckstation="Emulator for the PlayStation 1 game console"
	export loc_epsxe="Emulator for the PlayStation 1 game console with high compatibility"
	export loc_project64="Emulator for the Nintendo 64 game console"
	export loc_vba_m="Emulator for the Game Boy Advance game console"
	export loc_yabause="Emulator for the Sega Saturn game console"
	export loc_xenia="Emulator for the Xbox 360 game console"
	export loc_fceux="Emulator for the Nintendo Entertainment System (NES or Dendy) game console"
	export loc_xemu="Emulator for the Xbox game console"
	export loc_demul="Emulator for the Sega Dreamcast game console"
	export loc_rpcs3="Emulator for the PlayStation 3 game console"

	export loc_prefix_manager_comp='Select components to install in prefix:'
	export loc_prefix_manager_font='Select fonts to install in prefix:'
	export loc_prefix_manager_conf='Change config for prefix:'
	export loc_prefix_manager_wine='using wine:'
	export loc_pm='PREFIX MANAGER'
	export loc_pm_dlls='DLLS'
	export loc_pm_fonts='FONTS'
	export loc_pm_settings='SETTINGS'
	export loc_start_pfx_manager="Starting prefix manager:"

	export loc_warn_cyrillic_in_path="The path to the executable file contains Cyrillic characters.\nSometimes this can cause the application to malfunction."

	export loc_gui_terminal="TERMINAL"
	export loc_gui_logo="LOGO"

fi
