#!/bin/bash
# Author: PortWINE-Linux.ru

read "update_loc" < "${PORT_WINE_TMP_PATH}/${portname}_loc"
export update_loc=${update_loc}

if [ "${update_loc}" = "RUS" ]
then
	export PW_CHANGELOG_FILE="changelog_rus"
	export PW_SELECTION_DB_LOC="Найдено более одного DB файла для запускаемого приложения.\nВыберите необходимый, или перед следующим слезапуском удалите лишний DB файл.\n"

	export inst_set="Выбор"
	export inst_set_top="Установка PortWINE"
	export ss_done="Ярлык создан в корневом каталоге порта.\nДобавить его в МЕНЮ -> ИГРЫ?"

	export inst_succ="Установка завершена успешно!"

	export port_upd1="Обновление PortWINE"
	export port_upd2="На сайте portwine-linux.ru вышло обновление для ${portname}\n"
	export port_upd3="Действие:"
	export port_upd4="Перейти на сайт"
	export port_upd5="Напомнить позже"
	export port_upd6="Больше не напоминать"

	export scripts_upd1="Обновление скриптов"
	export scripts_upd2="Доступно обновление скриптов для ${portname}\n"
	export scripts_upd3="Действие:"
	export scripts_upd4="Обновить сейчас"
	export scripts_upd5="Напомнить позже"
	export scripts_upd6="Больше не напоминать"

	export port_clear_pfx="Вы действительно хотите очистить префикс PortProton?"

	export port_del1="Удаление $portname"
	export port_del2="Вы действительно хотите полностью удалить PortProton?"

	export port_deb1="PortWINE был запущен в режиме создания ${portname}.log и он успешно сохранен в корне каталога порта"
	export port_deb2="Для диагностики проблемы, скопируйте ВЕСЬ лог в соответствующий канал у нас на сервере дискорда: https://discord.gg/FTaheP99wE"

	export port_start1="Запуск PortWINE"
	export port_start2="В каком режиме вы хотите запустить PortWINE?"
	export port_start3="Режим:"
	export port_start4="Обычный"
	export port_start5="Отдельной X-сессии"
	export port_start6="Создать ЛОГ-файл"
	export port_start7="Запустить winetricks"
	export port_start8="DXVK"

	export port_debug="Не торопитесь!\nПосле окончания работы ${portname}, нажмите ОК."

	export loc_creat_shortcut="Создать ярлык для запускаемого файла."
	export loc_debug="Запуск c созданием .log файла в корне ${portname}"
	export loc_launch="Запустить файл..."
	export loc_winecfg="Запустить winecfg для редактирования настроек префикса ${portname}"
	export loc_winefile="Запустить файловый менеждер встроенный в wine"
    export loc_winecmd="Запустить командную строку wine"
	export loc_winereg="Запустить редактор реестра префикса ${portname}"
    export loc_winetricks="Запустить winetricks для установки доп. библиотек в префикс ${portname}"
	export loc_edit_db="Изменить файл настроек для"

	export ENABLE_VKBASALT_INFO='Включить vkBasalt по умолчанию для улучшение графики в играх работающих под Vulkan. (Горячая клавиша HOME отключает vkbasalt)'
	export PW_NO_ESYNC_INFO='Не использовать примитивы внутрипроцессной синхронизации на основе eventfd. (Рекомендуется не изменять значение)'
	export PW_NO_FSYNC_INFO='Не использовать примитивы внутрипроцессной синхронизации на основе фьютексов. (Автоматически отключается в системах без FUTEX_WAIT_MULTIPLE поддержки) (Рекомендуется не изменять значение)'
	export PW_USE_DXR10_INFO='Включить поддержку Ray Tracing v.1.0'
	export PW_USE_DXR11_INFO='Включить поддержку Ray Tracing v.1.1 (бета)'
	export PW_VULKAN_NO_ASYNC_INFO='Выключить асинхронные вызовы для режимов VULKAN и DXVK'
	export PW_USE_NVAPI_AND_DLSS_INFO='Включить DLSS на поддерживаемых видеокартах NVIDIA'
	export PW_OLD_GL_STRING_INFO='Принудительное использование старых версий OpenGL'
	export PW_HIDE_NVIDIA_GPU_INFO='Замаскировать все функции используемые для видеокарт NVIDIA'
	export PW_FORCE_USE_VSYNC_INFO='Принудительное включение вертикальной синхронизации'
	export PW_VIRTUAL_DESKTOP_INFO='Включить запуск приложение в виртуальном рабочем столе WINE'
	export PW_WINEDBG_DISABLE_INFO='Отключить все функции отладки WINE (Рекомендуется не изменять значение)'
	export PW_USE_TERMINAL_INFO='Запускать приложение в терминале'
    export PW_WINE_ALLOW_XIM_INFO='Использовать альтернативный режим для контроллера (Использовать только в случае проблем с контроллером)'
	export PW_HEAP_DELAY_FREE_INFO='Включить задержку освобождения некоторой памяти, чтобы обойти ошибки, связанные с использованием приложения после освобождения памяти.'
	export PW_NO_WRITE_WATCH_INFO='Очень опасный способ взлома таймера записи в памяти в ntdll. Это улучшает производительность некоторых очень специфических игр. (Рекомендуется не изменять значение)'
	export PW_GUI_DISABLED_CS_INFO='Отключить окно выбора режимов запуска и версии WINE'
	export PW_USE_GSTREAMER_INFO='Использовать Gstreamer для вывода роликов в играх (поддержка WMF)'
	export PW_USE_RUNTIME_INFO='Использовать контейнерный режим запуска (Рекомендуется не изменять значение)'
	export PW_MANGOHUD_INFO='Использование мониторинга FPS и нагрузки системы (Включается и выключается сочитанием клавиш - правый Shift + F12)'
	export PW_USE_GAMEMODE_INFO='Использование автоматической оптимизации системы для увеличения производительности в играх (при условии установленного пакета gamemode в системе)'
	export PW_DX12_DISABLE_INFO='Принудительное отключение DirectX 12'
	export PW_USE_WINE_DXGI_INFO='Принудительное использование встроенной библиотеки DXGI (в редких случаях решает проблемы с запуском игр под DX12)'
	export PW_MANGOHUD_USER_CONF_INFO='Принудительное использование системных настроек MANGOHUD (GOverlay и т.п.)'

	export PW_3DFX_INFO='Имитация старого графического ускорителя 3dfx (добавляет горизонтальные полосы)'
	export PW_AdaptiveSharpen_INFO='Увеличение резкости, можно использовать совместо с CAS'
	export PW_Bloom_INFO='Добавляет свечения от ярких источников света в игре'
	export PW_Border_INFO='Обрезка изображения сверху и снизу (как в кино =)'
	export PW_Cartoon_INFO='Сильное увеличение резкости краев тексур'
	export PW_ChromaticAberration_INFO='Добавляет хроматические аберрации к изображению'
	export PW_Clarity_INFO='Увеличение резкости текстур с небольшими модификациями контраста изображения (похож по эффекту на CAS)'
	export PW_ColorMatrix_INFO='Добавление холодных цветов'
	export PW_Colourfulness_INFO='Увеличение насыщености цветов'
	export PW_FakeHDR_INFO='Расширение динамического диапазона цветов'
	export PW_FilmGrain2_INFO='Добавление эффекта зерна кинопленки'
	export PW_Curves_INFO='Увеличение контраста изображения'
	export PW_Denoise_INFO='Уменьшение шумов за счет смазывания изображения'
	export PW_Emphasize_INFO='Уменьшение рязрядности цветопередачи'
	export PW_FakeMotionBlur_INFO='Сильное размытие объектов в движении'
	export PW_FilmicAnamorphSharpen_INFO='Увеличение резкости (рекомендую для мультяшных игр)'
	export PW_FilmicPass_INFO='Добавление холодных цветов'
	export PW_SMAA_INFO='Альтернативный вариант сглаживания (меньший эффект, но с меньшим потреблением ресурсов GPU, относительно стандартного SMAA)'
	export PW_GaussianBlur_INFO='Небольшой эффект размытия ярких обьектов (например пламя)'

	export PW_WAYLAND_INFO="Внимание! Вы запускаете $portname в сессии Wayland, некоторые функции могут быть недоступны!\nРекомендуется перезапустить сессию в X11!"

elif [ "${update_loc}" = "ENG" ]
then
	export PW_CHANGELOG_FILE="changelog_eng"
	export PW_SELECTION_DB_LOC="More than one DB file found for the application being launched.\nSelect the required one, or delete the extra DB file before the next run.\n"

	export inst_set="Sett..."
	export inst_set_top="PortWINE setting"
	export ss_done="The shortcut was created in the ${portname} directory.\nAdd it to MENU -> GAMES?"
	export inst_succ="The installation was successful."

	export port_upd1="New update PortWINE"
	export port_upd2="On portwine-linux.ru site published an update to the ${portname}\n"
	export port_upd3="Action:"
	export port_upd4="Go to the website"
	export port_upd5="Remind me later"
	export port_upd6="Do not remind me"

	export scripts_upd1="New update for scripts"
	export scripts_upd2="Scripts update avialable for ${portname}\n"
	export scripts_upd3="Action:"
	export scripts_upd4="Updating now"
	export scripts_upd5="Remind me later"
	export scripts_upd6="Do not remind me"

	export port_clear_pfx="Do you want to clear prefix in PortProton?"

	export port_del1="Remove $portname"
	export port_del2="Are you sure you want to delete the PortProton"
	export port_deb1="PortWINE was launched in creation mode ${portname}.log and it is successfully stored in the root directory of the port"

	export port_deb2="To diagnose the problem, copy ALL of the log to discord server: https://discord.gg/FTaheP99wE"

	export port_start1="Starting the PortWINE"
	export port_start2="In what mode you want to start the PortWINE?"
	export port_start3="Mode:"
	export port_start4="Normal"
	export port_start5="Individual X-Session"
	export port_start6="Create LOG-file"
	export port_start7="Run winetricks"
	export port_start8="DXVK"

	export port_debug="Please wait!\nAfter finishing the ${portname}, click OK."
	
	export PW_WAYLAND_INFO="Attention! You are running $portname in a Wayland session, some features may not be available!\nRestarting your session in X11 is recommended!"

	#Helped in translation: ConTI1NuEsZZZ
	export loc_creat_shortcut="Create shortcut for select file..."
	export loc_debug="Launch with the creation of a .log file at the root ${portname}"
    export loc_launch="Run file ..."
    export loc_winecfg="Run winecfg to edit prefix settings ${portname}"
    export loc_winefile="Run the file manager built into wine"
    export loc_winecmd="Run wine command line"
    export loc_winereg="Run Registry Prefix Editor ${portname}"
    export loc_winetricks="Run winetricks to install additional libraries to the prefix ${portname}"
	export loc_edit_db="Edit database file for"
fi
