#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
KILL_PORTWINE
if [ -e "${PORT_WINE_TMP_PATH}/pw_vulkan" ]; then
    rm -f "${PORT_WINE_TMP_PATH}/pw_vulkan"
fi
START_PORTWINE
STOP_PORTWINE | sszen
