#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
"${WINESERVER}" -k
wine_pids=$(ls -l /proc/*/exe 2>/dev/null | grep -E 'wine(64)?-preloader|wineserver' | perl -pe 's;^.*/proc/(\d+)/exe.*$;$1;g;')
if ! [ -z "${wine_pids}" ] ; then
    kill -9 ${wine_pids}
fi
if [ -e "${config_path}/dxvk_on" ]; then
    rm -f "${config_path}/dxvk_on"
fi
START_PORTWINE
STOP_PORTWINE | pwzen
