#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
"${WINESERVER}" -k
START_PORTWINE
if [ ! -z "$1" ]; then
    if [ ! -z ${optirun_on} ]; then
        ${optirun_on} "${port_on_run}" "run" "$1"
    else
        "${port_on_run}" "run" "$1"
    fi
else  
    if [ ! -z ${optirun_on} ]; then
        ${optirun_on} "${port_on_run}" "run" "${gamestart}" ${launch_parameters} 
    else
        "${port_on_run}" "run" "${gamestart}" ${launch_parameters}
    fi
fi
STOP_PORTWINE
