#!/bin/bash
#Author: Castro-Fidel (PortWINE-Linux.ru)
#SCRIPTS_NEXT_VERSION=2008
########################################################################
export PW_MANGOHUD=1
export MANGOHUD_CONFIG=font_size=24,position=top-left,toggle_hud=Shift_R+F12,no_display,resolution,wine,gpu_name,vulkan_driver,gpu_stats,vkbasalt
#export DXVK_HUD=fps,devinfo
#export ENABLE_VKBASALT=1
#export PW_VIRTUAL_DESKTOP=1

#export PW_XKBD_RU_HACK=1
export PW_USE_RUNTIME=1     # 0 - disabled; 1 - enabled
export PW_RT_MOUNT_RO=("${HOME}/.PortWINE")
export PW_RT_MOUNT_RW=("/media" "/mnt" "/run/media/${USER}" "${PORT_WINE_PATH}")
#export PW_SANDBOX_HOME_PATH="${PORT_WINE_PATH}"

export PW_NO_ESYNC=1
export PW_USE_GAMEMODE=1
export PW_FORCE_USE_VSYNC=2
export PW_LOG=0
export PW_TERM=""
export PW_USE_TERMINAL=0
export PW_MUST_HAVE_DLL="mfc42 vcrun2019 d3dcompiler_42 d3dcompiler_43 d3dcompiler_47 d3dx9"
export PW_WINEDBG_DISABLE=1
export PW_WINDOWS_VER="10"
export WINEARCH="win64"
export PW_LIBS_VER="_v17"
export PORTWINE_URL="http://portwine-linux.ru/"
export GDK_BACKEND="x11"

export PW_PROTON_GE_VER="6.16-GE-1"
export PW_MONO_VER="6.3.0"
export PW_GECKO_VER="2.47.2"
export WINEPREFIX="${PORT_WINE_PATH}/data/pfx"
export WINE_WIN_START="start.exe /i /unix"
export WINE_FULLSCREEN_FSR="1"
export WINE_FULLSCREEN_FSR_STRENGTH="2"

#################################################################
add_in_start_portwine ()
{
echo " "
}
########################################################################
add_in_stop_portwine ()
{
echo " "
}
########################################################################
pw_other_fixes () {
    #fix after installation Origin, for disabled OriginWebHelperService by default
    if [ ! -z `cat "${WINEPREFIX}/system.reg" | grep Origin.exe | head -n 1 | awk '{print $1}'` ] ; then
        sysreg_norig=$(((`cat -n "${WINEPREFIX}/system.reg" | grep OriginWebHelperService | awk '{print $1}'` + 3)))
        sed -i "${sysreg_norig}s/dword:0000000[1-2]/dword:00000003/" "${WINEPREFIX}/system.reg"
    fi
}
###FOR_OLD_VERSION_PORTPROTON###
#SCRIPTS_VERSION=1000
