#!/bin/bash
#Author: Castro-Fidel (PortWINE-Linux.ru)
#SCRIPTS_NEXT_VERSION=2054
#PORT_NEXT_VERSION=97
########################################################################
export PW_MANGOHUD=1
export MANGOHUD_CONFIG=font_size=24,position=top-left,toggle_hud=Shift_R+F12,no_display,resolution,wine,gpu_name,vulkan_driver,gpu_stats,vkbasalt
#export DXVK_HUD=fps,devinfo
#export ENABLE_VKBASALT=1
#export PW_VIRTUAL_DESKTOP=1

#export PW_XKBD_RU_HACK=1
export PW_USE_RUNTIME=1     # 0 - disabled; 1 - enabled
export PW_RT_MOUNT_RO=("")
export PW_RT_MOUNT_RW=("/media" "/mnt" "/run/media/${USER}" "${PORT_WINE_PATH}")
#export PW_SANDBOX_HOME_PATH="${PORT_WINE_PATH}"

export PW_NO_ESYNC=1
export PW_USE_GAMEMODE=1
export PW_FORCE_USE_VSYNC=2
export PW_LOG=0
export PW_TERM=""
export PW_USE_TERMINAL=0
export PW_MUST_HAVE_DLL="physx mfc42 vcrun2019"
export PW_WINEDBG_DISABLE=1
export PW_WINDOWS_VER="10"
export WINEARCH="win64"
export PW_LIBS_VER="_v19.2"
export PORTWINE_URL="http://portwine-linux.ru/"
export GDK_BACKEND="x11"
export PW_USE_GSTREAMER="1"
export WINEPREFIX="${PORT_WINE_PATH}/data/pfx"
export WINE_WIN_START="start.exe /i /unix"
###DEFAULT_WINE###
export PW_WINE_USE=PROTON_STEAM
export PW_PLUGINS_VER="_v1"
###WINE_PROTON_STEAM###
export PW_STEAM_VER="6.3-7"
export PW_PROTON_STEAM_VER="PROTON_STEAM_${PW_STEAM_VER}"
###WINE_PROTON_GE###
export PW_GE_VER="6.19-5"
export PW_PROTON_GE_VER="PROTON_GE_${PW_GE_VER}"
export WINE_FULLSCREEN_FSR="1"
export WINE_FULLSCREEN_FSR_STRENGTH="2"
#################################################################
add_in_start_portwine ()
{
echo " "
}
########################################################################
add_in_stop_portwine ()
{
echo " "
}
########################################################################
pw_other_fixes () {
#fix after installation Origin, for disabled OriginWebHelperService by default
if [ ! -z `cat "${WINEPREFIX}/system.reg" | grep -wm 1 "Origin.exe" | awk '{print $1}'` ] ; then
    sysreg_norig=$(((`cat -n "${WINEPREFIX}/system.reg" | grep OriginWebHelperService | awk '{print $1}'` + 3)))
    sed -i "${sysreg_norig}s/dword:0000000[1-2]/dword:00000003/" "${WINEPREFIX}/system.reg"
fi
#fix after installation PnkBstr*, for disabled PnkBstr* by default
for fix_reg in "PnkBstrA.exe" "PnkBstrB.exe" ; do
    if [ ! -z `cat "${WINEPREFIX}/system.reg" | grep -wm 1 "${fix_reg}" | awk '{print $1}'` ] ; then
        sysreg_norig=$(((`cat -n "${WINEPREFIX}/system.reg" | grep "${fix_reg}" | awk '{print $1}'` + 3)))
        sed -i "${sysreg_norig}s/dword:0000000[1-2]/dword:00000003/" "${WINEPREFIX}/system.reg"
    fi
done
#disabled silent autostart steam
sed -i '/steam.exe\\" -silent"/d' "${WINEPREFIX}/user.reg"
}
