#!/bin/bash
# License GPL
# Author: Tergoev M.A.
########################################################################
export portname=PortProton
export gamename=
export gamedir=
if [ ! -z "${gamedir}" ]; then
    export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/Program Files (x86)/${gamedir}"
fi
export gamestart="${PATH_TO_GAME}/.exe"
export porturl="http://portwine-linux.ru/"
########################################################################
#export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export STAGING_SHARED_MEMORY=1
export PW_LOG=0     # 1-ENABLE_DEBUG_MODE_FOR_TERMINAL 
export PW_NO_VR=1
export PW_NO_D3D9=0
export PW_NO_D3D10=0
export PW_NO_D3D11=0
export PW_NO_D3D12=0
export PW_NO_FSYNC=0
export PW_NO_ESYNC=1
export PW_DXVK_ASYNC=0
export PW_DXGI_NATIVE=0
export PW_USE_SECCOMP=0
export PW_OLD_GL_STRING=0
export PW_NO_WINEMFPLAY=1
export PW_NVAPI_DISABLE=1
export PW_NO_WRITE_WATCH=1
export PW_FORCE_USE_VSYNC=2     # 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
export PW_WINEDBG_DISABLE=1
export PW_PULSE_LOWLATENCY=0
export PW_FORCE_DISABLED_GAMEMOD=0
export PW_FORCE_LARGE_ADDRESS_AWARE=1
########################################################################
ADD_IN_START_PORTWINE ()
{
export launch_parameters=""
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap ` > /dev/null 2>&1  
}
