#!/bin/bash
# License GPL
# Author: Tergoev M.A.
########################################################################
export portname=""
export gamename=""
export gamedir=""
export porturl="http://portwine-linux.ru/"
export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/Program Files (x86)/${gamedir}"
export gamestart="${PATH_TO_GAME}/.exe"
########################################################################
#__NV_PRIME_RENDER_OFFLOAD=1
#__GLX_VENDOR_LIBRARY_NAME=nvidia
#export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export STAGING_SHARED_MEMORY=1
export PROTON_FORCE_LARGE_ADDRESS_AWARE=0
export PROTON_USE_SECCOMP=0
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export WINEDEBUG="-all"
export DXVK_LOG_LEVEL=none
export VKD3D_DEBUG=none
export kill_winedevice=0
export kill_explorer=0
########################################################################
ADD_IN_START_PORTWINE ()
{
if [ "${var_dxvk_on}" -eq "0" ]
then        ###OPENGL###
    export launch_parameters=""
    export vblank_mode=0
    export __GL_SYNC_TO_VBLANK=0
    export PROTON_USE_WINED3D=1
    export PROTON_USE_VKD3D=0
    export PROTON_USE_D9VK=0
    export PROTON_NO_D3D11=0
    export PROTON_NO_D3D10=0
    export PROTON_OLD_GL_STRING=0
else        ###DXVK###
    export launch_parameters=""
    export vblank_mode=1
    export __GL_SYNC_TO_VBLANK=1
    export PROTON_USE_WINED3D=0
    export PROTON_USE_D9VK=0
    export PROTON_USE_VKD3D=0
    export PROTON_NO_D3D11=0
    export PROTON_NO_D3D10=0
    export PROTON_OLD_GL_STRING=0
    export DXVK_ASYNC=0
#   export RADV_PERFTEST=aco
#   export MESA_LOADER_DRIVER_OVERRIDE=zink
fi
########################################################################
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap ` > /dev/null 2>&1  
}
