#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname "`readlink -f "$0"`")"/runlib
"${WINESERVER}" -k
wine_pids=$(ls -l /proc/*/exe 2>/dev/null | grep -E 'wine(64)?-preloader|wineserver' | perl -pe 's;^.*/proc/(\d+)/exe.*$;$1;g;')
if ! [ -z "${wine_pids}" ] ; then
    kill -9 ${wine_pids}
fi
rm -f ${PORT_SCRIPTS_PATH}/winetricks
wget -T 3 --output-document=${PORT_SCRIPTS_PATH}/winetricks https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x "${PORT_SCRIPTS_PATH}/winetricks" 
sed -i '18a . $(dirname $(readlink -f "$0"))/runlib\nSTART_PORTWINE\nexport WINELOADER="${WINEDIR}/bin/wine" ' "${PORT_SCRIPTS_PATH}/winetricks" 
sleep 1
export PW_LOG=1
$PW_TERM "sh ${PORT_SCRIPTS_PATH}/winetricks -q --force"
STOP_PORTWINE
