#!/bin/bash
# Author: PortWINE-Linux.ru
runlib_path="$(dirname $(readlink -f "$0"))"/runlib
. "$runlib_path"
"${WINESERVER}" -k
START_PORTWINE
export WINEDEBUG="fixme-all" 
"${PROTONRUN}" "run" "winecfg" >&2
STOP_PORTWINE
