#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname "`readlink -f "$0"`")"/runlib
"${WINESERVER}" -k
wine_pids=$(ls -l /proc/*/exe 2>/dev/null | grep -E 'wine(64)?-preloader|wineserver' | perl -pe 's;^.*/proc/(\d+)/exe.*$;$1;g;')
if ! [ -z "${wine_pids}" ] ; then
    kill -9 ${wine_pids}
fi
rm -f ${link}/winetricks
"/usr/bin/xterm" -e wget  -T 3 --output-document="${link}/winetricks" https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x "${link}/winetricks" 
sed -i '18a . $(dirname $(readlink -f "$0"))/runlib\nSTART_PORTWINE\nexport WINELOADER="${WINEDIR}/bin/wine" ' "${link}/winetricks" 
sleep 1
export PW_LOG=1
"/usr/bin/xterm" -e "sh ${link}/winetricks -q --force"
STOP_PORTWINE
