#!/bin/bash
# Author: PortWINE-Linux.ru
runlib_path="$(dirname $(readlink -f "$0"))"/runlib
. "$runlib_path"
"${WINESERVER}" -k
START_PORTWINE
export WINEDEBUG="fixme-all" 
if [ ! -z ${optirun_on} ]
then
    ${optirun_on} "${PROTONRUN}" "run" "winecfg" >&2
else
    "${PROTONRUN}" "run" "winecfg" >&2
fi
STOP_PORTWINE
