#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
START_PORTWINE
export WINEDEBUG="fixme-all" 
if [ ! -z ${optirun_on} ]
then
    ${optirun_on} "${PROTONRUN}" "run" "explorer" 
else
    "${PROTONRUN}" "run" "explorer" 
fi
STOP_PORTWINE
