#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
"${WINESERVER}" -k
START_PORTWINE
PW_LOG=1
if [ ! -z ${optirun_on} ]
then
    ${optirun_on} "${port_on_run}" "run" "winecfg" >&2
else
    "${port_on_run}" "run" "winecfg" >&2
fi
STOP_PORTWINE
