#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname "`readlink -f "$0"`")"/runlib
"${WINESERVER}" -k
rm -f ${link}/winetricks
"/usr/bin/xterm" -e wget  -T 3 --output-document="${link}/winetricks" https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
chmod +x "${link}/winetricks" 
sed -i '18a . $(dirname $(readlink -f "$0"))/runlib\nSTART_PORTWINE\nexport WINELOADER="${WINEDIR}/bin/wine" ' "${link}/winetricks" 
sleep 1
"${PROTONRUN}" "run" "winecfg" | pwzen
STOP_PORTWINE
