#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
export PW_LOG=1
START_PORTWINE
if [ ! -z ${optirun_on} ]
then
    $PW_TERM '${PW_RUNTIME}" "${optirun_on}" "${port_on_run}" "run" "cmd"'
else
    $PW_TERM '${PW_RUNTIME}" "${port_on_run}" "run" "cmd"'
fi
STOP_PORTWINE
