#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
START_PORTWINE
PW_LOG=1
if [ ! -z ${optirun_on} ]
then
    ${optirun_on} "${port_on_run}" "run" "explorer" 
else
    "${port_on_run}" "run" "explorer" 
fi
STOP_PORTWINE
