#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
START_PORTWINE
PW_LOG=1
if [ ! -z ${optirun_on} ]
then
    $PW_TERM '"${optirun_on}" "${port_on_run}" "run" "cmd"'
else
    $PW_TERM '"${port_on_run}" "run" "cmd"'
fi
STOP_PORTWINE
