#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
START_PORTWINE
PW_LOG=1
if [ ! -z ${optirun_on} ]
then
    "/usr/bin/xterm" -e '"${optirun_on}" "${port_on_run}" "run" "cmd"'
else
    "/usr/bin/xterm" -e '"${port_on_run}" "run" "cmd"'
fi
STOP_PORTWINE
