#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
START_PORTWINE
export WINEDEBUG="fixme-all" 
"${optirun_on}" ${var_gamemode} "${PROTONRUN}" "run" "explorer" & KILL9_WINEDEVICE >&2
STOP_PORTWINE
