#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/Battle.net-Setup.exe"
export PW_WINE_USE="WINE_LG"
export PW_VULKAN_USE="1"
export LAUNCH_PARAMETERS=""
export WINEDLLOVERRIDES="locationapi="
export PW_WINE_FULLSCREEN_FSR="0"
export PW_USE_EAC_AND_BE="0"

start_portwine
if try_download "https://battle.net/download/getInstallerForGame?os=win&version=LIVE&gameProgram=BATTLENET_APP" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    try_remove_dir "$WINEPREFIX/drive_c/ProgramData/Battle.net"
    pw_kill_autostart Battle.net.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    pw_start_progress_bar_install_game "Battle Net."
    portwine_exe="$(find "$WINEPREFIX/drive_c/" -type f -name "Battle.net.exe" | grep "Battle.net/Battle.net.exe")"
    pw_stop_progress_bar
    portwine_create_shortcut
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
fi
stop_portwine
