#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/q" )
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/CatsLauncher.msi"
export PW_PREFIX_NAME="DOTNET"
export PW_USE_D3D_EXTRAS="1"
export PORTWINE_CREATE_SHORTCUT_NAME="CatsLauncher"

start_portwine
if try_download "https://catswhoplay.com/downloads/CatsLauncher_0.1.10.msi" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "CatsLauncher."
    pw_run msiexec /i "${PW_AUTOINSTALL_EXE}"
    portwine_exe="${WINEPREFIX}/drive_c/Program Files/CatsWhoPlay/Cats Launcher/CatsLauncher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
