#!/usr/bin/env bash
# author: chal55rus
# type: games
# name: ExoTanks
# image: exotanks
# info_en:
# info_ru:
########################################################################
export PW_PREFIX_NAME="EXOTANKS"
export LAUNCH_PARAMETERS=("/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP-")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/ExoTanksMOBA_Setup.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="ExoTanks"
#UE4PrereqSetup
start_portwine
if try_download "https://www.exotanks.com/ExoTanksMOBA_Setup.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "ExoTanks."
    pw_kill_autostart ExoTanksMOBA_Launcher.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Games/ExoTanksMOBA/ExoTanksMOBA_Launcher/Engine/Binaries/Win64/ExoTanksMOBA_Launcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
