#!/usr/bin/env bash
# Author: cefeiko
########################################################################
export PW_WINDOWS_VER=10
export PW_DLL_INSTALL="vcrun2017"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/EveLauncher-2198233.exe"
start_portwine
if try_download "binaries.eveonline.com/EveLauncher-2198233.exe" "${PW_AUTOINSTALL_EXE}"
then
    pw_kill_autostart evelauncher.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe=`find "$WINEPREFIX/drive_c/" -type f -name "evelauncher.exe"`
    pw_stop_progress_bar
    portwine_create_shortcut
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
fi
stop_portwine
