#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/ePSXe205.zip"
start_portwine
if try_download "http://www.epsxe.com/files/ePSXe205.zip" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "Installing the VBA-M. Please wait..."
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/EPSXe"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/EPSXe/ePSXe.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="ePSXe"
    portwine_create_shortcut
fi
stop_portwine
