#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
# type: games
# name: EA App (TEST)
# image: eaapp
# info_en:
# info_ru:
########################################################################
export LAUNCH_PARAMETERS=("/silent" "/repair" )
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/EAappInstaller.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="EALauncher"
export PW_VULKAN_USE="2"
export PW_WINE_USE="PROTON_LG"
export PW_PREFIX_NAME="EAAPP"
export PW_USE_EAC_AND_BE="1"

start_portwine
if try_download "https://origin-a.akamaihd.net/EA-Desktop-Client-Download/installer-releases/EAappInstaller.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "EA Launcher."
    pw_kill_autostart EABackgroundSer 5 please &
    create_new_dir "$WINEPREFIX/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop"
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/Electronic Arts/EA Desktop/EA Desktop/EALauncher.exe"
    pw_stop_progress_bar
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine
