#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export PW_VULKAN_USE=2
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/Hoyolauncher_installer.exe"
export PW_PREFIX_NAME="HoYoPlay"
export PORTWINE_CREATE_SHORTCUT_NAME="HoYoPlay"

start_portwine

if try_download "https://ys-api-os.mihoyo.com/event/download_porter/link/ys_global/genshinimpactpc/default" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_block "Installing HoYoPlay Launcher."
    pw_kill_autostart launcher.exe &
    export PATH_TO_GAME="${PW_USER_TEMP}"
    pw_run "${PW_AUTOINSTALL_EXE}"
    export portwine_exe="$WINEPREFIX/drive_c/Program Files/HoYoPlay/launcher.exe"
    pw_create_unique_exe
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi

stop_portwine
