#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export PW_VULKAN_USE=2
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/gi_installer.exe"
export PW_PREFIX_NAME="GENSHIN_IMPACT"
export PORTWINE_CREATE_SHORTCUT_NAME="Genshin Impact"

start_portwine

if try_download_no_mirror "https://ys-api-os.mihoyo.com/event/download_porter/link/ys_global/genshinimpactpc/default" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "Installing Genshin Impact Launcher. ${loc_gui_please_wait} "
    pw_kill_autostart launcher.exe &
    export PATH_TO_GAME="${PW_USER_TEMP}"
    pw_run "${PW_AUTOINSTALL_EXE}"
    export portwine_exe="$WINEPREFIX/drive_c/Program Files/Genshin Impact/launcher.exe"
    pw_create_unique_exe
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi

stop_portwine

