#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("--silent")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/itch-setup.exe"
start_portwine
if try_download "itch.io/app/download?platform=windows" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "${loc_gui_installing_the} ITCH.IO. ${loc_gui_please_wait} "
    pw_kill_autostart itch.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/itch/app-25.5.1/itch.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Itch"
    portwine_create_shortcut
fi
stop_portwine
