#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("--silent")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/itch-setup.exe"

start_portwine
if try_download "https://itch.io/app/download?platform=windows" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "ITCH.IO."
    pw_kill_autostart itch.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe=$(find "$WINEPREFIX/drive_c/users" -type f -name "itch.exe")
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Itch"
    portwine_create_shortcut
fi
stop_portwine
