#!/usr/bin/env bash
# Author: chal55rus
########################################################################
export PW_PREFIX_NAME="LOST_LIGHT"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/LostLight.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="Lost Light"

start_portwine
if try_download "https://h75na.gdl.easebar.com/LostLight_global_netease_20240903.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "LostLight."
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/LostLight"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/LostLight/launcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
