#!/usr/bin/env bash
# Author: ValoKarDin
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/.exe"
export PW_PREFIX_NAME="MW"

start_portwine

if try_download_game "https://gdn.gaijin.net/launcher/current.php?id=ModernWarshipsLauncher"  "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "Starting Modern Warships installation..."
    pw_kill_autostart launcher.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/ModernWarships/launcher.exe"
    export PORTWINE_CREATE_SHORTCUT_NAME="Modern Warships"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    portwine_create_shortcut
fi

stop_portwine
