#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/mame0237b_64bit.exe"
start_portwine
if try_download "github.com/mamedev/mame/releases/download/mame0237/mame0237b_64bit.exe" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "${loc_gui_installing_the} MAME. ${loc_gui_please_wait} "
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/Mame"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Mame/mame.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="MAME"
    portwine_create_shortcut
fi
stop_portwine
