#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: Metal War Online
# image: mwo
# info_en: A multiplayer online action game with strategic elements, where players control combat robots and battle on various arenas. The game offers extensive customization options for the machines and a variety of game modes, allowing each player to create a unique fighting style.
# info_ru: Многопользовательская онлайн-игра в жанре экшен с элементами стратегии, где игроки управляют боевыми роботами и сражаются на различных аренах. Игра предлагает богатую кастомизацию техники и разнообразные игровые режимы, позволяя каждому игроку создавать уникальный стиль боя.
########################################################################
export LAUNCH_PARAMETERS="/s /nr /l=Russian"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/MWO_Launcher_Setup.exe"
start_portwine
if try_download "http://mwogame.com/download.php" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Metal War Online."
    pw_run "${PW_AUTOINSTALL_EXE}"
    if [[ -d "$WINEPREFIX/drive_c/games/" ]] ; then
        portwine_exe="$WINEPREFIX/drive_c/games/MetalWarOnline/MWOLauncher.exe"
    else
        portwine_exe="$WINEPREFIX/drive_c/Games/MetalWarOnline/MWOLauncher.exe"
    fi
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Metal War Online"
    portwine_create_shortcut
fi
stop_portwine
