#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: emulators
# name: MAME
# image: mame
# info_en: An arcade game emulator that allows classic games to run on modern computers and devices. It supports a wide variety of arcade systems and helps preserve the history of video games by providing access to large collections of retro games.
# info_ru: Эмулятор аркадных игр, позволяющий запускать классические игры на современных компьютерах и устройствах. Он поддерживает множество аркадных систем и способствует сохранению истории видеоигр, предоставляя доступ к большим коллекциям ретро-игр.
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/mame0259b_64bit.exe"
start_portwine
if try_download "https://github.com/mamedev/mame/releases/download/mame0259/mame0259b_64bit.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "MAME."
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/Mame"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Mame/mame.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="MAME"
    portwine_create_shortcut
fi
stop_portwine
