#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/s" )
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/plarium_play_setup.exe"
export PW_WINDOWS_VER="7"
export PW_DLL_INSTALL=""
export LAUNCH_PARAMETERS=""
export PW_PREFIX_NAME="PLARIUM_PLAY"
export PW_MANGOHUD="0"
export PW_MANGOHUD_x32="0"
export PW_MANGOHUD_USER_CONF="0"
export ENABLE_VKBASALT="0"
export PW_NO_ESYNC="1"
export PW_NO_FSYNC="1"
export PW_WINE_FULLSCREEN_FSR="0"
export PW_HIDE_NVIDIA_GPU="0"
export PW_VIRTUAL_DESKTOP="0"
export PW_USE_TERMINAL="0"
export PW_GUI_DISABLED_CS="0"
export PW_USE_GAMEMODE="0"
export PW_DX12_DISABLE="1"
export PW_USE_D3D_EXTRAS="0"
export PW_FIX_VIDEO_IN_GAME="0"
export PW_USE_GSTREAMER="0"
export PW_FORCE_LARGE_ADDRESS_AWARE="1"
export PW_USE_SHADER_CACHE="0"
export PW_USE_WINE_DXGI="0"
export PW_USE_EAC_AND_BE="0"
export WINEDLLOVERRIDES=""

start_portwine
if try_download "https://plarium.com/services/api/downloads/desktop?lid=1&arc=64&os=windows" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "${loc_gui_installing_the} Plarium Play. ${loc_gui_please_wait}"
    pw_kill_autostart PlariumPlay.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/PlariumPlay/PlariumPlay.exe" 
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Plarium Play"
    portwine_create_shortcut
fi
stop_portwine


