#!/usr/bin/env bash
# Author: chal55rus
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PW_WINDOWS_VER="7"
export PW_PREFIX_NAME="PANZAR"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/Panzar.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="Panzar"

start_portwine
if try_download "https://www.panzar.ru/ru/download/installer/" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Panzar."
    pw_kill_autostart start.exe 3 &
    pw_run "${PW_AUTOINSTALL_EXE}"
    export portwine_exe="${WINEPREFIX}/drive_c/Games/Panzar/start.exe"
    pw_create_unique_exe
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
