#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: Stalker Online
# image: so
# info_en: An MMORPG based on the popular S.T.A.L.K.E.R. series, where players can explore the danger Zone, complete quests, fight mutants and other players. The game offers elements of survival and interaction with the open world.
# info_ru: MMORPG, основанная на популярной серии S.T.A.L.K.E.R., где игроки могут исследовать опасную Зону, выполнять квесты, сражаться с мутантами и другими игроками. Игра предлагает элементы выживания и взаимодействия с открытым миром.
########################################################################
export LAUNCH_PARAMETERS="/S"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/SO_installer.exe"
start_portwine
if try_download "https://update-nl-release.stalker.so/launcher/SO_installer.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Stalker Online."
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Game/StalkerOnline/StalkerOnline Launcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Stalker Online"
    portwine_create_shortcut
fi
stop_portwine
