#!/usr/bin/env bash
# Author: chal55rus
########################################################################
export PW_PREFIX_NAME="SWL"
export WINEDLLOVERRIDES="d3d9=b"
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/SecretWorldLegendsMin.exe"

start_portwine
if try_download "https://web-cdn.funcom.com/downloads/swl/SecretWorldLegendsMin.exe" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "${loc_gui_installing_the} Secret World Legends. ${loc_gui_please_wait} "
    pw_kill_autostart ClientPatcher.exe &
#    pw_kill_autostart PatcherSetup.exe &
    pw_run "${PW_AUTOINSTALL_EXE}"
#    portwine_exe="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/SecretWorldLegendsDX11.exe"
    portwine_exe="${WINEPREFIX}/drive_c/Program Files (x86)/Funcom/Secret World Legends/ClientPatcher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Secret World Legends"
    portwine_create_shortcut
fi
stop_portwine
