#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: Tanki Online
# image: tankionline
# info_en:
# info_ru:
########################################################################
export PW_PREFIX_NAME="TANKI_ONLINE"
export LAUNCH_PARAMETERS="/S"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/TankiOnlineSetup.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="Tanki Online"

start_portwine
if try_download "https://tankionline.com/desktop/TankiOnlineSetup.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Tanki Online."
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/Programs/Tanki Online/Tanki Online.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
