#!/usr/bin/env bash
# Author: chal55rus
# type: games
# name: The Lord of the Rings Online (ENG)
# image: lordofringsonline
# info_en:
# info_ru:
########################################################################
export PW_PREFIX_NAME="THE_LORD_OF_THE_RINGS_ONLINE"
export LAUNCH_PARAMETERS="/VERYSILENT /SUPPRESSMSGBOXES /NORESTART /SP- /LANG=en"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/lotrolive.exe"
export PORTWINE_CREATE_SHORTCUT_NAME="The Lord of the Rings Online"

start_portwine
if try_download "https://files.lotro.com/lotro/installers/lotrolive.exe" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "The Lord of the Rings Online."
    pw_run "${PW_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/StandingStoneGames/The Lord of the Rings Online/LotroLauncher.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
