#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: emulators
# name: VBA-M
# image: vba-m
# info_en: The Nintendo Game Boy Advance (GBA) emulator, which allows users to play classic games of this portable console on modern devices. The program supports many functions, including saving the game, setting up controls and the ability to play a multiplayer game over the Internet.
# info_ru: Эмулятор Nintendo Game Boy Advance (GBA), который позволяет пользователям играть в классические игры этой портативной консоли на современных устройствах. Программа поддерживает множество функций, включая сохранение игры, настройка управления и возможность играть в режиме многопользовательской игры через интернет.
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/visualboyadvance-m-Win-x86_64.zip"

start_portwine
if try_download "https://github.com/visualboyadvance-m/visualboyadvance-m/releases/latest/download/visualboyadvance-m-Win-x86_64.zip" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "VBA-M."
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/Visualboyadvance-m"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Visualboyadvance-m/visualboyadvance-m.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="VBA-M"
    portwine_create_shortcut
fi
stop_portwine
