#!/usr/bin/env bash
# Author: Castro Fidel
########################################################################
export LAUNCH_PARAMETERS=("/q")
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/Warframe.msi"
export PORTWINE_CREATE_SHORTCUT_NAME="Warframe"

start_portwine
if try_download "http://content.warframe.com/dl/Warframe.msi" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Warframe."
    pw_kill_autostart Launcher.exe 3 &
    pw_run msiexec /i "${PW_AUTOINSTALL_EXE}"
    export portwine_exe="${WINEPREFIX}/drive_c/users/$USER/AppData/Local/Warframe/Downloaded/Public/Tools/Launcher.exe"
    pw_create_unique_exe "warframe_launcher_pp"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
