#!/usr/bin/env bash
# Author: Cefeiko
########################################################################
export PW_PREFIX_NAME="DOTNET"
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/wos_client.exe"
export LAUNCH_PARAMETERS=("/VERYSILENT")
export PW_DLL_INSTALL="faudio dotnet48"
export PW_VULKAN_USE=1

start_portwine
if try_download "https://165311.selcdn.ru/wosb_installer/wos_client.exe" "${PW_AUTOINSTALL_EXE}"
then
    pw_start_progress_bar_block "Installing World of Sea Battle. ${loc_gui_please_wait} "

    pw_kill_autostart WorldOfSeaBattleClient.exe &
    pw_run "${PW_AUTOINSTALL_EXE}" 
    portwine_exe="$WINEPREFIX/drive_c/Games/World Of Sea Battle/WorldOfSeaBattleClient.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="World of Sea Battle"
    portwine_create_shortcut
fi
stop_portwine
