#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
# type: emulators
# name: Xenia
# image: xenia
# info_en:
# info_ru:
########################################################################
export PW_AUTOINSTALL_EXE="${PW_USER_TEMP}/xenia_master.zip"
start_portwine
if try_download "https://github.com/xenia-project/release-builds-windows/releases/latest/download/xenia_master.zip" "${PW_AUTOINSTALL_EXE}" no_mirror
then
    pw_start_progress_bar_install_game "Xenia."
    "$pw_7z" x -y "${PW_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/xenia"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/xenia/xenia.exe"
    try_remove_file "${PW_AUTOINSTALL_EXE}"
    try_remove_file "${portwine_exe}.ppdb"
    kill_portwine
    pw_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Xenia"
    portwine_create_shortcut
fi
stop_portwine
