#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/VERYSILENT" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/BethesdaNetLauncher_Setup.exe"
start_portwine
if try_download "download.cdp.bethesda.net/BethesdaNetLauncher_Setup.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the BethesdaNetLauncher. Please wait..."
    pp_kill_autostart BethesdaNetLauncher.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Bethesda.net Launcher/BethesdaNetLauncher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Bethesda.net"
    portwine_create_shortcut
fi
stop_portwine
