#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
[ "${update_loc}" = "RUS" ] && export BN_LOC=ruRU || export BN_LOC=enUS
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Battle.net-Setup-${BN_LOC}.exe"
start_portwine
if try_download "dist.blizzard.com/downloads/bna-installers/322d5bb9ae0318de3d4cde7641c96425/retail.1/Battle.net-Setup-${BN_LOC}.exe" "${PP_AUTOINSTALL_EXE}"
then
    # PP_START_PROGRESS_BAR "Installing the Battle Net. Please wait..."
    pp_kill_autostart Battle.net.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe=`find "$WINEPREFIX/drive_c/" -type f -name "Battle.net.exe"`
    pp_stop_progress_bar
    portwine_create_shortcut
    try_remove_file "${PP_AUTOINSTALL_EXE}"
fi
stop_portwine
