#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
#export LAUNCH_PARAMETERS=("")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/citra-setup-windows.exe"
start_portwine
if try_download "github.com/citra-emu/citra-web/releases/download/1.0/citra-setup-windows.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the Citra. Please wait..."
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/Citra/nightly-mingw/citra-qt.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Citra"
    portwine_create_shortcut
fi
stop_portwine
