#!/usr/bin/env bash
# Author: linux-gaming.ru
########################################################################
export PP_URL_CEMU=($(curl -s "https://cemu.info" | grep "zip" | cut -d \" -f 2))
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/`echo ${PP_URL_CEMU} | awk -F/ '{print $5}'`"
start_portwine
if try_download "${PP_URL_CEMU}" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the Cemu. Please wait..."
    "$pp_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/`echo ${PP_URL_CEMU} | awk -F/ '{print $5}' | sed 's/.zip//'`/Cemu.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Cemu"
    portwine_create_shortcut
fi
stop_portwine
