#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("/S")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/dolphin-x64-5.0.exe"
start_portwine
if try_download "dl-mirror.dolphin-emu.org/5.0/dolphin-x64-5.0.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the Dolphin 5.0. Please wait..."
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/Dolphin/Dolphin.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Dolphin 5.0"
    portwine_create_shortcut
fi
stop_portwine
