#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/ePSXe205.zip"
start_portwine
if try_download "www.epsxe.com/files/ePSXe205.zip" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the VBA-M. Please wait..."
    "$pp_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/EPSXe"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/EPSXe/ePSXe.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="ePSXe"
    portwine_create_shortcut
fi
stop_portwine
