#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("/S" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/GlyphInstall.exe"
start_portwine
if try_download "download.dyn.triongames.com/GlyphInstall.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the GlyphClient. Please wait..."
    pp_kill_autostart GlyphClient.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Glyph/GlyphClient.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="GlyphClient"
    portwine_create_shortcut
fi
stop_portwine
