#!/usr/bin/env bash
# Author: chal55rus (Sergey P.), cefeiko, Castro-Fidel (linux-gaming.ru)
##########################################################################
pp_shutdown_please () {
    if [ "$PP_USE_RUNTIME" != 1 ]
    then echo "PP_USE_RUNTIME: `echo $PP_USE_RUNTIME`"
    else
        sleep 10
        while true ; do
            if  [ -z "`ps aux | grep -v grep | grep -wm 1 "$1" | awk '{print $2}'`" ] && [ ! -z "`pgrep wrap | head -n 1`" ]; then
                echo -e "PID "$1" not found"
                sleep 1
            else
                killall -s TERM gfclient.exe
                killall -s TERM GameforgeInstaller.exe
                break
            fi
        done
    fi
}

export LAUNCH_PARAMETERS=("")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/GameforgeInstaller.exe"
start_portwine
if try_download "raw.githubusercontent.com/WarfaceZ/lutris-clients/master/GameforgeInstaller.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Gameforge-Client. Please wait..."
    pp_shutdown_please SparkWebHelper.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/GameforgeClient/gfclient.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="GameforgeClient"
    portwine_create_shortcut
fi
stop_portwine