#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################## 
export LAUNCH_PARAMETERS=("--silent")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/itch-setup.exe"
start_portwine
if try_download "itch.io/app/download?platform=windows" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the ITCH.IO. Please wait..."
    pp_kill_autostart itch.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/itch/app-25.5.1/itch.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Itch"
    portwine_create_shortcut
fi
stop_portwine
