#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export LAUNCH_PARAMETERS=("")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/MyGamesLoader.exe"
start_portwine
if try_download "static.gc.my.games/MyGamesLoader.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the My.Games. Please wait..."
    pp_kill_autostart GameCenter.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/users/steamuser/AppData/Local/GameCenter/GameCenter.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="MY.GAMES"
    portwine_create_shortcut
fi
stop_portwine
