#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/mame0237b_64bit.exe"
start_portwine
if try_download "github.com/mamedev/mame/releases/download/mame0237/mame0237b_64bit.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the MAME. Please wait..."
    "$pp_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files (x86)/Mame"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Mame/mame.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="MAME"
    portwine_create_shortcut
fi
stop_portwine
