#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/silent" "/NoLaunch" )
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/OriginSetup.exe"
start_portwine
if try_download "origin-a.akamaihd.net/Origin-Client-Download/origin/live/OriginThinSetup.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the Origin. Please wait..."
    # pp_kill_autostart Origin.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Origin/Origin.exe"
    pp_stop_progress_bar
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    portwine_create_shortcut
fi
stop_portwine 
