#!/usr/bin/env bash
# Author: cefeiko
########################################################################
export PP_PREFIX_NAME=DOTNET
start_portwine
export PP_DLL_INSTALL="dotnet48"
mkdir -p "${WINEPREFIX}/drive_c/Program Files (x86)/OSU/"
export PP_AUTOINSTALL_EXE="${WINEPREFIX}/drive_c/Program Files (x86)/OSU/osu!.exe"
if try_download "m1.ppy.sh/r/osu!install.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Installing the OSU!. Please wait..."
    if  [ -f "${PORT_WINE_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!install.exe" ]; then
        mv -f  "${PORT_WINE_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!install.exe" "${PORT_WINE_PATH}/data/pfx_dotnet/drive_c/Program Files (x86)/OSU/osu!.exe"
    fi
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/OSU/osu!.exe"
    # pp_run "${PP_AUTOINSTALL_EXE}"
    pp_stop_progress_bar
    portwine_create_shortcut
    kill_portwine
fi
stop_portwine
