#!/usr/bin/env bash
# Author: chal55rus (Sergey P.)
########################################################################
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/Rockstar-Games-Launcher.exe"
start_portwine
if try_download "web.archive.org/web/20210708074247if_/gamedownloads.rockstargames.com/public/installer/Rockstar-Games-Launcher.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_block "Rockstar-Games-Launcher. Please wait..."
    "$pp_7z" x -y "${PP_AUTOINSTALL_EXE}" -o"$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher"
    portwine_exe="$WINEPREFIX/drive_c/Program Files/Rockstar Games/Launcher/Launcher.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    export PORTWINE_CREATE_SHORTCUT_NAME="Rockstar"
    portwine_create_shortcut
fi
stop_portwine
