#!/usr/bin/env bash
# Author: Castro-Fidel (linux-gaming.ru)
########################################################################
export LAUNCH_PARAMETERS=("/S" "/D=c:\Program Files (x86)\Ubisoft Game Launcher")
export PP_AUTOINSTALL_EXE="${PP_USER_TEMP}/UbisoftConnectInstaller.exe"
start_portwine
if try_download "ubistatic3-a.akamaihd.net/orbit/launcher_installer/UbisoftConnectInstaller.exe" "${PP_AUTOINSTALL_EXE}"
then
    pp_start_progress_bar_cs "Installing the Ubisoft Connect. Please wait..."
    pp_kill_autostart UbisoftConnect.exe &
    pp_run "${PP_AUTOINSTALL_EXE}"
    portwine_exe="$WINEPREFIX/drive_c/Program Files (x86)/Ubisoft Game Launcher/UbisoftConnect.exe"
    try_remove_file "${PP_AUTOINSTALL_EXE}"
    kill_portwine
    pp_stop_progress_bar
    portwine_create_shortcut
fi
stop_portwine
