#!/bin/bash
# Author: Tergoev M.A.

read "update_loc" < "${config_path}/${portname}_loc"
export update_loc=${update_loc}

if [ "${update_loc}" = "RUS" ] 
then

	export inst_set="Выбор"
	export inst_set_top="Установка PortWINE"

	export ss_title="Опции запуска:"
	export ss_text="Выбирете желаемый вариант запуска ${portname}. Вы всегда можете изменить свой выбор, \nзапустив ярлык start_settings из каталога: \n"${PORT_WINE_PATH}"/settings/"
	export ss_ver="Версия?"
	export ss_default_1="Cтандартный запуск"
	export ss_default_2="Старый запуск, с вопросами и логами"
	export ss_ogl_2="Использовать библиотеки WINE"

	export inst_succ="Установка завершена успешно!"

	export port_upd1="Обновление PortWINE"
	export port_upd2="На сайте portwine-linux.ru вышло обновление для ${portname}\n"
	export port_upd3="Действие:"
	export port_upd4="Перейти на сайт"
	export port_upd5="Напомнить позже"
	export port_upd6="Больше не напоминать"

	export port_del1="Удаление $portname"
	export port_del2="Вы действительно хотите удалить $portname,\nс установленным в него клиентом?\n"
	export port_del3="Удалить?!"
	export port_del4="Нет, не удалять!"
	export port_del5="Да, удалить!"
	export port_del6="был удален."

	export port_deb1="PortWINE был запущен в режиме создания ${portname}.log и он успешно сохранен в корне каталога порта"
	export port_deb2="Для диагностики проблем, скопируйте ВЕСЬ лог в комментарии к игре на сайте portwine-linux.ru"

	export port_start1="Запуск PortWINE"
	export port_start2="В каком режиме вы хотите запустить PortWINE?"
	export port_start3="Режим:"
	export port_start4="Обычный"
	export port_start5="Отдельной X-сессии"
	export port_start6="Создать ЛОГ-файл"
	export port_start7="Запустить winetricks"
	export port_start8="DXVK"

	export port_time1="Информация"
	export port_time2="Ты думаешь что помочь автору развивать проект это сложно? Нет!\nДостаточно, что бы именно ты пожертвовал сколько считаешь нужным,\nну или хотя бы 50 рублей."
	export port_time3="Действие:"
	export port_time4="Перейти на сайт и помочь развитию проекта"
	export port_time5="Мне жалко потратить даже 50 рублей на проект"
	export port_time6="Я молодец и уже сделал вклад в будущее проекта"

elif [ "${update_loc}" = "ENG" ] 
then

	export inst_set="Sett..."
	export inst_set_top="PortWINE setting"

	export ss_title="Settings::"
	export ss_text="Choose your preferred ${portname} launch option. You can always change your choice by unsetting\nthe start_settings shortcut from the directory:\n"${PORT_WINE_PATH}"/settings/"
	export ss_ver="Version:"
	export ss_default_1="Standard start"
	export ss_default_2="Old startup, with questions and logs"
	export ss_ogl_2="Use the built-in WINE libraries"

	export inst_succ="The installation was successful."

	export port_upd1="New update PortWINE"
	export port_upd2="On portwine-linux.ru site published an update to the ${portname}\n"
	export port_upd3="Action:"
	export port_upd4="Go to the website"
	export port_upd5="Remind me later"
	export port_upd6="Do not remind me"

	export port_del1="Remove $portname" 
	export port_del2="Are you sure you want to delete the ${portname}?\n"
	export port_del3="Remove?!"
	export port_del4="No!"
	export port_del5="Yes!"
	export port_del6="was deleted."
	export port_deb1="PortWINE was launched in creation mode ${portname}.log and it is successfully stored in the root directory of the port"

	export port_deb2="To diagnose the problem, copy ALL of the log in comments to the game on the site portwine-linux.ru"

	export port_start1="Starting the PortWINE"
	export port_start2="In what mode you want to start the PortWINE?"
	export port_start3="Mode:"
	export port_start4="Normal"
	export port_start5="Individual X-Session"
	export port_start6="Create LOG-file"
	export port_start7="Run winetricks"
	export port_start8="DXVK"

	export port_time1="Information"
	export port_time2="Do you think that it is difficult to help the author develop the project? No! It is enough that you would sacrifice what you think is necessary, well, or at least 1$."
	export port_time3="Action:"
	export port_time4="Go to the site and help develop the project"
	export port_time5="I do not want to help the project"
	export port_time6="I'm well done and have already contributed to the future of the project"

fi

