#!/bin/bash
# Author: PortWINE-Linux.ru
. "$(dirname $(readlink -f "$0"))/runlib"
start_settings=`zenity --title  "${ss_title}" --text "${ss_text}" --list --radiolist \
--column="${inst_set}" --column "${ss_ver}" --column "${ss_dr}"  --width=600 --height=300 \
TRUE "${ss_default_1}" "${ss_default_2}" \
FALSE "OpenGL" "${ss_ogl_2}" \
FALSE "DXVK_latest" "AMD/Intel: latest: Nvidia: latest" \
FALSE "DXVK_1.2.3" "AMD/Intel: Mesa 19.1-git+: Nvidia: 418.52.05+" \
FALSE "DXVK_1.0.3" "AMD: Mesa 18.1.2+; Nvidia:396.24.02+" `
if [ $? -eq 1 ];then exit 1; fi
case $start_settings in
	"${ss_default_1}") 
RM_DXVK | sszen
if grep DXVK "${WINEPREFIX}/drive_c/windows/system32/d3d11.dll" || grep DXVK "${WINEPREFIX}/drive_c/windows/syswow64/d3d11.dll" 
then
	echo "error replacing DXVK files"
else
	echo "Ok. DXVK is disabled"
fi
STOP_PORTWINE | sszen
cat > "${link}/start" <<EOF
#!/bin/bash
# Author: Tergoev M.A.
. "\$(dirname \$(readlink -f "\$0"))/runlib"
xsd=\`zenity --title  "\${port_start1}" --text "\${port_start2}" --list --radiolist --height=260 \\
--column="\${inst_set}" --column "\${port_start3}" \\
TRUE "\${port_start4}" \\
FALSE "\${port_start8}"  \`
if [ \$? -eq 1 ];then exit 1; fi
case \$xsd in
	"\${port_start4}")
		START_PORTWINE
		WINE_DX_TO_OPENGL
		OPENGL_SET
		"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"' ;;

	"\${port_start8}")
		START_PORTWINE
		WINE_DX_TO_VULKAN 
		VULKAN_SET
		"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"' ;;
esac 
STOP_PORTWINE
EOF
;;
	"OpenGL") 
RM_DXVK | sszen
if grep DXVK "${WINEPREFIX}/drive_c/windows/system32/d3d11.dll" || grep DXVK "${WINEPREFIX}/drive_c/windows/syswow64/d3d11.dll" 
then
	echo "error replacing DXVK files"
else
	echo "Ok. DXVK is disabled"
fi
STOP_PORTWINE | sszen
cat > "${link}/start" <<EOF
#!/bin/bash
# Author: Tergoev M.A.
. "\$(dirname \$(readlink -f "\$0"))/runlib"
START_PORTWINE
WINE_DX_TO_OPENGL
OPENGL_SET
"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"'
STOP_PORTWINE
EOF
;;
	"DXVK_1.0.3") 
if grep DXVK "${WINEPREFIX}/drive_c/windows/system32/d3d11.dll" || grep DXVK "${WINEPREFIX}/drive_c/windows/syswow64/d3d11.dll" 
then
	RM_DXVK | sszen
	echo "Old DXVK is disabled"
fi
sh "${link}/winetricks" --force dxvk103 | sszen 
STOP_PORTWINE | sszen
echo "New DXVK is enabled"
cat > "${link}/start" <<EOF
#!/bin/bash
# Author: Tergoev M.A.
. "\$(dirname \$(readlink -f "\$0"))/runlib"
START_PORTWINE
WINE_DX_TO_VULKAN 
VULKAN_SET
"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"'
STOP_PORTWINE
EOF
;;
	"DXVK_1.2.3") 
if grep DXVK "${WINEPREFIX}/drive_c/windows/system32/d3d11.dll" || grep DXVK "${WINEPREFIX}/drive_c/windows/syswow64/d3d11.dll" 
then
	RM_DXVK | sszen
	echo "Old DXVK is disabled"
fi
sh "${link}/winetricks" --force dxvk123 | sszen 
STOP_PORTWINE | sszen
echo "New DXVK is enabled"
cat > "${link}/start" <<EOF
#!/bin/bash
# Author: Tergoev M.A.
. "\$(dirname \$(readlink -f "\$0"))/runlib"
START_PORTWINE
WINE_DX_TO_VULKAN 
VULKAN_SET
"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"'
STOP_PORTWINE
EOF
;;
	"DXVK_latest") 
if grep DXVK "${WINEPREFIX}/drive_c/windows/system32/d3d11.dll" || grep DXVK "${WINEPREFIX}/drive_c/windows/syswow64/d3d11.dll" 
then
	RM_DXVK | sszen
	echo "Old DXVK is disabled"
fi
sh "${link}/winetricks" --force dxvk | sszen 
STOP_PORTWINE | sszen
echo "New DXVK is enabled"
cat > "${link}/start" <<EOF
#!/bin/bash
# Author: Tergoev M.A.
. "\$(dirname \$(readlink -f "\$0"))/runlib"
START_PORTWINE
WINE_DX_TO_VULKAN 
VULKAN_SET
"/usr/bin/xterm" -geometry 130x13 -sb -e 'echo "--------------------------------------------------------PORTWINE-LINUX.RU--------------------------------------------------------" && "\${optirun_on}" "\${WINELOADER}" "\${gamestart}" "\${launch_parameters}"'
STOP_PORTWINE
EOF
;;
esac
