#!/bin/bash
# Author: Tergoev M.A.
########################################################################
export gamedir=""
export gamename=""
export portname=""
export porturl=""
export gamestart="c:\\Games\\${gamedir}\\.exe"
export PATH_TO_GAME="${PORT_WINE_PATH}/data/prefix/drive_c/!!!/${gamedir}/"
########################################################################
WINE_DX_TO_OPENGL ()
{
export launch_parameters=""
export WINEDLLOVERRIDES="winemenubuilder.exe=d" 
}
WINE_DX_TO_VULKAN ()
{
export launch_parameters=""
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export DXVK_HUD=fps 
export VK_LOADER_DEBUG=""
export DXVK_LOG_LEVEL=""
}
###.NVIDIA.###
#export LD_PRELOAD="libpthread.so.0 libGL.so.1" 
#export __GL_THREADED_OPTIMIZATIONS=1
export __GL_SHADER_DISK_CACHE=1
export __GL_SHADER_DISK_CACHE_PATH="${PATH_TO_GAME}" 
export __GL_SYNC_TO_VBLANK=0
###.MESA.###
export mesa_glthread="true"
export vblank_mode=0
###.ESYNC and FSYNC.###
export WINEESYNC=0
export WINEFSYNC=1
###.PBA.###
export PBA_DISABLE=1
export __PBA_CB_HEAP=128
export __PBA_GEO_HEAP=512
###.OTHER.###
export WINEDEBUG="-all"
export Xserv=2
#export PULSE_LATENCY_MSEC=60
########################################################################
ADD_IN_START_PORTWINE ()
{
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap `
}
###################################################################
ADD_IN_POST_UNINSTALL ()
{
echo " "
}

