#!/bin/bash
# Author: PortWINE-Linux.ru
########################################################################
export gamedir=" "
export gamename=" "
export portname=" "
export porturl="http://portwine-linux.ru/port-/"
export gamestart="c:\\Games\\${gamedir}\\ .exe"
export PATH_TO_GAME="${PORT_WINE_PATH}/data/prefix/drive_c/Games/${gamedir}/"
########################################################################
export runtime_libs=0
#export LD_PRELOAD="libpthread.so.0 libGL.so.1" 
#export __GL_THREADED_OPTIMIZATIONS=1
#export __GL_SYNC_TO_VBLANK=0
#export vblank_mode=0
export PROTON_FORCE_LARGE_ADDRESS_AWARE=0
export STAGING_SHARED_MEMORY=1 
export WINEDEBUG="-all"
########################################################################
WINE_DX_TO_OPENGL ()
{
export launch_parameters=""
export WINEDLLOVERRIDES="winemenubuilder.exe=d" 
export PROTON_OLD_GL_STRING=0
}
########################################################################
WINE_DX_TO_VULKAN ()
{
export launch_parameters=""
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export DXVK_HUD=fps 
#export PROTON_USE_D9VK=1
}
########################################################################
ADD_IN_START_PORTWINE ()
{
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap `
}
###################################################################
ADD_IN_POST_UNINSTALL ()
{
echo " "
}

