#!/bin/bash
# License GPL
# Author: Tergoev M.A.
########################################################################
export gamename=
export gamedir=
if [ ! -z "${gamedir}" ]; then
    export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/Program Files (x86)/${gamedir}"
fi
export gamestart="${PATH_TO_GAME}/.exe"
export porturl="http://portwine-linux.ru/"
########################################################################
#export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export STAGING_SHARED_MEMORY=1
export PW_LOG=0             # Enable debug mode fo terminal 
export PW_NO_VR=1           # Disabled VR support 
export PW_NO_D3D9=0         # Disable d3d9.dll
export PW_NO_D3D10=0        # Disable d3d10.dll, for d3d10 games which can fall back to and run better with d3d9
export PW_NO_D3D11=0        # Disable d3d11.dll, for d3d11 games which can fall back to and run better with d3d9
export PW_NO_D3D12=0        # Disable d3d12.dll, for d3d12 games which can fall back to and run better with d3d11 or d3d9
export PW_NO_FSYNC=0        # Do not use futex-based in-process synchronization primitives. (Automatically disabled on systems with no FUTEX_WAIT_MULTIPLE support.
export PW_NO_ESYNC=0        # Do not use eventfd-based in-process synchronization primitives
export PW_DXVK_ASYNC=0
export PW_DXGI_NATIVE=0
export PW_USE_TERMINAL=0
export PW_OLD_GL_STRING=0
export PW_NO_WINEMFPLAY=0
export PW_NVAPI_DISABLE=1
export PW_NO_WRITE_WATCH=0          # Disable support for memory write watches in ntdll. This is a very dangerous hack and should only be applied if you have verified that the game can operate without write watches. This improves performance for some very specific games (e.g. CoreRT-based games).
export PW_HIDE_NVIDIA_GPU=0
export PW_FORCE_USE_VSYNC=2         # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
export PW_WINEDBG_DISABLE=1
export PW_PULSE_LOWLATENCY=0
export PW_FORCE_DISABLED_GAMEMOD=0              # Force disabele gamemod
export PW_FORCE_LARGE_ADDRESS_AWARE=1           # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
########################################################################
ADD_IN_START_PORTWINE ()
{
export launch_parameters=""
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap ` > /dev/null 2>&1  
}
