#!/bin/bash
# License GPL
# Author: Tergoev M.A.
########################################################################
export portname="PortMailRu"
export gamename="GameMailRu"
export gamedir="GameCenter"
export porturl="http://portwine-linux.ru/mail-ru-linux"
if [ ! -z "${gamedir}" ]; then
    export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/users/steamuser/Local Settings/Application Data/${gamedir}"
fi
export gamestart="${PATH_TO_GAME}/GameCenter.exe"
########################################################################
export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export STAGING_SHARED_MEMORY=0
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export PW_LOG=0
export PW_ACO=1
export PW_NO_VR=1
export PW_FILELOCK=1
export PW_DXVK_ASYNC=0
export PW_USE_SECCOMP=1
export PW_NO_WINEMFPLAY=0
export PW_NVAPI_DISABLE=1
export PW_NO_WRITE_WATCH=1
export PW_WINEDBG_DISABLE=1
export PW_PULSE_LOWLATENCY=1
export PW_FORCE_LARGE_ADDRESS_AWARE=1
########################################################################
ADD_IN_START_PORTWINE ()
{
export launch_parameters=""
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
`zenity --info --title "${inst_set_top}" --text "${inst_succ}" --no-wrap ` > /dev/null 2>&1  
}
