#!/bin/bash
# Author: PortWINE-Linux.ru
########################################################################
export gamename="GameMailRu"
export gamedir="GameCenter"
export porturl="http://portwine-linux.ru/mail-ru-linux"
export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/users/steamuser/Local Settings/Application Data/${gamedir}"
export gamestart="${PATH_TO_GAME}/GameCenter.exe"
########################################################################
export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export PW_LOG=0
export PW_ACO=1
export PW_NO_VR=1
export PW_FILELOCK=1
export PW_DXVK_ASYNC=0
export PW_USE_SECCOMP=1
export PW_NO_WINEMFPLAY=0
export PW_NVAPI_DISABLE=1
export PW_NO_WRITE_WATCH=1
export PW_WINEDBG_DISABLE=1
export PW_FORCE_LARGE_ADDRESS_AWARE=1
#export MANGOHUD=1
########################################################################
ADD_IN_START_PORTWINE ()
{
export LAUNCH_PARAMETERS=""
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
echo " "
}
