#!/bin/bash
# License GPL
# Author: Tergoev M.A.
########################################################################
export portname="PortLoL"
export gamename="League_of_Legends"
export gamedir="Riot Games/Riot Client"
export porturl="http://portwine-linux.ru/league-of-legends-linux/"
export PATH_TO_GAME="${PORT_WINE_PATH}/data/pfx/drive_c/${gamedir}"
export gamestart="${PATH_TO_GAME}/RiotClientServices.exe"
########################################################################
#export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export WINEDLLOVERRIDES="winemenubuilder.exe=d"
export PW_LOG=0
export PW_ACO=1
export PW_NO_VR=1
export PW_NO_FSYNC=1
export PW_NO_ESYNC=1
export PW_FILELOCK=1
export PW_DXVK_ASYNC=0
export PW_USE_SECCOMP=0
export PW_NO_WINEMFPLAY=0
export PW_NVAPI_DISABLE=1
export PW_NO_WRITE_WATCH=1
export PW_WINEDBG_DISABLE=1
export PW_FORCE_LARGE_ADDRESS_AWARE=0
########################################################################
ADD_IN_START_PORTWINE ()
{
export launch_parameters="--launch-product=league_of_legends --launch-patchline=live"
cd "${PATH_TO_GAME}"

if [ "$(cat /proc/sys/abi/vsyscall32)" -ne 0 ]
then
    zenity --question --title="Fix for LoL anti-cheat" \
           --text='Root rights are required to execute the command:           \n"sysctl -w abi.vsyscall32=0" and "sysctl -p"' --no-wrap
    if [ "$?" = 1 ]
    then
        exit 0
    fi
    pkexec sh -c 'sysctl -w abi.vsyscall32=0 && sysctl -p'
fi
sh "${PORT_SCRIPTS_PATH}"/fix_start_lol.sh | zenity --progress --title="Start PortLoL" --text="Please wait, launch is in progress, it may take few minutes" --pulsate --auto-close --auto-kill --width=450 &
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
echo " "
}

