#!/bin/bash
# Author: PortWINE-Linux.ru
########################################################################
export porturl="http://portwine-linux.ru/"
########################################################################
#export MESA_GL_VERSION_OVERRIDE=4.4COMPAT
export PW_LOG=0             # Enable debug mode fo terminal 
export PW_USE_TERMINAL=0
export PW_NVAPI_DISABLE=1
export PW_FORCE_USE_VSYNC=2         # Vsync: 0-FORCE_OFF, 1-FORCE_ON, 2-BY_DEFAULT
export PW_WINEDBG_DISABLE=0
export PW_FORCE_DISABLED_GAMEMOD=0              # Force disabele gamemod
#export PW_FORCE_LARGE_ADDRESS_AWARE=1           # Force Wine to enable the LARGE_ADDRESS_AWARE flag for all executables. Enabled by default.
export PULSE_LATENCY_MSEC=60
#export PW_MANGOHUD=1
#export MANGOHUD_CONFIG=full,height=500,font_size=32,position=top-right,toggle_hud=F9
#export DXVK_HUD=fps,devinfo
########################################################################
ADD_IN_START_PORTWINE ()
{
cd "${PATH_TO_GAME}"
}
########################################################################
ADD_IN_STOP_PORTWINE ()
{	
echo " "
}
########################################################################
ADD_IN_POST_INSTALL ()
{
update-desktop-database -q "${HOME}/.local/share/applications"
}
